import { FlashCardItem } from "@/shared/component/flash-card/flash-card";

export const cards: FlashCardItem[] = [
  {
    front: "～がてら",
    back: [
      "✨ Nhân tiện (làm A nhân tiện làm B)",
      "・Ví dụ: Đi dạo nhân tiện ghé cửa hàng tiện lợi.",
      "📌 Hành động chính kèm hành động phụ, thường có yếu tố di chuyển.",
    ],
    more: [
      "🧩 N / Vます + がてら",
      "⚖️ ～ついでに (không nhấn yếu tố di chuyển), ～ながら (đồng thời)",
      "💬 Thường dùng trong văn nói, mang tính cá nhân.",
      "📝 ví dụ",
      "・散歩がてらコンビニに寄った",
      "・写真を撮りがてら山を登った",
    ],
    questions: [
      {
        id: "1-1",
        content: "ドライブ___、新しい喫茶店に行ってみた",
        answers: ["ながら", "につれて", "がてら", "ついでに"],
        correctAnswer: 2,
        memo: [
          "ながら: Diễn tả hai hành động đồng thời có chủ ý (vừa A vừa B), không nhấn yếu tố 'nhân tiện'.",
          "につれて: Diễn tả sự thay đổi tỷ lệ thuận (A thay đổi thì B thay đổi), không phù hợp.",
          "がてら: Hành động chính (lái xe) kèm hành động phụ (ghé quán cà phê), có yếu tố di chuyển và mục đích 'nhân tiện'. (Đúng)",
          "ついでに: Cũng là 'nhân tiện' nhưng がてら được coi là trang trọng hơn và nhấn mạnh yếu tố di chuyển.",
        ],
      },
      {
        id: "1-2",
        content: "買い物___、本屋にも寄った",
        answers: ["がてら", "のせいで", "をめぐって", "のところに"],
        correctAnswer: 0,
        memo: [
          "がてら: Hành động chính (mua sắm) kèm hành động phụ (ghé nhà sách), có yếu tố di chuyển và mục đích 'nhân tiện'. (Đúng)",
          "のせいで: 'Tại vì...' (lý do tiêu cực), không phải ngữ pháp đồng thời.",
          "をめぐって: 'Xoay quanh/Về vấn đề...', không liên kết hành động.",
          "のところに: Không phải ngữ pháp liên kết hành động 'nhân tiện'.",
        ],
      },
      {
        id: "1-3",
        content: "故郷のニュースを聞く___、昔のことを思い出す",
        answers: ["ながら", "つつ", "につけ", "がてら"],
        correctAnswer: 2,
        memo: [
          "ながら: Diễn tả hành động đồng thời có ý thức, không phù hợp với ngữ cảnh 'mỗi khi nghe tin quê hương' kéo theo cảm xúc/trạng thái (nhớ lại).",
          "つつ: Diễn tả hành động đồng thời (trang trọng hơn ながら) hoặc đối lập, không phù hợp với ngữ cảnh 'mỗi khi nghe tin quê hương' kéo theo cảm xúc/trạng thái (nhớ lại).",
          "につけ: Diễn tả 'mỗi khi/hễ cứ' (thường đi kèm với cảm xúc/tâm trạng: nhớ lại kỷ niệm). (Đúng)",
          "がてら: Diễn tả 'nhân tiện làm gì' (có chủ đích, di chuyển), không phù hợp với việc nhớ lại kỷ niệm.",
        ],
      },
    ],
  },
  {
    front: "～なり",
    back: [
      "✨ Ngay sau khi (vừa A thì ngay lập tức B xảy ra)",
      "・Ví dụ: Anh ấy vừa nhận điện thoại xong thì lập tức đứng dậy và ra khỏi phòng.",
      "📌 Hành động B là bất ngờ, ngoài ý muốn và xảy ra ngay sau A. Chỉ dùng cho ngôi thứ ba.",
    ],
    more: [
      "🧩 Vる + なり",
      "⚖️ ～やいなや / ～が早いか (dùng cho hành động mang tính khách quan hơn)",
      "💬 Văn viết hoặc nói trang trọng, mang tính kịch tính.",
      "📝 ví dụ",
      "・彼は電話を受けるなり、席を立って部屋を出ていった",
      "・子供は母親の顔を見るなり、わっと泣き出した",
    ],
    questions: [
      {
        id: "2-1",
        content: "家に帰る___、すぐさまベッドに倒れ込んだ",
        answers: ["とたんに", "わけではない", "なり", "かぎり"],
        correctAnswer: 2,
        memo: [
          "とたんに: 'Ngay sau khi', nhấn mạnh sự thay đổi đột ngột (thường dùng cho hiện tượng tự nhiên).",
          "わけではない: 'Không hẳn là...' (phủ định một phần), không phải ngữ pháp chỉ thời gian tức thì.",
          "なり: 'Ngay sau khi'. Hành động 'ngã vật ra giường' là bất ngờ, ngoài ý muốn và xảy ra tức thì sau khi về nhà. Phù hợp với tính chất của ngữ pháp này. (Đúng)",
          "かぎり: 'Chừng nào còn...' (chỉ giới hạn thời gian/điều kiện), không phù hợp.",
        ],
      },
      {
        id: "2-2",
        content: "終業のベルを聞く___、学生たちは教室から飛び出していった",
        answers: ["が早いか", "なり", "わけにはいかない", "において"],
        correctAnswer: 0,
        memo: [
          "が早いか: 'Ngay sau khi'. Nhấn mạnh tính tức thì và hành động mang tính bản năng, tập thể (học sinh ùa ra khỏi lớp) hơn. Phù hợp với ngữ cảnh khách quan này. (Đúng)",
          "なり: Thường nhấn mạnh hành động bất ngờ của cá nhân (ngôi thứ ba) hơn.",
          "わけにはいかない: 'Không thể (vì lý do nghĩa vụ)', không phù hợp.",
          "において: 'Trong/Ở lĩnh vực...', không phù hợp.",
        ],
      },
      {
        id: "2-3",
        content: "彼は社長の顔を見る___、緊張のあまり言葉を失った",
        answers: ["をものともせず", "なり", "やいなや", "が早いか"],
        correctAnswer: 1,
        memo: [
          "をものともせず: 'Bất chấp...', không phù hợp.",
          "なり: 'Ngay sau khi'. Hành động B (mất lời vì căng thẳng) là phản ứng bất ngờ, ngoài ý muốn ngay sau khi thấy mặt, dùng cho ngôi thứ ba (anh ấy). Rất phù hợp. (Đúng)",
          "やいなや: 'Ngay sau khi', trang trọng, dùng cho hành động bất ngờ, mang tính khách quan.",
          "が早いか: 'Ngay sau khi', nhấn mạnh hành động bản năng, lặp lại.",
        ],
      },
    ],
  },
  {
    front: "～手前（てまえ）",
    back: [
      "✨ Vì đứng trước/vì đã hứa/vì thể diện (nên phải làm gì)",
      "・Ví dụ: Vì đã hứa với con trai, nên dù bận tôi cũng phải đi.",
      "📌 Hành động tiếp theo là bắt buộc phải làm vì giữ thể diện hoặc lời đã hứa.",
    ],
    more: [
      "🧩 Vる / Nの + 手前",
      "⚖️ ～以上は (cũng là 'một khi đã', nhưng 手前 nhấn mạnh yếu tố thể diện)",
      "💬 Văn nói và viết, trang trọng, dùng để biện minh hoặc giải thích.",
      "📝 ví dụ",
      "・息子と遊園地へ行く約束をした手前、忙しくても行かないわけにはいかない",
      "・合格すると宣言した手前、勉強しないわけにはいかない",
    ],
    questions: [
      {
        id: "3-1",
        content:
          "上司に終わらせる___、何が何でも今日の内にやり遂げなければならない",
        answers: ["以上は", "限りで", "手前", "かぎりだ"],
        correctAnswer: 2,
        memo: [
          "以上は: 'Một khi đã...', cũng là nghĩa vụ nhưng không nhấn mạnh yếu tố 'thể diện' mạnh bằng 手前.",
          "限りで: 'Cho đến hết' (tuyên bố chấm dứt), không phù hợp.",
          "手前: 'Vì thể diện/vì đã nhận lời'. Vì đã nhận lời (từ cấp trên) là phải hoàn thành, nên phải làm bằng mọi giá. Nhấn mạnh nghĩa vụ giữ lời hứa/thể diện. (Đúng)",
          "かぎりだ: 'Vô cùng' (chỉ cảm xúc), không phù hợp.",
        ],
      },
      {
        id: "3-2",
        content: "自分が引き受けると宣言した___、途中でやめるわけにはいかない",
        answers: ["にもかかわらず", "手前", "につけ", "というのに"],
        correctAnswer: 1,
        memo: [
          "にもかかわらず: 'Mặc dù...', chỉ sự đối lập (Mặc dù tuyên bố nhưng vẫn bỏ cuộc), không phù hợp với vế sau.",
          "手前: 'Vì thể diện/vì đã nhận lời'. Vì đã tuyên bố nhận trách nhiệm nên không thể bỏ cuộc giữa chừng (phải giữ lời hứa/thể diện). (Đúng)",
          "につけ: 'Mỗi khi/hễ cứ', không phù hợp.",
          "というのに: 'Mặc dù...' (chỉ sự đối lập, tiếc nuối), không phù hợp.",
        ],
      },
      {
        id: "3-3",
        content: "周りの人たちの前で言った___、実行するしかない",
        answers: ["にあたって", "をいいことに", "の限り", "上は"],
        correctAnswer: 3,
        memo: [
          "にあたって: 'Nhân dịp/Khi bắt đầu', không phù hợp.",
          "をいいことに: 'Lợi dụng...', không phù hợp.",
          "の限り: 'Hết mức có thể', không phải ngữ pháp liên kết điều kiện - kết quả.",
          "上は: 'Một khi đã...' (sau khi đã nói trước mọi người thì hành động tiếp theo là tất yếu/nghĩa vụ phải làm). (Đúng)",
        ],
      },
    ],
  },
  {
    front: "～を限りに／限りで",
    back: [
      "✨ Hết/Cho đến hết (dùng để tuyên bố chấm dứt một điều gì đó)",
      "・Ví dụ: Với ngày hôm nay là hết, tôi sẽ nghỉ việc.",
      "📌 Luôn đi kèm với danh từ chỉ thời gian và hành động sau là chấm dứt hoàn toàn.",
    ],
    more: [
      "🧩 N + を限りに / 限りで",
      "⚖️ ～をもって (cũng là 'kết thúc', nhưng をもって trang trọng hơn, dùng cho sự kiện công cộng)",
      "💬 Trang trọng, dùng trong thông báo chính thức.",
      "📝 ví dụ",
      "・今日を限りに、会社を辞めさせていただきます",
      "・この度の講義を限りで、もう参加しません",
    ],
    questions: [
      {
        id: "4-1",
        content: "本日___、当店は閉店させていただきます",
        answers: ["を限りに", "をもって", "かぎりだ", "限り"],
        correctAnswer: 0,
        memo: [
          "を限りに: 'Hết/Cho đến hết' (tuyên bố chấm dứt, thường dùng cho thông báo chính thức của cửa hàng/công ty). Phù hợp nhất. (Đúng)",
          "をもって: Cũng là 'kết thúc' (thường dùng cho các sự kiện công cộng, mang tính hành chính cao hơn).",
          "かぎりだ: 'Vô cùng' (chỉ cảm xúc), không phù hợp.",
          "限り: 'Chừng nào còn...' hoặc 'Hết mức có thể', không phù hợp với ngữ cảnh 'tuyên bố chấm dứt'.",
        ],
      },
      {
        id: "4-2",
        content: "本年度___、この制度を廃止いたします",
        answers: ["に限って", "をもって", "に限らず", "にかぎりでは"],
        correctAnswer: 1,
        memo: [
          "に限って: 'Chỉ riêng...' hoặc 'Thông thường...', không phù hợp.",
          "をもって: 'Kể từ/Cho đến hết' (thông báo kết thúc, thường dùng cho các sự kiện/chính sách công cộng, mang tính hành chính). Phù hợp với việc bãi bỏ chế độ. (Đúng)",
          "に限らず: 'Không chỉ...', không phù hợp.",
          "にかぎりでは: 'Theo như trong phạm vi...', không phù hợp.",
        ],
      },
      {
        id: "4-3",
        content: "このイベントを___、部長は引退する予定だ",
        answers: ["を限りに", "をもって", "限りで", "限りだ"],
        correctAnswer: 2,
        memo: [
          "を限りに: 'Hết/Cho đến hết' (dùng cho mốc thời gian, sự kiện). Có thể dùng nhưng '限りで' phổ biến hơn với danh từ chỉ sự kiện.",
          "をもって: 'Kể từ/Cho đến hết' (trang trọng hơn, thường dùng cho thông báo công cộng).",
          "限りで: 'Hết/Cho đến hết' (dùng để tuyên bố chấm dứt). Phù hợp với việc lấy sự kiện (N) làm mốc kết thúc hành động cá nhân (nghỉ hưu). (Đúng)",
          "限りだ: 'Vô cùng' (chỉ cảm xúc), không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～限りだ",
    back: [
      "✨ Cực kỳ/Vô cùng (thể hiện cảm xúc mạnh mẽ của người nói)",
      "・Ví dụ: Thấy anh ấy thành công, tôi vô cùng vui mừng.",
      "📌 Luôn đi kèm với tính từ chỉ cảm xúc (vui, buồn, hối hận...) và là cách nói trang trọng.",
    ],
    more: [
      "🧩 Vる / Aい / Naである + 限りだ",
      "⚖️ ～というものだ (thật là.../mang tính khách quan hơn)",
      "💬 Văn viết, trang trọng.",
      "📝 ví dụ",
      "・彼の成功を見て、喜ばしい限りだ",
      "・自分の軽率な行動を反省し、悔しい限りだ",
    ],
    questions: [
      {
        id: "5-1",
        content: "彼のような若者が国を担うことは、心強い___",
        answers: ["限りだ", "ばかりだ", "一方だ", "ものだ"],
        correctAnswer: 0,
        memo: [
          "限りだ: 'Vô cùng'. Đi kèm với tính từ chỉ cảm xúc (心強い - an tâm, vững tâm) để nhấn mạnh cảm xúc mạnh mẽ của người nói. (Đúng)",
          "ばかりだ: Diễn tả sự thay đổi theo một chiều hướng (chỉ tăng/chỉ giảm), không phù hợp.",
          "一方だ: Diễn tả sự thay đổi theo một chiều hướng (chỉ tăng/chỉ giảm), không phù hợp.",
          "ものだ: 'Thật là...' (mang tính khách quan) hoặc 'Thường hay...', không nhấn mạnh cảm xúc mạnh mẽ như 限りだ.",
        ],
      },
      {
        id: "5-2",
        content: "自分の不注意で事故を起こし、恥ずかしい___",
        answers: ["限りだ", "限りで", "かぎり", "を限りに"],
        correctAnswer: 0,
        memo: [
          "限りだ: 'Vô cùng'. Đi kèm với tính từ chỉ cảm xúc (恥ずかしい - xấu hổ) để nhấn mạnh cảm xúc mạnh mẽ, trang trọng. (Đúng)",
          "限りで: 'Cho đến hết' (tuyên bố chấm dứt), không phù hợp.",
          "かぎり: 'Chừng nào còn...', không phù hợp.",
          "を限りに: 'Cho đến hết' (tuyên bố chấm dứt), không phù hợp.",
        ],
      },
      {
        id: "5-3",
        content: "皆様の温かいお心遣いに、感謝の___",
        answers: ["限り", "限りだ", "を限りに", "限りで"],
        correctAnswer: 1,
        memo: [
          "限り: Nếu không có だ, câu sẽ không hoàn chỉnh trong ngữ cảnh trang trọng này.",
          "限りだ: 'Vô cùng biết ơn' (chỉ cảm xúc mạnh mẽ). Danh từ 感謝 (Lòng biết ơn) đi với の và 限りだ. (Đúng)",
          "を限りに: 'Cho đến hết' (tuyên bố chấm dứt), không phù hợp.",
          "限りで: 'Cho đến hết' (tuyên bố chấm dứt), không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～あっての",
    back: [
      "✨ Chính vì/Nhờ có (Nhấn mạnh A là điều kiện tiên quyết để có B)",
      "・Ví dụ: Thành công ngày hôm nay chính là nhờ có sự hỗ trợ của mọi người.",
      "📌 A là điều kiện quan trọng nhất, không có A thì không có B. Thường là các danh từ trừu tượng.",
    ],
    more: [
      "🧩 N + あっての + N",
      "⚖️ ～のおかげで (cũng là 'nhờ có', nhưng あっての nhấn mạnh mối quan hệ phụ thuộc mạnh mẽ hơn)",
      "💬 Văn viết trang trọng hoặc văn nói nhấn mạnh.",
      "📝 ví dụ",
      "・今日の成功は、皆さんの協力あってのものです",
      "・健康あっての仕事だ。無理をして体を壊してはいけない",
    ],
    questions: [
      {
        id: "6-1",
        content: "このプロジェクトの成功は、チームワーク___成果だ",
        answers: ["あっての", "おかげで", "ならではの", "ならでは"],
        correctAnswer: 0,
        memo: [
          "あっての: 'Chính vì/Nhờ có'. Nhấn mạnh Teamwork là điều kiện tiên quyết, không có nó thì không có thành công. Phù hợp nhất với ý nghĩa 'phụ thuộc lẫn nhau'. (Đúng)",
          "おかげで: 'Nhờ có', không nhấn mạnh mối quan hệ phụ thuộc tuyệt đối bằng あっての.",
          "ならではの: 'Chỉ có ở/chỉ riêng' (đi kèm danh từ), không phù hợp.",
          "ならでは: 'Chỉ có ở/chỉ riêng' (kết thúc câu), không phù hợp.",
        ],
      },
      {
        id: "6-2",
        content: "お客様の支持___ビジネスだ。常に謙虚でなければならない",
        answers: ["にとっての", "のおかげ", "あっての", "をめぐっての"],
        correctAnswer: 2,
        memo: [
          "にとっての: 'Đối với...', không phù hợp.",
          "のおかげ: 'Nhờ có...', đúng nhưng あっての nhấn mạnh mối quan hệ phụ thuộc tuyệt đối mạnh mẽ hơn.",
          "あっての: 'Chính vì/Nhờ có'. Nhấn mạnh Business (B) phụ thuộc hoàn toàn vào sự ủng hộ của khách hàng (A). Không có A thì không có B. (Đúng)",
          "をめぐっての: 'Xoay quanh...', không phù hợp.",
        ],
      },
      {
        id: "6-3",
        content: "信頼___友情だ。嘘をついてはいけない",
        answers: ["にあって", "にして", "にあらず", "あっての"],
        correctAnswer: 3,
        memo: [
          "にあって: 'Trong hoàn cảnh...', không phù hợp.",
          "にして: 'Đến cả...', không phù hợp.",
          "にあらず: 'Không phải là...', không phù hợp.",
          "あっての: 'Chính vì/Nhờ có'. Nhấn mạnh Tình bạn (B) phụ thuộc hoàn toàn vào niềm tin (A). Không có A thì không có B. (Đúng)",
        ],
      },
    ],
  },
  {
    front: "～だの～だの",
    back: [
      "✨ Nào là... nào là... (Liệt kê các ví dụ tiêu cực, thể hiện sự chán nản/bất mãn)",
      "・Ví dụ: Anh ấy lúc nào cũng than phiền nào là tiền không đủ, nào là công việc vất vả.",
      "📌 Liệt kê các ví dụ tiêu cực hoặc không quan trọng, bày tỏ sự khó chịu, chán ghét của người nói.",
    ],
    more: [
      "🧩 N / Vる / Aい / Na + だの + ...",
      "⚖️ ～やら～やら (cũng là liệt kê, nhưng không mang ý nghĩa tiêu cực mạnh mẽ như だのだの)",
      "💬 Văn nói suồng sã, mang tính phàn nàn, tiêu cực.",
      "📝 ví dụ",
      "・彼はいつも給料が安いだの、仕事がつらいだのと愚痴ばかり言っている",
      "・彼女の暑いだの寒いだのという文句はもう聞き飽きた",
    ],
    questions: [
      {
        id: "7-1",
        content:
          "このレストランは、料理が遅い___、サービスが悪い___と評判が悪い",
        answers: ["やら/やら", "だの/だの", "につけ/につけ", "なら/なり"],
        correctAnswer: 1,
        memo: [
          "やら/やら: Cũng là liệt kê, nhưng không mang ý phàn nàn/tiêu cực mạnh mẽ như だの/だの.",
          "だの/だの: 'Nào là... nào là...'. Dùng để liệt kê các yếu tố tiêu cực (món ăn chậm, dịch vụ tệ) dẫn đến kết quả tiêu cực (tiếng xấu). Rất phù hợp. (Đúng)",
          "につけ/につけ: 'Mỗi khi A hay B...', không phù hợp.",
          "なら/なり: 'Nếu là A thì phải làm tương xứng...', không phù hợp.",
        ],
      },
      {
        id: "7-2",
        content: "彼女は、忙しい___疲れた___と、いつも言い訳ばかりする",
        answers: ["といい/といい", "にしろ/にしろ", "なり/なり", "だの/だの"],
        correctAnswer: 3,
        memo: [
          "といい/といい: 'Cả A và B...', mang tính liệt kê ví dụ tốt/xấu nhưng không nhấn mạnh sự phàn nàn/bất mãn.",
          "にしろ/にしろ: 'Dù là A hay là B...', mang tính bao hàm, không phù hợp.",
          "なり/なり: 'Hoặc là A hoặc là B' (chỉ sự lựa chọn), hoặc 'Nếu là A thì phải tương xứng...', không phù hợp.",
          "だの/だの: 'Nào là... nào là...'. Dùng để liệt kê các lý do (bận, mệt) để phàn nàn/biện minh (luôn đưa ra lời bào chữa). Thể hiện sự khó chịu của người nói. (Đúng)",
        ],
      },
      {
        id: "7-3",
        content: "うるさい___、遅い___と、文句ばかり言われた",
        answers: ["わ/わ", "にかぎり", "だの/だの", "をいいことに"],
        correctAnswer: 2,
        memo: [
          "わ/わ: Cũng là liệt kê các yếu tố tiêu cực, nhưng thường đi kèm với kết quả tổng hợp (ví dụ: điện thoại hỏng, ví mất, *kết quả là* một ngày tồi tệ), ít dùng để chỉ sự phàn nàn lặp đi lặp lại.",
          "にかぎり: 'Chỉ riêng...', không phù hợp.",
          "だの/だの: 'Nào là... nào là...'. Liệt kê các lỗi lầm (ồn ào, chậm chạp) để thể hiện sự phàn nàn (luôn bị phàn nàn). (Đúng)",
          "をいいことに: 'Lợi dụng...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～であれ～であれ",
    back: [
      "✨ Dù là A hay là B (thì kết quả vẫn không thay đổi, mang tính bao hàm)",
      "・Ví dụ: Dù là đàn ông hay phụ nữ thì lao động chân chính đều phải được tôn trọng.",
      "📌 Liệt kê hai trường hợp tương phản hoặc đối lập, kết quả sau đó là luôn luôn đúng với cả hai trường hợp.",
    ],
    more: [
      "🧩 N / Vる / Aい / Na + であれ + ...",
      "⚖️ ～にしろ～にしろ (cũng là 'dù là/hay là', nhưng であれであれ trang trọng và bao quát hơn)",
      "💬 Văn viết trang trọng.",
      "📝 ví dụ",
      "・男であれ女であれ、正当な労働は尊重されるべきだ",
      "・勝つであれ負けるであれ、初めの気持ちを忘れてはいけない",
    ],
    questions: [
      {
        id: "8-1",
        content: "正社員___アルバイト___、仕事に対する責任は同じだ",
        answers: [
          "にしても/にしても",
          "であれ/であれ",
          "といい/といい",
          "ばかりか/も",
        ],
        correctAnswer: 1,
        memo: [
          "にしても/にしても: 'Dù là A hay là B' (ít trang trọng hơn).",
          "であれ/であれ: 'Dù là A hay là B'. Liệt kê hai đối tượng (nhân viên chính thức và bán thời gian) để khẳng định một sự thật chung (trách nhiệm là như nhau). Trang trọng và bao quát. (Đúng)",
          "といい/といい: 'Cả A và B đều...', mang tính liệt kê ví dụ tiêu biểu.",
          "ばかりか/も: 'Không chỉ A mà còn B', không phù hợp.",
        ],
      },
      {
        id: "8-2",
        content: "どんなに小さなミス___大きなミス___、すぐに報告するべきだ",
        answers: ["であれ/であれ", "において/は", "はする/が", "につけ/につけ"],
        correctAnswer: 0,
        memo: [
          "であれ/であれ: 'Dù là A hay là B'. Liệt kê hai mức độ đối lập (sai lầm nhỏ hay sai lầm lớn) để khẳng định một yêu cầu chung (đều phải báo cáo ngay). (Đúng)",
          "において/は: 'Trong lĩnh vực...', không phù hợp.",
          "はする/が: 'Có làm nhưng...', không phù hợp.",
          "につけ/につけ: 'Mỗi khi A hay B...', không phù hợp.",
        ],
      },
      {
        id: "8-3",
        content: "晴天___雨天___、明日の遠足は決行する",
        answers: [
          "にしても/にしても",
          "なり/なり",
          "を問わず",
          "であれ/であれ",
        ],
        correctAnswer: 3,
        memo: [
          "にしても/にしても: 'Dù là A hay là B' (ít trang trọng hơn).",
          "なり/なり: 'Hoặc là A hoặc là B' (chỉ sự lựa chọn), không phù hợp.",
          "を問わず: 'Không kể/Bất kể' (dùng thay thế được nhưng であれ/であれ nhấn mạnh tính liệt kê hai trường hợp rõ rệt hơn).",
          "であれ/であれ: 'Dù là A hay là B'. Liệt kê hai khả năng đối lập (trời nắng hay trời mưa) để khẳng định kết quả (cuộc dã ngoại vẫn được tổ chức). (Đúng)",
        ],
      },
    ],
  },
  {
    front: "～どうにも…ない",
    back: [
      "✨ Hoàn toàn không thể (dù cố gắng thế nào cũng không thể, thường đi với V thể khả năng)",
      "・Ví dụ: Tôi hoàn toàn không thể tìm thấy chìa khóa đã đánh mất.",
      "📌 Đi kèm với động từ thể khả năng và phủ định để nhấn mạnh sự hoàn toàn bất lực.",
    ],
    more: [
      "🧩 どうにも + V (thể khả năng) ない",
      "⚖️ どうしても...ない (nhấn mạnh sự bất lực mạnh mẽ hơn)",
      "💬 Văn nói suồng sã, diễn tả sự bất lực cá nhân.",
      "📝 ví dụ",
      "・いくら探しても、なくした鍵はどうにも見つからない",
      "・こんなに病気が重くては、どうにも動けない",
    ],
    questions: [
      {
        id: "9-1",
        content: "この問題は難しすぎて、私一人の力では___理解で___",
        answers: [
          "どうしても/ない",
          "どんなに/ない",
          "いくら/ない",
          "どうにも/ない",
        ],
        correctAnswer: 3,
        memo: [
          "どうしても/ない: 'Tuyệt đối không thể' (thường là bất khả kháng, mạnh hơn どうにも).",
          "どんなに/ない: Các từ này thường đi với Vて + も hoặc Vても (vd: どんなに頑張っても...ない).",
          "いくら/ない: Các từ này thường đi với Vて + も hoặc Vても (vd: いくら頑張っても...ない).",
          "どうにも/ない: 'Hoàn toàn không thể'. Nhấn mạnh sự bất lực hoàn toàn (không thể hiểu được) dù cố gắng/dù khó khăn. (Đúng)",
        ],
      },
      {
        id: "9-2",
        content: "このパソコンは古すぎて、新しいソフトは___使え___",
        answers: [
          "なんとか/ない",
          "とにかく/ない",
          "どうにも/ない",
          "どうにか/ない",
        ],
        correctAnswer: 2,
        memo: [
          "なんとか/ない: Ngữ pháp này sai vì なんとか có nghĩa là 'bằng cách nào đó'.",
          "とにかく/ない: Không có cách diễn đạt này.",
          "どうにも/ない: 'Hoàn toàn không thể'. Máy tính quá cũ nên hoàn toàn không thể sử dụng được phần mềm mới. Nhấn mạnh sự bất lực do điều kiện khách quan. (Đúng)",
          "どうにか/ない: Ngữ pháp này sai vì どうにか có nghĩa là 'bằng cách nào đó'.",
        ],
      },
      {
        id: "9-3",
        content: "状況が複雑すぎて、___解決でき___",
        answers: [
          "どうしても/ない",
          "いくら/ない",
          "どうにも/ない",
          "いかに/ない",
        ],
        correctAnswer: 2,
        memo: [
          "どうしても/ない: 'Tuyệt đối không thể' (thường là bất khả kháng, mạnh hơn どうにも).",
          "いくら/ない: Cần đi kèm với Vて + も (vd: いくら頑張っても).",
          "どうにも/ない: 'Hoàn toàn không thể'. Tình hình quá phức tạp nên hoàn toàn không thể giải quyết được. (Đúng)",
          "いかに/ない: Cần đi kèm với Vて + も (vd: いかに努力しても).",
        ],
      },
    ],
  },
  {
    front: "～はする",
    back: [
      "✨ Có làm/Có xảy ra (Nhấn mạnh hành động hoặc sự thật, thường ngụ ý 'nhưng mà', mang tính nhượng bộ)",
      "・Ví dụ: Món ăn này có ngon, nhưng mà giá hơi đắt.",
      "📌 Đặt は giữa Vます và する để nhấn mạnh sự thật của hành động, nhưng luôn đi kèm với vế sau mang tính đối lập/nhượng bộ.",
    ],
    more: [
      "🧩 Vます + は + する",
      "⚖️ VるにはVる (cũng là 'có... thì có...', nhưng はする nhấn mạnh yếu tố đối lập/hối tiếc sau đó hơn)",
      "💬 Văn nói, dùng để nhượng bộ và đối lập (Có A nhưng B).",
      "📝 ví dụ",
      "・この料理は美味しいはするが、値段が少し高い",
      "・来るとは言ったはするが、まだ確実ではないようだ",
    ],
    questions: [
      {
        id: "10-1",
        content: "彼の説明はわかりやすい___が、具体例が少ない",
        answers: ["ではある", "はする", "にしても", "こそする"],
        correctAnswer: 1,
        memo: [
          "ではある: (Dùng với Na/N) 'Tuy là...', cũng mang nghĩa nhượng bộ/đối lập. Tuy nhiên, わかりやすい là Tính từ-i, không phù hợp.",
          "はする: Nhấn mạnh sự thật rằng 'có dễ hiểu' (わかりやすくはする - tuy có làm cho dễ hiểu), nhưng đi kèm với vế đối lập (thiếu ví dụ cụ thể). (Đúng)",
          "にしても: 'Dù là...' (nhượng bộ), không phù hợp với cấu trúc Vます + は + する.",
          "こそする: Nhấn mạnh hành động (chính là làm), không mang ý nghĩa nhượng bộ/đối lập.",
        ],
      },
      {
        id: "10-2",
        content: "一応謝罪___が、心から反省しているようには見えなかった",
        answers: ["とはいえ", "にしても", "といい", "はするが"],
        correctAnswer: 3,
        memo: [
          "とはいえ: 'Mặc dù nói là...', dùng để mở đầu một mệnh đề đối lập/hạn chế.",
          "にしても: 'Dù là...' (nhượng bộ), không phù hợp với cấu trúc này.",
          "といい: 'Cả... và...' (liệt kê), không phù hợp.",
          "はするが: Nhấn mạnh sự thật rằng 'có xin lỗi' (謝罪はする), nhưng đi kèm với vế đối lập (không có vẻ hối lỗi chân thành). (Đúng)",
        ],
      },
      {
        id: "10-3",
        content: "努力はした___が、残念ながら結果は出なかった",
        answers: ["はする", "こそする", "ではある", "ならする"],
        correctAnswer: 0,
        memo: [
          "はする: Nhấn mạnh sự thật rằng 'có nỗ lực' (努力はする), nhưng đi kèm với vế đối lập (không có kết quả). (Đúng)",
          "こそする: Nhấn mạnh hành động (chính là làm), không mang ý nghĩa nhượng bộ/đối lập.",
          "ではある: (Dùng với Na/N), không phù hợp với động từ 努力する.",
          "ならする: 'Nếu làm', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～ているばあいではない",
    back: [
      "✨ Không phải lúc để.../Không thể... được (Nhấn mạnh tình huống khẩn cấp, không cho phép làm điều đó)",
      "・Ví dụ: Đây không phải là lúc để nghỉ ngơi.",
      "📌 Nhấn mạnh sự không phù hợp của một hành động trong một tình huống nghiêm trọng, cần phải làm việc khác ngay lập tức.",
    ],
    more: [
      "🧩 Vて いる / N + の + ばあいではない",
      "⚖️ ～どころではない (cũng là 'không phải lúc', nhưng ばあいではない nhấn mạnh sự cần thiết phải hành động)",
      "💬 Văn nói và viết, dùng để nhấn mạnh tình huống khẩn cấp, cần hành động.",
      "📝 ví dụ",
      "・休んでいるばあいではない。すぐに出発しなければならない",
      "・こんなに危険な状況で、心配しているばあいではない、早く行動しろ",
    ],
    questions: [
      {
        id: "11-1",
        content: "もう締め切りまで時間がない。のんびりし___",
        answers: [
          "ところではない",
          "わけではない",
          "ばあいではない",
          "どころではない",
        ],
        correctAnswer: 2,
        memo: [
          "ところではない: Không có cách diễn đạt này.",
          "わけではない: 'Không hẳn là...' (phủ định một phần), không phù hợp.",
          "ばあいではない: 'Không phải lúc để...' (nhấn mạnh tình huống khẩn cấp). Đã gần deadline nên 'không phải lúc để thong thả'. (Đúng)",
          "どころではない: 'Hoàn toàn không thể (vì tình huống quá tệ/bận)', cũng có nghĩa tương tự nhưng ばあいではない nhấn mạnh tính cần thiết phải hành động hơn.",
        ],
      },
      {
        id: "11-2",
        content: "試験まであと一週間だ。遊んでいる___",
        answers: [
          "わけではない",
          "どころではない",
          "ことではない",
          "ばあいではない",
        ],
        correctAnswer: 3,
        memo: [
          "わけではない: 'Không hẳn là...' (phủ định một phần), không phù hợp.",
          "どころではない: 'Hoàn toàn không thể (vì tình huống quá tệ/bận)'.",
          "ことではない: 'Không phải là việc...', không phù hợp.",
          "ばあいではない: 'Không phải lúc để...' (nhấn mạnh tình huống khẩn cấp). Còn 1 tuần thi nên 'không phải lúc để chơi'. (Đúng)",
        ],
      },
      {
        id: "11-3",
        content: "災害が発生した。一刻も早く避難しなければ、様子を見___",
        answers: ["どころか", "というわけだ", "ばあいではない", "によって"],
        correctAnswer: 2,
        memo: [
          "どころか: 'Chứ đừng nói là...', không phù hợp.",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
          "ばあいではない: 'Không phải lúc để...' (nhấn mạnh tình huống khẩn cấp). Thảm họa đã xảy ra, không phải lúc để quan sát, phải sơ tán ngay. (Đúng)",
          "によって: 'Tùy theo/Bằng cách...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～なら…なり",
    back: [
      "✨ Nếu là A thì hãy làm tương ứng với A/Trong phạm vi có thể (thể hiện sự chấp nhận điều kiện hiện tại và hành động trong phạm vi đó)",
      "・Ví dụ: Nếu không có tiền thì hãy làm theo cách không có tiền",
      "📌 Hành động B phải là hành động tương xứng hoặc hợp lý với điều kiện A (dù A có thể là tiêu cực/kém lý tưởng).",
    ],
    more: [
      "🧩 N / Vる / Aい + なら + N / Vる / Aい + なりに/なり",
      "⚖️ VるなりVるなり (là 'hoặc là làm V1 hoặc là làm V2', chỉ sự lựa chọn)",
      "💬 Văn nói, dùng để thể hiện sự chấp nhận điều kiện và hành động tương xứng.",
      "📝 ví dụ",
      "・金がないなら、金がないなりのやり方があるはずだ",
      "・気に入らないなら、気に入らないなりにそう言ってくれ",
    ],
    questions: [
      {
        id: "12-1",
        content: "まだ子供___、子供___にできることをやるべきだ",
        answers: ["ならば/なり", "なら/ならば", "なら/なりに", "なり/なりに"],
        correctAnswer: 2,
        memo: [
          "ならば/なり: Sai cấu trúc.",
          "なら/ならば: Sai cấu trúc.",
          "なら/なりに: 'Nếu là... thì hãy làm tương ứng với...'. Nếu là trẻ con thì hãy làm những việc mà trẻ con có thể làm. (N なら N なりに). (Đúng)",
          "なり/なりに: Sai cấu trúc.",
        ],
      },
      {
        id: "12-2",
        content: "わからない___、わからない___に先生に聞くべきだ",
        answers: ["なり/なり", "ならば/ならば", "にしろ/にしろ", "なら/なり"],
        correctAnswer: 3,
        memo: [
          "なり/なり: 'Hoặc là... hoặc là...' (chỉ sự lựa chọn), không phù hợp.",
          "ならば/ならば: Sai cấu trúc.",
          "にしろ/にしろ: 'Dù là A hay là B', không phù hợp.",
          "なら/なり: 'Nếu không hiểu thì hãy hỏi giáo viên theo cách không hiểu' (hãy làm hành động tương xứng với điều kiện). (Aい なら Aい なりに). (Đúng)",
        ],
      },
      {
        id: "12-3",
        content: "困ったときは、先生___友達___に相談するといい",
        answers: ["ならば/なりに", "なり/なり", "にしろ/にしろ", "なら/なり"],
        correctAnswer: 1,
        memo: [
          "ならば/なりに: Sai cấu trúc.",
          "なり/なり: 'Hoặc là... hoặc là...'. Khi gặp khó khăn thì 'hoặc là hỏi thầy giáo hoặc là hỏi bạn bè' (chỉ sự lựa chọn). (Đúng)",
          "にしろ/にしろ: 'Dù là A hay là B', không phù hợp.",
          "なら/なり: Sai cấu trúc.",
        ],
      },
    ],
  },
  {
    front: "～わ...わ（で）",
    back: [
      "✨ Nào là... nào là... (Liệt kê nhiều sự việc, thường là tiêu cực, dẫn đến kết quả tệ hại/khó khăn)",
      "・Ví dụ: Nào là bị cảm, nào là bị mất ví, tôi đã có một ngày thật tồi tệ.",
      "📌 Liệt kê tối thiểu hai sự kiện tiêu cực/khó khăn xảy ra liên tiếp, vế sau là kết quả tất yếu.",
    ],
    more: [
      "🧩 Vる / Aい / N / Na + わ + ...",
      "⚖️ ～だの～だの (cũng là tiêu cực, nhưng わ…わ nhấn mạnh sự chồng chất của nhiều vấn đề)",
      "💬 Văn nói và viết, diễn tả sự chồng chất của nhiều vấn đề, mang tính tiêu cực.",
      "📝 ví dụ",
      "・風邪をひくわ、財布をなくすわ（で）、ひどい一日だった",
      "・義母は病気になるわ、子供は学費を要求するわ（で）、私は大変だ",
    ],
    questions: [
      {
        id: "13-1",
        content:
          "仕事は終わらない___、締め切りは迫る___（で）、ストレスがたまった",
        answers: ["わ/わ", "だの/だの", "にしたところで", "にしろ/にしろ"],
        correctAnswer: 0,
        memo: [
          "わ/わ: 'Nào là... nào là...'. Liệt kê các yếu tố tiêu cực chồng chất (công việc không xong, deadline cận kề) dẫn đến kết quả tệ hại (tích tụ stress). (Đúng)",
          "だの/だの: Thường nhấn mạnh sự phàn nàn/bất mãn hơn là sự chồng chất dẫn đến hậu quả.",
          "にしたところで: 'Ngay cả...', không phù hợp.",
          "にしろ/にしろ: 'Dù là A hay là B' (bao hàm), không phù hợp.",
        ],
      },
      {
        id: "13-2",
        content: "電車は遅れる___、雨は降る___（で）、散々な目にあった",
        answers: ["にしても/にしても", "だの/だの", "わ/わ", "なり/なり"],
        correctAnswer: 2,
        memo: [
          "にしても/にしても: 'Dù là A hay là B' (nhượng bộ/bao hàm), không phù hợp.",
          "だの/だの: Thường nhấn mạnh sự phàn nàn/bất mãn hơn là sự chồng chất dẫn đến hậu quả.",
          "わ/わ: 'Nào là... nào là...'. Liệt kê các yếu tố tiêu cực chồng chất (tàu chậm, trời mưa) dẫn đến kết quả tệ hại (gặp phải chuyện tồi tệ). (Đúng)",
          "なり/なり: 'Hoặc là... hoặc là...', không phù hợp.",
        ],
      },
      {
        id: "13-3",
        content: "渋滞がひどい___、道に迷う___で、約束の時間に遅れてしまった",
        answers: ["やら/やら", "だの/だの", "にしろ/にしろ", "わ/わ"],
        correctAnswer: 3,
        memo: [
          "やら/やら: Cũng là liệt kê, nhưng không mang sắc thái tiêu cực/hậu quả mạnh mẽ như わ/わ.",
          "だの/だの: Thường nhấn mạnh sự phàn nàn/bất mãn hơn là sự chồng chất dẫn đến hậu quả.",
          "にしろ/にしろ: 'Dù là A hay là B' (bao hàm), không phù hợp.",
          "わ/わ: 'Nào là... nào là...'. Liệt kê các yếu tố tiêu cực chồng chất (tắc đường, lạc đường) dẫn đến kết quả tệ hại (bị trễ hẹn). (Đúng)",
        ],
      },
    ],
  },
  {
    front: "～をいいことに",
    back: [
      "✨ Lợi dụng... (Lợi dụng một điều kiện/sự vắng mặt để làm điều không tốt)",
      "・Ví dụ: Cô ấy lợi dụng việc thầy giáo không có ở đây để lười biếng",
      "📌 Lợi dụng một trạng thái thuận lợi (thường là tiêu cực hoặc sự vắng mặt) để thực hiện một hành vi tiêu cực/ích kỷ.",
    ],
    more: [
      "🧩 Vる / Vた / Aい / Na / N + の/こと + をいいことに",
      "⚖️ ～につけこんで (ám chỉ việc lợi dụng điểm yếu/sơ hở)",
      "💬 Văn nói, mang tính tiêu cực, dùng để chỉ trích hành vi lợi dụng.",
      "📝 ví dụ",
      "・先生がいないのをいいことに、彼女は怠けている",
      "・皆が親切にしてくれるのをいいことに、彼はわがままなことをする",
    ],
    questions: [
      {
        id: "14-1",
        content: "テストが中止になった___、彼は一切勉強しなくなった",
        answers: ["につれて", "のをいいことに", "をめぐって", "の限り"],
        correctAnswer: 1,
        memo: [
          "につれて: 'Cùng với sự thay đổi của...', không phù hợp.",
          "のをいいことに: 'Lợi dụng...'. Lợi dụng việc thi bị hủy (là điều kiện thuận lợi) để làm điều không tốt (không học nữa). (Đúng)",
          "をめぐって: 'Xoay quanh/Về vấn đề...', không phù hợp.",
          "の限り: 'Hết mức có thể', không phù hợp.",
        ],
      },
      {
        id: "14-2",
        content: "部長が長期出張中___、部下たちは好き勝手なことをしている",
        answers: ["につけ", "にしても", "のをいいことに", "にあっては"],
        correctAnswer: 2,
        memo: [
          "につけ: 'Mỗi khi/hễ cứ', không phù hợp.",
          "にしても: 'Dù là...', không phù hợp.",
          "のをいいことに: 'Lợi dụng...'. Lợi dụng sự vắng mặt của cấp trên (là điều kiện thuận lợi) để làm điều không tốt (làm theo ý mình). (Đúng)",
          "にあっては: 'Trong hoàn cảnh...', không phù hợp.",
        ],
      },
      {
        id: "14-3",
        content: "親が病気で家にいるという___、彼はさっそくお金をせびりに来た",
        answers: ["のをいいことに", "を限りに", "にしろ", "につけこんで"],
        correctAnswer: 3,
        memo: [
          "のをいいことに: 'Lợi dụng (điều kiện thuận lợi)', không nhấn mạnh yếu tố 'điểm yếu' mạnh như につけこんで.",
          "を限りに: 'Cho đến hết', không phù hợp.",
          "にしろ: 'Dù là...', không phù hợp.",
          "につけこんで: 'Lợi dụng (điểm yếu/sơ hở)'. Lợi dụng việc cha mẹ bị ốm (là điểm yếu/sơ hở) để xin tiền. (Đúng)",
        ],
      },
    ],
  },
  {
    front: "～いざ～となると／～となれば／～となったら",
    back: [
      "✨ Cứ hễ đến lúc/Khi cần thiết (sẽ có sự thay đổi đột ngột về thái độ, hành động, hoặc sự thật được làm rõ)",
      "・Ví dụ: Mặc dù nói là biết, nhưng cứ hễ đến lúc làm thì lại hoàn toàn không thể",
      "📌 Diễn tả sự thay đổi đột ngột hoặc tiết lộ sự thật khi điều kiện đặc biệt/thời điểm quyết định đến.",
    ],
    more: [
      "🧩 いざ + N / Vる + となると/となれば/となったら",
      "⚖️ となると (trang trọng hơn), となれば (nhấn mạnh điều kiện), となったら (thông thường hơn)",
      "💬 Văn nói và viết, dùng để nhấn mạnh sự thay đổi khi đến thời điểm quyết định.",
      "📝 ví dụ",
      "・知っていると言ったが、いざやるとなると、全然できない",
      "・いざお金がとなれば、彼は態度を変えて優しくなる",
    ],
    questions: [
      {
        id: "15-1",
        content: "いつも口では偉そうだが、___ 実行 ___、彼は何もできない",
        answers: [
          "いざ/になったら",
          "まさか/となると",
          "いざ/となると",
          "いざ/にしても",
        ],
        correctAnswer: 2,
        memo: [
          "いざ/になったら: Không phù hợp cấu trúc (いざ đi với Vる).",
          "まさか/となると: 'Không ngờ...', không phù hợp.",
          "いざ/となると: 'Cứ hễ đến lúc/khi cần thiết... thì...'. Luôn nói mạnh miệng nhưng cứ hễ đến lúc thực hành thì lại không làm được. (Đúng)",
          "いざ/にしても: 'Dù là...', không phù hợp.",
        ],
      },
      {
        id: "15-2",
        content: "旅行に行く___、準備に時間と手間がかかる",
        answers: [
          "まさか/となると",
          "いざ/になれば",
          "たとえ/となれば",
          "いざ/となれば",
        ],
        correctAnswer: 3,
        memo: [
          "まさか/となると: 'Không ngờ...', không phù hợp.",
          "いざ/になれば: Không phù hợp cấu trúc (いざ Vる となれば).",
          "たとえ/となれば: 'Cho dù/Dù là...', không phù hợp.",
          "いざ/となれば: 'Cứ hễ đến lúc/khi cần thiết... thì...'. Cứ hễ đến lúc đi du lịch thì việc chuẩn bị lại tốn thời gian. (Đúng)",
        ],
      },
      {
        id: "15-3",
        content: "普段はおとなしいが、___トラブル___、彼は頼りになる",
        answers: [
          "いざ/となると",
          "いざ/となっては",
          "まさか/となったら",
          "いざ/になったら",
        ],
        correctAnswer: 0,
        memo: [
          "いざ/となると: 'Cứ hễ đến lúc/khi cần thiết... thì...'. Bình thường hiền lành nhưng cứ hễ xảy ra rắc rối thì lại đáng tin cậy. (Đúng)",
          "いざ/となっては: Có ý nghĩa tương tự, nhưng となると/となったら/となれば phổ biến hơn.",
          "まさか/となったら: 'Không ngờ...', không phù hợp.",
          "いざ/になったら: Không phù hợp cấu trúc (いざ N となると/となれば).",
        ],
      },
    ],
  },
  {
    front: "～との",
    back: [
      "✨ Rằng/Nghe nói là (Chỉ nguồn tin, thông báo; dùng trong văn viết, phát thanh, báo chí)",
      "・Ví dụ: Có thông báo rằng cuộc họp đã bị hoãn lại",
      "📌 Chỉ dùng để trích dẫn hoặc thông báo nguồn tin chính thức/công cộng và mang tính trang trọng.",
    ],
    more: [
      "🧩 V / Aい / Na / N + との + N (danh từ chỉ thông tin: 連絡, ニュース...)",
      "⚖️ ～という (cũng là 'rằng', nhưng との trang trọng hơn và bắt buộc phải đi kèm với một danh từ chỉ thông tin)",
      "💬 Văn viết, trang trọng, dùng trong thông báo chính thức, báo chí.",
      "📝 ví dụ",
      "・会議は中止されたとの連絡があった",
      "・社長が辞任するとのニュースを聞いた",
    ],
    questions: [
      {
        id: "16-1",
        content: "来月新製品が発売される___公式発表があった",
        answers: ["と", "という", "というわけだ", "との"],
        correctAnswer: 3,
        memo: [
          "と: Thường đi với V/N nói/nghĩ, ít dùng trong thông báo chính thức.",
          "という: Cũng là trích dẫn, nhưng との trang trọng hơn trong văn bản chính thức.",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
          "との: 'Rằng/Nghe nói là'. Kết hợp với danh từ chỉ thông báo (公式発表) để trích dẫn nội dung thông báo một cách trang trọng. (Vる + との + N). (Đúng)",
        ],
      },
      {
        id: "16-2",
        content: "明日は台風が接近する___予報だ",
        answers: ["としての", "という", "との", "とのこと"],
        correctAnswer: 2,
        memo: [
          "としての: 'Với tư cách là...', không phù hợp.",
          "という: Cũng là trích dẫn, nhưng との trang trọng hơn trong văn bản chính thức.",
          "との: 'Rằng/Nghe nói là'. Kết hợp với danh từ chỉ thông tin (予報 - dự báo) để trích dẫn nội dung dự báo một cách trang trọng. (Vる + との + N). (Đúng)",
          "とのこと: 'Nghe nói là...' (kết thúc câu), không đi kèm trực tiếp với danh từ 予報.",
        ],
      },
      {
        id: "16-3",
        content: "犯人は逃走中だ___情報が入った",
        answers: ["との", "と", "というわけだ", "という"],
        correctAnswer: 0,
        memo: [
          "との: 'Rằng/Nghe nói là'. Kết hợp với danh từ chỉ thông tin (情報 - thông tin) để trích dẫn nội dung một cách trang trọng. (N だ + との + N). (Đúng)",
          "と: Thường đi với V/N nói/nghĩ, ít trang trọng.",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
          "という: Cũng là trích dẫn, nhưng との trang trọng hơn trong văn bản chính thức.",
        ],
      },
    ],
  },
  {
    front: "～てもしかたがない",
    back: [
      "✨ Có làm... cũng vô ích/Không thể tránh khỏi (Thể hiện sự chấp nhận điều không mong muốn)",
      "・Ví dụ: Dù có hối hận về những gì đã xảy ra thì cũng vô ích",
      "📌 Diễn tả sự vô ích của một hành động, thường là hành động mang tính cảm xúc đối với một sự thật không thể thay đổi",
    ],
    more: [
      "🧩 Vて + もしかたがない/しょうがない/どうしようもない",
      "⚖️ ～てもはじまらない (cũng là 'vô ích', trang trọng hơn)",
      "💬 Văn nói suồng sã, dùng để chấp nhận/biện minh cho sự vô ích.",
      "📝 ví dụ",
      "・起きてしまったことを後悔してもしかたがない",
      "・終わったことを泣いてもしかたがない",
    ],
    questions: [
      {
        id: "17-1",
        content: "今さら、あの時の判断を悔やん___",
        answers: [
          "てもいい",
          "てもしかたがない",
          "ても構わない",
          "てもいいはずだ",
        ],
        correctAnswer: 1,
        memo: [
          "てもいい: 'Có thể làm... cũng được', không phù hợp với ngữ cảnh tiếc nuối/vô ích.",
          "てもしかたがない: 'Có làm... cũng vô ích'. Hối hận về quyết định lúc đó bây giờ cũng vô ích vì không thể thay đổi được. (Đúng)",
          "ても構わない: 'Có thể làm... cũng được', không phù hợp với ngữ cảnh tiếc nuối/vô ích.",
          "てもいいはずだ: 'Lẽ ra có thể làm...', không phù hợp.",
        ],
      },
      {
        id: "17-2",
        content: "過ぎ去った時間を嘆い___、未来は変わらない",
        answers: [
          "てもいい",
          "てもいいはずだ",
          "てもかまわない",
          "てもしかたがない",
        ],
        correctAnswer: 3,
        memo: [
          "てもいい: 'Có thể làm... cũng được', không phù hợp.",
          "てもいいはずだ: 'Lẽ ra có thể làm...', không phù hợp.",
          "てもかまわない: 'Có thể làm... cũng được', không phù hợp.",
          "てもしかたがない: (Có thể lược bỏ vế sau). 'Than thở về thời gian đã qua thì tương lai cũng không thay đổi' (than thở là vô ích). (Đúng)",
        ],
      },
      {
        id: "17-3",
        content: "自分の不注意で失敗したのだから、誰かのせいにし___",
        answers: [
          "てもいい",
          "てもしかたがない",
          "てもかまわない",
          "てもいいはずだ",
        ],
        correctAnswer: 1,
        memo: [
          "てもいい: 'Có thể làm... cũng được' (mặc dù đổ lỗi là hành động tiêu cực, câu này mang tính phê phán).",
          "てもしかたがない: 'Có làm... cũng vô ích/không thể'. Vì là lỗi của bản thân nên đổ lỗi cho người khác cũng vô ích/không thể được. (Đúng)",
          "てもかまわない: 'Có thể làm... cũng được' (mặc dù đổ lỗi là hành động tiêu cực, câu này mang tính phê phán).",
          "てもいいはずだ: 'Lẽ ra có thể làm...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～Vずにはおかない",
    back: [
      "✨ Nhất định sẽ.../Không thể không... (Diễn tả ý chí mạnh mẽ của người nói rằng hành động B nhất định sẽ xảy ra/ảnh hưởng đến người khác)",
      "・Ví dụ: Tác phẩm này nhất định sẽ gây ấn tượng mạnh mẽ cho người xem",
      "📌 Thể hiện sự chắc chắn rằng hành động sẽ gây ra một ảnh hưởng mạnh mẽ lên người/vật khác. Chỉ dùng cho ngôi thứ ba.",
    ],
    more: [
      "🧩 Vない + ずにはおかない (bỏ ない)",
      "⚖️ ～ずにはいられない (là 'không thể không/không kìm được', dùng cho cảm xúc của chính người nói)",
      "💬 Văn viết, trang trọng.",
      "📝 ví dụ",
      "・この作品は見る人に感動を与えずにはおかないだろう",
      "・彼の言葉は、彼女の心を傷つけずにはおかないだろう",
    ],
    questions: [
      {
        id: "18-1",
        content: "彼のカリスマ性は、聴衆の心をつかま___だろう",
        answers: [
          "ずにはおかない",
          "ずにはいられない",
          "ざるをえない",
          "ないわけにはいかない",
        ],
        correctAnswer: 0,
        memo: [
          "ずにはおかない: 'Nhất định sẽ...'. Diễn tả sự chắc chắn rằng Karisma của anh ấy nhất định sẽ gây ảnh hưởng mạnh mẽ đến khán giả (ngôi thứ ba). (Đúng)",
          "ずにはいられない: 'Không thể kìm được' (chỉ cảm xúc của chính người nói), không dùng cho sự ảnh hưởng đến người khác.",
          "ざるをえない: 'Buộc phải làm...', không phù hợp.",
          "ないわけにはいかない: 'Không thể không làm...', không phù hợp.",
        ],
      },
      {
        id: "18-2",
        content: "その衝撃的なニュースは、世論を騒がせ___だろう",
        answers: [
          "ずにはいられない",
          "ざるをえない",
          "ないわけにはいかない",
          "ずにはおかない",
        ],
        correctAnswer: 3,
        memo: [
          "ずにはいられない: 'Không thể kìm được' (chỉ cảm xúc của người nói), không phù hợp.",
          "ざるをえない: 'Buộc phải làm...', không phù hợp.",
          "ないわけにはいかない: 'Không thể không làm...', không phù hợp.",
          "ずにはおかない: 'Nhất định sẽ...'. Diễn tả sự chắc chắn rằng tin tức chấn động nhất định sẽ gây ảnh hưởng mạnh mẽ đến dư luận (ngôi thứ ba). (Đúng)",
        ],
      },
      {
        id: "18-3",
        content: "この悲惨な事件は、人々の心に深い影を落とさ___",
        answers: [
          "ずにいる",
          "ざるをえない",
          "ずにはおかない",
          "ないわけにはいかない",
        ],
        correctAnswer: 2,
        memo: [
          "ずにいる: 'Không làm V mà vẫn...', không phù hợp.",
          "ざるをえない: 'Buộc phải làm...', không phù hợp.",
          "ずにはおかない: 'Nhất định sẽ...'. Diễn tả sự chắc chắn rằng sự việc bi thảm này nhất định sẽ gây ảnh hưởng mạnh mẽ (bóng đen) lên tâm hồn mọi người (ngôi thứ ba). (Đúng)",
          "ないわけにはいかない: 'Không thể không làm...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～たらどんなに…か",
    back: [
      "✨ Nếu... thì sẽ... biết bao/Ước gì (Thể hiện cảm xúc mạnh mẽ, mong muốn điều gì xảy ra, thường là điều khó xảy ra)",
      "・Ví dụ: Nếu tôi có thể hiểu được cảm xúc của người đó thì tốt biết mấy",
      "📌 Diễn tả cảm xúc tột độ đối với một giả định không có thực hoặc khó xảy ra",
    ],
    more: [
      "🧩 Vたら / Nなら + どんなに + Vる/Aい + か/だろうか",
      "⚖️ ～ばいいのに (chỉ là ước muốn nhẹ nhàng hơn)",
      "💬 Văn nói, dùng để bày tỏ cảm xúc, ước muốn mạnh mẽ.",
      "📝 ví dụ",
      "・あの人の気持ちがわかったらどんなにいいか",
      "・昔の親友に再会できたらどんなにうれしいか",
    ],
    questions: [
      {
        id: "19-1",
        content: "もう一度、学生時代に戻れ___楽しいか",
        answers: ["たとしても", "たらどんなに", "たらいいのに", "たところで"],
        correctAnswer: 1,
        memo: [
          "たとしても: 'Cho dù...', không phù hợp.",
          "たらどんなに: 'Nếu... thì sẽ... biết bao'. Thể hiện ước muốn mạnh mẽ về một điều khó xảy ra (quay lại thời học sinh) và cảm xúc tột độ (vui vẻ biết bao). (Đúng)",
          "たらいいのに: 'Ước gì...' (mong muốn nhẹ nhàng hơn).",
          "たところで: 'Dù có làm... cũng vô ích', không phù hợp.",
        ],
      },
      {
        id: "19-2",
        content: "もし、時間旅行ができ___素晴らしいか",
        answers: [
          "たところで",
          "たとしても",
          "てからでなければ",
          "たらどんなに",
        ],
        correctAnswer: 3,
        memo: [
          "たところで: 'Dù có làm... cũng vô ích', không phù hợp.",
          "たとしても: 'Cho dù...', không phù hợp.",
          "てからでなければ: 'Nếu không làm A thì không làm B', không phù hợp.",
          "たらどんなに: 'Nếu... thì sẽ... biết bao'. Thể hiện ước muốn mạnh mẽ về một điều khó xảy ra (du hành thời gian) và cảm xúc tột độ (tuyệt vời biết bao). (Đúng)",
        ],
      },
      {
        id: "19-3",
        content: "宝くじに当たっ___幸せだろうか",
        answers: ["てもいい", "たとしたら", "たらどんなに", "てもしかたがない"],
        correctAnswer: 2,
        memo: [
          "てもいい: 'Có thể làm... cũng được', không phù hợp.",
          "たとしたら: 'Nếu là...', chỉ đặt ra giả định, không nhấn mạnh cảm xúc tột độ.",
          "たらどんなに: 'Nếu... thì sẽ... biết bao'. Thể hiện ước muốn mạnh mẽ về một giả định (trúng số) và cảm xúc tột độ (hạnh phúc biết bao). (Đúng)",
          "てもしかたがない: 'Có làm... cũng vô ích', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～ぬまに",
    back: [
      "✨ Trong khi.../Trong lúc... (Trong lúc chưa xảy ra/chưa nhận thấy A thì làm nhanh B)",
      "・Ví dụ: Trong lúc mẹ không để ý, thằng bé đã ăn vụng chiếc bánh ngọt",
      "📌 Thể hiện hành động B được thực hiện ngay lập tức hoặc thầm lặng trong trạng thái không rõ ràng/chưa nhận thấy của A.",
    ],
    more: [
      "🧩 Vない + ぬまに (chỉ dùng với một số động từ cố định)",
      "⚖️ ～ないうちに (cũng là 'trong khi chưa...', nhưng ぬまに trang trọng hơn và nhấn mạnh yếu tố bí mật/không nhận thấy)",
      "💬 Văn viết, trang trọng.",
      "📝 ví dụ",
      "・母親が目を離すぬまに、子供はお菓子をこっそり食べた",
      "・若く、経験がないぬまに、もっと多くのことにチャレンジするべきだ",
    ],
    questions: [
      {
        id: "20-1",
        content: "知らない___、季節はすっかり春になっていた",
        answers: ["うちに", "ところだ", "あいだに", "ぬまに"],
        correctAnswer: 3,
        memo: [
          "うちに: 'Trong khi...' (khi trạng thái A còn đang tiếp diễn), không nhấn mạnh yếu tố 'bí mật/chưa nhận thấy' mạnh bằng ぬまに.",
          "ところだ: 'Đúng lúc...', không phù hợp.",
          "あいだに: 'Trong suốt khoảng thời gian...', không phù hợp.",
          "ぬまに: 'Trong khi chưa nhận ra'. Thể hiện sự thay đổi trạng thái xảy ra một cách thầm lặng, không rõ ràng (chưa kịp nhận ra thì mùa đã sang xuân). (Đúng)",
        ],
      },
      {
        id: "20-2",
        content: "周りの人が気づか___、彼はこっそり席を立った",
        answers: ["うちに", "あいだに", "うちに/ぬまに", "ぬまに"],
        correctAnswer: 3,
        memo: [
          "うちに: 'Trong khi...' (khi trạng thái A còn đang tiếp diễn).",
          "あいだに: 'Trong suốt khoảng thời gian...', không phù hợp.",
          "うちに/ぬまに: Cấu trúc gộp hai ngữ pháp, không phù hợp cho lựa chọn duy nhất.",
          "ぬまに: 'Trong khi chưa nhận ra/chưa nhận thấy'. Hành động 'bí mật đứng dậy' được thực hiện trong trạng thái người khác chưa kịp nhận thấy. (Đúng)",
        ],
      },
      {
        id: "20-3",
        content: "誰も気づか___、会議が終わってしまった",
        answers: ["うちに", "ところだ", "あいだに", "ぬまに"],
        correctAnswer: 3,
        memo: [
          "うちに: 'Trong khi...' (khi trạng thái A còn đang tiếp diễn).",
          "ところだ: 'Đúng lúc...', không phù hợp.",
          "あいだに: 'Trong suốt khoảng thời gian...', không phù hợp.",
          "ぬまに: 'Trong khi chưa nhận ra'. Thể hiện sự kết thúc xảy ra một cách thầm lặng, không rõ ràng (chưa kịp nhận ra thì cuộc họp đã kết thúc). (Đúng)",
        ],
      },
    ],
  },
  {
    front: "～からとおもって",
    back: [
      "✨ Vì nghĩ rằng... (Là lý do cho một hành động nào đó, thường là tiêu cực hoặc có kết quả không tốt)",
      "・Ví dụ: Vì nghĩ rằng còn nhiều thời gian, nên tôi đã lơ là việc chuẩn bị",
      "📌 Biểu thị lý do mang tính suy đoán chủ quan của người nói, dẫn đến hành động thiếu cẩn trọng và thường có kết quả không mong muốn/tiêu cực.",
    ],
    more: [
      "🧩 V / Aい / Na / N + だ + からとおもって",
      "⚖️ ～ので (chỉ lý do khách quan, còn からとおもって nhấn mạnh suy nghĩ chủ quan dẫn đến sai lầm)",
      "💬 Văn nói, dùng để biện minh cho hành động thiếu cẩn trọng.",
      "📝 ví dụ",
      "・まだ時間があるからとおもって、準備を怠ってしまった",
      "・ちょっとしたミスだからとおもって報告しなかったら、大きな問題になった",
    ],
    questions: [
      {
        id: "21-1",
        content:
          "少しぐらい遅れても大丈夫だ___、急がなかったら、電車に乗り遅れた",
        answers: ["からこそ", "からとおもって", "のおかげで", "によって"],
        correctAnswer: 1,
        memo: [
          "からこそ: 'Chính vì...', nhấn mạnh lý do tích cực, không phù hợp.",
          "からとおもって: 'Vì nghĩ rằng...'. Vì suy đoán chủ quan mà dẫn đến hành động sai lầm (không vội) và kết quả tiêu cực (trễ tàu). (Đúng)",
          "のおかげで: 'Nhờ có...' (thường là tích cực), không phù hợp.",
          "によって: 'Tùy theo/Bằng cách...', không phù hợp.",
        ],
      },
      {
        id: "21-2",
        content: "自分には関係ない___、黙っていたら、事態は悪化した",
        answers: ["からこそ", "とばかりに", "からといって", "からとおもって"],
        correctAnswer: 3,
        memo: [
          "からこそ: 'Chính vì...', không phù hợp.",
          "とばかりに: 'Cứ như là...', không phù hợp.",
          "からといって: 'Cho dù nói là...', không phù hợp.",
          "からとおもって: 'Vì nghĩ rằng...'. Vì suy đoán chủ quan (nghĩ rằng không liên quan đến mình) mà dẫn đến hành động sai lầm (im lặng) và kết quả tiêu cực (tình hình xấu đi). (Đúng)",
        ],
      },
      {
        id: "21-3",
        content: "安い___、たくさん買ってしまったが、結局使わなかった",
        answers: ["とあって", "のおかげで", "によって", "からとおもって"],
        correctAnswer: 3,
        memo: [
          "とあって: 'Vì là... (hoàn cảnh đặc biệt)', không phù hợp.",
          "のおかげで: 'Nhờ có...', không phù hợp.",
          "によって: 'Tùy theo/Bằng cách...', không phù hợp.",
          "からとおもって: 'Vì nghĩ rằng...'. Vì suy đoán chủ quan (nghĩ rằng rẻ) mà dẫn đến hành động sai lầm (mua nhiều) và kết quả tiêu cực (cuối cùng không dùng). (Đúng)",
        ],
      },
    ],
  },
  {
    front: "～かとおもえば...も",
    back: [
      "✨ Vừa mới... đã lại.../Vừa A xong thì ngay lập tức B (Thể hiện sự thay đổi liên tục, nhanh chóng, thường là sự đối lập)",
      "・Ví dụ: Đứa bé vừa mới khóc xong thì đã lập tức cười",
      "📌 Diễn tả sự thay đổi trạng thái hoặc hành động nhanh chóng, bất ngờ, thường là sự đối lập hoặc luân phiên.",
    ],
    more: [
      "🧩 Vた + かと思えば / かと思ったら",
      "⚖️ ～とたんに (chỉ sự thay đổi tức thì, nhưng かと思えば nhấn mạnh sự đối lập và luân phiên)",
      "💬 Văn nói, diễn tả sự thay đổi nhanh chóng, luân phiên.",
      "📝 ví dụ",
      "・あの赤ちゃんは泣いたかとおもえば、すぐ笑い出す",
      "・さっきまで晴れていたかとおもえば、急に雨が降り出した",
    ],
    questions: [
      {
        id: "22-1",
        content: "部長は怒鳴った___、次の瞬間には穏やかに話していた",
        answers: ["とたんに", "かとおもえば", "が早いか", "やいなや"],
        correctAnswer: 1,
        memo: [
          "とたんに: 'Ngay sau khi', dùng cho hành động B xảy ra tức thì sau A (ít nhấn mạnh sự đối lập).",
          "かとおもえば: 'Vừa mới... đã lại...'. Diễn tả sự thay đổi trạng thái đối lập (từ la hét sang ôn tồn) một cách nhanh chóng, bất ngờ. (Đúng)",
          "が早いか: 'Ngay sau khi', nhấn mạnh hành động bản năng, lặp lại.",
          "やいなや: 'Ngay sau khi', trang trọng, dùng cho hành động bất ngờ, mang tính khách quan.",
        ],
      },
      {
        id: "22-2",
        content: "昨日まで暖かかった___、今日は急に寒くなった",
        answers: ["やいなや", "とたんに", "なり", "かとおもえば"],
        correctAnswer: 3,
        memo: [
          "やいなや: Thường dùng cho hành động của người/vật xảy ra tức thì.",
          "とたんに: Thường dùng cho hành động của người/vật xảy ra tức thì.",
          "なり: Thường dùng cho hành động bất ngờ của cá nhân.",
          "かとおもえば: 'Vừa mới... đã lại...'. Diễn tả sự thay đổi trạng thái đối lập của thời tiết (từ ấm áp sang lạnh đột ngột) một cách nhanh chóng. (Đúng)",
        ],
      },
      {
        id: "22-3",
        content: "先生が教室に入ってきた___、すぐにまた出て行った",
        answers: ["やいなや", "とたんに", "なり", "かとおもえば"],
        correctAnswer: 3,
        memo: [
          "やいなや: 'Ngay sau khi', nhấn mạnh hành động tức thì (ít nhấn mạnh sự luân phiên).",
          "とたんに: 'Ngay sau khi', nhấn mạnh hành động tức thì (ít nhấn mạnh sự luân phiên).",
          "なり: 'Ngay sau khi', hành động B thường là bất ngờ, ngoài ý muốn.",
          "かとおもえば: 'Vừa mới... đã lại...'. Diễn tả sự luân phiên/thay đổi trạng thái nhanh chóng (vừa vào đã ra). (Đúng)",
        ],
      },
    ],
  },
  {
    front: "～といっても間違いない",
    back: [
      "✨ Nói là... thì không sai (Nhấn mạnh sự thật/mức độ gần như tuyệt đối, mang tính khẳng định)",
      "・Ví dụ: Cô ấy là người thành công nhất trong công ty, nói là 'thiên tài' thì không sai",
      "📌 Khẳng định một sự thật/đặc điểm là hoàn toàn chính xác, không cần phải nghi ngờ. Dùng để phóng đại sự thật",
    ],
    more: [
      "🧩 V / Aい / Na / N + といっても間違いない",
      "⚖️ ～といっても過言ではない (cũng là 'nói là... không quá lời', mạnh tương đương)",
      "💬 Văn nói và viết, dùng để khẳng định mạnh mẽ, phóng đại sự thật.",
      "📝 ví dụ",
      "・彼女は社内で最も成功した人だ。天才といっても間違いない",
      "・この車は最後の限定モデルであり、傑作といっても間違いない",
    ],
    questions: [
      {
        id: "23-1",
        content: "彼はチームの心臓だ。リーダー___",
        answers: [
          "というわけだ",
          "といっても間違いない",
          "にすぎない",
          "であれ",
        ],
        correctAnswer: 1,
        memo: [
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
          "といっても間違いない: 'Nói là... thì không sai'. Khẳng định mạnh mẽ rằng anh ấy chính là người dẫn đầu (Leader), không cần nghi ngờ. (Đúng)",
          "にすぎない: 'Chỉ là...', không phù hợp.",
          "であれ: 'Dù là...', không phù hợp.",
        ],
      },
      {
        id: "23-2",
        content: "この技術は、世界を変える発明___",
        answers: [
          "といっても過言ではない",
          "ということだ",
          "にしては",
          "にかぎりだ",
        ],
        correctAnswer: 0,
        memo: [
          "といっても過言ではない: 'Nói là... thì không quá lời'. Khẳng định mạnh mẽ về mức độ lớn lao của phát minh này. (Đúng)",
          "ということだ: 'Có nghĩa là...', không phù hợp.",
          "にしては: 'Mặc dù...', không phù hợp.",
          "にかぎりだ: 'Vô cùng...', không phù hợp.",
        ],
      },
      {
        id: "23-3",
        content: "彼の努力は想像を絶するもので、努力の化身___",
        answers: [
          "にすぎない",
          "にほかならない",
          "といっても間違いない",
          "といっても過言ではない",
        ],
        correctAnswer: 1,
        memo: [
          "にすぎない: 'Chỉ là...', không phù hợp.",
          "にほかならない: 'Chính là/Không gì khác là...'. Khẳng định mạnh mẽ rằng anh ấy chính là hiện thân của sự nỗ lực. (Đúng)",
          "といっても間違いない: 'Nói là... thì không sai', cũng đúng nhưng にほかならない nhấn mạnh sự thật hiển nhiên hơn.",
          "といっても過言ではない: 'Nói là... thì không quá lời', cũng đúng nhưng にほかならない nhấn mạnh sự thật hiển nhiên hơn.",
        ],
      },
    ],
  },
  {
    front: "～にいわせれば",
    back: [
      "✨ Theo ý kiến của.../Nếu để... nói (Trích dẫn quan điểm của một người/nhóm người nào đó)",
      "・Ví dụ: Theo ý kiến của các chuyên gia thì biện pháp này là chưa đủ",
      "📌 Trích dẫn ý kiến mang tính chủ quan hoặc đánh giá của một người/nhóm người. Thường dùng cho các chủ thể có thẩm quyền.",
    ],
    more: [
      "🧩 N + にいわせれば",
      "⚖️ ～によると (chỉ nguồn thông tin khách quan, còn にいわせれば nhấn mạnh ý kiến/quan điểm cá nhân)",
      "💬 Văn nói và viết.",
      "📝 ví dụ",
      "・専門家にいわせれば、この対策はまだ十分ではないそうだ",
      "・彼にいわせれば、できないことは何もないらしい",
    ],
    questions: [
      {
        id: "24-1",
        content: "ベテランの職人___、この作品にはまだ改善の余地があるそうだ",
        answers: ["によれば", "によると", "にいわせれば", "にとっては"],
        correctAnswer: 2,
        memo: [
          "によれば: 'Theo...' (trích dẫn nguồn thông tin khách quan/công cộng), ít nhấn mạnh quan điểm cá nhân/đánh giá chủ quan.",
          "によると: 'Theo...' (trích dẫn nguồn thông tin khách quan/công cộng), ít nhấn mạnh quan điểm cá nhân/đánh giá chủ quan.",
          "にいわせれば: 'Theo ý kiến của...'. Trích dẫn quan điểm/đánh giá chủ quan của người có chuyên môn (ベテランの職人) về chất lượng tác phẩm. (Đúng)",
          "にとっては: 'Đối với...', không phù hợp.",
        ],
      },
      {
        id: "24-2",
        content: "私___、その方法は非効率的だ",
        answers: ["にとって", "にしてみれば", "によれば", "にいわせれば"],
        correctAnswer: 3,
        memo: [
          "にとって: 'Đối với tôi...' (chỉ sự ảnh hưởng/quan trọng), không nhấn mạnh ý kiến/đánh giá.",
          "にしてみれば: 'Nếu xét theo quan điểm của...', cũng tương tự nhưng にいわせれば nhấn mạnh việc 'nếu để người đó nói ra'.",
          "によれば: 'Theo...' (nguồn thông tin khách quan), không phù hợp khi nói về bản thân.",
          "にいわせれば: 'Theo ý kiến của tôi...'. Trích dẫn quan điểm/đánh giá chủ quan của chính người nói. (Đúng)",
        ],
      },
      {
        id: "24-3",
        content: "流行に敏感な若者___、このファッションはもう古いそうだ",
        answers: ["によれば", "にいわせれば", "によると", "にとっては"],
        correctAnswer: 1,
        memo: [
          "によれば: 'Theo...' (nguồn thông tin khách quan), không nhấn mạnh ý kiến/đánh giá chủ quan.",
          "にいわせれば: 'Theo ý kiến của...'. Trích dẫn quan điểm/đánh giá chủ quan của một nhóm người (giới trẻ nhạy cảm với thời trang) về sự lỗi thời của một thứ gì đó. (Đúng)",
          "によると: 'Theo...' (nguồn thông tin khách quan), không nhấn mạnh ý kiến/đánh giá chủ quan.",
          "にとっては: 'Đối với...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～でなくてなんだろう",
    back: [
      "✨ Không phải... thì là gì/Chính là... (Cách nói nhấn mạnh, khẳng định chắc chắn điều gì đó, thường là những danh từ trừu tượng)",
      "・Ví dụ: Sự cống hiến quên mình vì gia đình đó, không phải là tình yêu thì là gì?",
      "📌 Dùng để khẳng định một cách mạnh mẽ rằng sự vật/sự việc là N, không còn cách giải thích nào khác.",
    ],
    more: [
      "🧩 N + でなくてなんだろう",
      "⚖️ ～にほかならない (cũng là 'chính là', nhưng でなくてなんだろう mang tính cảm thán, nhấn mạnh ý kiến cảm xúc của người nói hơn).",
      "💬 Văn viết, trang trọng, mang tính hùng biện, cảm thán mạnh mẽ.",
      "📝 ví dụ",
      "・家族のために尽くすその姿は、愛でなくてなんだろう",
      "・偶然の出来事が重なった。これは運命でなくてなんだろう",
    ],
    questions: [
      {
        id: "25-1",
        content: "命がけで他人を助けたその行為は、勇気___",
        answers: [
          "にほかならない",
          "でなくてなんだろう",
          "にすぎない",
          "というわけだ",
        ],
        correctAnswer: 1,
        memo: [
          "にほかならない: 'Chính là...' (khẳng định mạnh mẽ, ít cảm thán hơn).",
          "でなくてなんだろう: 'Không phải... thì là gì/Chính là...'. Khẳng định mạnh mẽ và cảm thán rằng hành động đó chính là Lòng Dũng Cảm (勇気). (Đúng)",
          "にすぎない: 'Chỉ là...', không phù hợp.",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
        ],
      },
      {
        id: "25-2",
        content: "誰も到達できない高み。これこそが、才能___",
        answers: [
          "にほかならない",
          "でなくてなんだろう",
          "にすぎない",
          "というわけだ",
        ],
        correctAnswer: 0,
        memo: [
          "にほかならない: 'Chính là/Không gì khác là...'. Khẳng định mạnh mẽ rằng tầm cao đó chính là Tài Năng (才能). (Đúng)",
          "でなくてなんだろう: 'Không phải... thì là gì' (cũng đúng, nhưng にほかならない nhấn mạnh sự thật hiển nhiên hơn).",
          "にすぎない: 'Chỉ là...', không phù hợp.",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
        ],
      },
      {
        id: "25-3",
        content: "困難に立ち向かい成功を収めた。これは努力の証___",
        answers: [
          "にほかならない",
          "にすぎない",
          "というわけだ",
          "でなくてなんだろう",
        ],
        correctAnswer: 0,
        memo: [
          "にほかならない: 'Chính là/Không gì khác là...'. Khẳng định mạnh mẽ rằng sự thành công đó chính là bằng chứng của nỗ lực (努力の証). (Đúng)",
          "にすぎない: 'Chỉ là...', không phù hợp.",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
          "でなくてなんだろう: 'Không phải... thì là gì' (cũng đúng, nhưng にほかならない mang tính khẳng định/kết luận mạnh mẽ hơn).",
        ],
      },
    ],
  },
  {
    front: "～にあっては",
    back: [
      "✨ Trong tình huống/hoàn cảnh... (Thường dùng cho hoàn cảnh đặc biệt, khó khăn hoặc đòi hỏi nghiêm ngặt, mang tính trang trọng)",
      "・Ví dụ: Trong hoàn cảnh thiên tai như thế này, sự hợp tác của mọi người là không thể thiếu",
      "📌 Dùng cho hoàn cảnh đặc biệt, khó khăn (thường là N) để rút ra một nhận định/yêu cầu mang tính trang trọng/nghiêm khắc.",
    ],
    more: [
      "🧩 N + にあっては",
      "⚖️ ～においては (chỉ trong phạm vi/lĩnh vực nào đó, còn にあっては nhấn mạnh tính đặc thù/nghiêm trọng của hoàn cảnh)",
      "💬 Văn viết, rất trang trọng.",
      "📝 ví dụ",
      "・このような天災にあっては、皆の協力が不可欠だ",
      "・この緊急事態にあっては、一刻一秒が惜しい",
    ],
    questions: [
      {
        id: "26-1",
        content: "未曾有の危機___、冷静な判断が求められる",
        answers: ["について", "において", "にあたって", "にあっては"],
        correctAnswer: 3,
        memo: [
          "について: 'Về vấn đề...', không phù hợp.",
          "において: 'Trong lĩnh vực/ở nơi...', không nhấn mạnh hoàn cảnh đặc biệt/khó khăn.",
          "にあたって: 'Nhân dịp/Khi bắt đầu...', không phù hợp.",
          "にあっては: 'Trong hoàn cảnh...'. Dùng cho hoàn cảnh đặc biệt, khó khăn (khủng hoảng chưa từng có) để đưa ra yêu cầu nghiêm ngặt (cần phán đoán bình tĩnh). (Đúng)",
        ],
      },
      {
        id: "26-2",
        content: "この国___、教育は最も重要な課題だ",
        answers: ["にあって", "にあたって", "において", "について"],
        correctAnswer: 2,
        memo: [
          "にあって: 'Trong hoàn cảnh...' (ít trang trọng hơn にあっては).",
          "にあたって: 'Nhân dịp/Khi bắt đầu...', không phù hợp.",
          "において: 'Trong/Ở lĩnh vực/phạm vi...'. Dùng để chỉ phạm vi rộng (trong quốc gia này). (Đúng)",
          "について: 'Về vấn đề...', không phù hợp.",
        ],
      },
      {
        id: "26-3",
        content:
          "極度のプレッシャー___、最高のパフォーマンスを発揮するのは難しい",
        answers: ["において", "にあって", "にあっては", "について"],
        correctAnswer: 2,
        memo: [
          "において: 'Trong lĩnh vực/ở nơi...', không phù hợp.",
          "にあって: 'Trong hoàn cảnh...' (ít trang trọng hơn にあっては).",
          "にあっては: 'Trong hoàn cảnh...'. Dùng cho hoàn cảnh đặc biệt, khó khăn (áp lực cực độ) để đưa ra nhận định (khó phát huy tối đa). (Đúng)",
          "について: 'Về vấn đề...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～といったところだ",
    back: [
      "✨ Đại khái là/Chừng đó là cùng (Thể hiện mức độ tối đa, nhưng ở mức thấp hoặc trung bình, mang tính khiêm tốn)",
      "・Ví dụ: Tiền lương một tháng đại khái là 20 man là cùng",
      "📌 Đưa ra con số, mức độ hoặc phạm vi tối đa nhưng lại mang ý nghĩa không lớn/không đáng kể/chỉ đến thế mà thôi.",
    ],
    more: [
      "🧩 N / Vる + といったところだ",
      "⚖️ ～ぐらい/ほどだ (chỉ mức độ thông thường, といったところだ nhấn mạnh mức độ tối đa nhưng không cao)",
      "💬 Văn nói và viết, mang tính khiêm tốn hoặc đánh giá mức độ thấp.",
      "📝 ví dụ",
      "・一ヶ月の収入は20万円といったところだ",
      "・講義の内容は6割理解できたといったところだ",
    ],
    questions: [
      {
        id: "27-1",
        content: "今年のボーナスは、去年の半分___",
        answers: [
          "にすぎない",
          "にほかならない",
          "といったところだ",
          "というわけだ",
        ],
        correctAnswer: 2,
        memo: [
          "にすぎない: 'Chỉ là/Không hơn không kém' (thường dùng cho số ít, đơn giản, mang tính phủ định).",
          "にほかならない: 'Chính là...', không phù hợp.",
          "といったところだ: 'Đại khái là/Chừng đó là cùng'. Đưa ra mức độ (một nửa năm ngoái) và ngụ ý mức độ đó là tối đa, không đáng kể. (Đúng)",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
        ],
      },
      {
        id: "27-2",
        content: "彼女の日本語能力は、日常会話レベル___",
        answers: [
          "にほかならない",
          "にすぎない",
          "といったところだ",
          "というわけだ",
        ],
        correctAnswer: 2,
        memo: [
          "にほかならない: 'Chính là...', không phù hợp.",
          "にすぎない: 'Chỉ là...' (mang tính phủ định, chê bai).",
          "といったところだ: 'Đại khái là/Chừng đó là cùng'. Đưa ra mức độ tối đa của khả năng (cấp độ đàm thoại hàng ngày) và ngụ ý rằng chỉ đến thế mà thôi. (Đúng)",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
        ],
      },
      {
        id: "27-3",
        content: "彼が話せる外国語は、英語とフランス語少々___",
        answers: [
          "にすぎない",
          "というわけだ",
          "といったところだ",
          "にほかならない",
        ],
        correctAnswer: 2,
        memo: [
          "にすぎない: 'Chỉ là...', không phù hợp.",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
          "といったところだ: 'Đại khái là/Chừng đó là cùng'. Liệt kê phạm vi tối đa các ngôn ngữ có thể nói (Tiếng Anh và một chút tiếng Pháp) và ngụ ý là không nhiều. (Đúng)",
          "にほかならない: 'Chính là...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～とあって",
    back: [
      "✨ Vì/Do (Là lý do đặc biệt nên kết quả là một trạng thái đặc biệt)",
      "・Ví dụ: Vì là Giáng sinh nên khắp phố đều tấp nập",
      "📌 Đưa ra một lý do đặc biệt (N, Na) và kết quả là một tình trạng đặc trưng hoặc khác thường.",
    ],
    more: [
      "🧩 N / Na + とあって",
      "⚖️ ～だけあって (cũng là 'vì', nhưng だけあって nhấn mạnh sự xứng đáng, còn とあって nhấn mạnh sự đặc trưng của hoàn cảnh)",
      "💬 Văn viết, trang trọng, thường dùng trong báo chí.",
      "📝 ví dụ",
      "・クリスマスとあって、街はにぎやかだ",
      "・経験者とあって、彼女の仕事ぶりは見事だ",
    ],
    questions: [
      {
        id: "28-1",
        content: "連休の初日___、高速道路は渋滞している",
        answers: ["ならではの", "ならでは", "とあって", "のおかげで"],
        correctAnswer: 2,
        memo: [
          "ならではの: 'Chỉ có ở...' (đi kèm danh từ), không phù hợp.",
          "ならでは: 'Chỉ có ở...' (kết thúc câu), không phù hợp.",
          "とあって: 'Vì là...'. Vì là lý do đặc biệt (Ngày đầu tiên của kỳ nghỉ dài) nên dẫn đến trạng thái đặc trưng (đường cao tốc bị tắc nghẽn). (Đúng)",
          "のおかげで: 'Nhờ có...' (thường là tích cực), không phù hợp.",
        ],
      },
      {
        id: "28-2",
        content: "一流ホテルで働くスタッフ___、接客マナーは完璧だ",
        answers: ["だけあって", "とあって", "ならでは", "というものだ"],
        correctAnswer: 0,
        memo: [
          "だけあって: 'Quả đúng là/Xứng đáng là...'. Nhấn mạnh kết quả (thái độ phục vụ hoàn hảo) là xứng đáng với lý do (làm việc ở khách sạn hạng nhất). (Đúng)",
          "とあって: Chỉ nhấn mạnh sự đặc trưng của hoàn cảnh, không nhấn mạnh tính xứng đáng.",
          "ならでは: 'Chỉ có ở...', không phù hợp.",
          "というものだ: 'Thật là...', không phù hợp.",
        ],
      },
      {
        id: "28-3",
        content: "夏休みで長期休暇___、多くの人が海外旅行に出かけた",
        answers: ["とあって", "ならでは", "だけあって", "というものだ"],
        correctAnswer: 0,
        memo: [
          "とあって: 'Vì là...'. Vì là lý do đặc biệt (kỳ nghỉ dài do nghỉ hè) nên dẫn đến trạng thái đặc trưng (nhiều người đi du lịch nước ngoài). (Đúng)",
          "ならでは: 'Chỉ có ở...', không phù hợp.",
          "だけあって: 'Quả đúng là/Xứng đáng là...', không phù hợp.",
          "というものだ: 'Thật là...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～をものともせずに",
    back: [
      "✨ Bất chấp/Mặc kệ (Làm điều gì đó một cách can đảm, bất chấp trở ngại)",
      "・Ví dụ: Anh ấy bất chấp bệnh tật mà tiếp tục nghiên cứu",
      "📌 Đi kèm với trở ngại, khó khăn (thường là N) và diễn tả hành động can đảm, kiên cường, kết quả thường là tích cực.",
    ],
    more: [
      "🧩 N + をものともせずに",
      "⚖️ ～にもかかわらず (cũng là 'mặc dù', nhưng をものともせずに nhấn mạnh sự kiên cường, bất chấp mạnh mẽ hơn)",
      "💬 Văn viết, trang trọng, mang tính ca ngợi.",
      "📝 ví dụ",
      "・彼は病気をものともせずに研究を続けた",
      "・あらゆる批判をものともせずに、彼女は夢を追い続けた",
    ],
    questions: [
      {
        id: "29-1",
        content: "彼は周囲の冷たい視線___、自分の信念を貫いた",
        answers: ["をものともせずに", "にもかかわらず", "につけ", "にしろ"],
        correctAnswer: 0,
        memo: [
          "をものともせずに: 'Bất chấp...'. Hành động can đảm, kiên cường (giữ vững niềm tin) được thực hiện bất chấp khó khăn (ánh mắt lạnh lùng của người xung quanh). (Đúng)",
          "にもかかわらず: 'Mặc dù...', không nhấn mạnh sự kiên cường, ca ngợi mạnh mẽ như をものともせずに.",
          "につけ: 'Mỗi khi/hễ cứ', không phù hợp.",
          "にしろ: 'Dù là...', không phù hợp.",
        ],
      },
      {
        id: "29-2",
        content: "強い向かい風___、選手たちはゴールを目指して走り続けた",
        answers: ["にもかかわらず", "をものともせずに", "にかぎり", "にしろ"],
        correctAnswer: 1,
        memo: [
          "にもかかわらず: 'Mặc dù...', không nhấn mạnh sự kiên cường, ca ngợi mạnh mẽ như をものともせずに.",
          "をものともせずに: 'Bất chấp...'. Hành động can đảm, kiên cường (chạy tiếp) được thực hiện bất chấp trở ngại (gió ngược mạnh). (Đúng)",
          "にかぎり: 'Chỉ riêng...', không phù hợp.",
          "にしろ: 'Dù là...', không phù hợp.",
        ],
      },
      {
        id: "29-3",
        content: "強い反対___、そのプロジェクトは開始された",
        answers: ["にしろ", "にもかかわらず", "をものともせずに", "にせよ"],
        correctAnswer: 1,
        memo: [
          "にしろ: 'Dù là...', không phù hợp.",
          "にもかかわらず: 'Mặc dù...'. Diễn tả hành động (dự án được bắt đầu) xảy ra bất chấp sự đối lập (sự phản đối mạnh mẽ). (Đúng)",
          "をものともせずに: Thường dùng cho hành động mang tính cá nhân/tập thể cần sự can đảm, kiên cường.",
          "にせよ: 'Dù là...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～が早いか / ～やいなや / ～なり / ～とたんに",
    back: [
      "✨ Ngay sau khi (Diễn tả hành động B xảy ra tức thì sau khi hành động A vừa kết thúc)",
      "・Ví dụ: Vừa nghe chuông kết thúc, học sinh đã chạy ra khỏi lớp.",
      "📌 Nhấn mạnh tính tức thì, không có khoảng cách thời gian.",
    ],
    more: [
      "🧩 Vる / Vた + が早いか / やいなや / なり / とたんに",
      "⚖️",
      " * が早いか: Nhấn mạnh hành động bản năng, lặp lại. (Vる/Vた)",
      " * やいなや: Trang trọng, hành động bất ngờ. (Vる/Vた)",
      " * なり: Hành động bất ngờ, chủ ngữ duy nhất. (Vる)",
      " * とたんに: Thay đổi đột ngột (thường dùng cho hiện tượng tự nhiên). (Vる/Vた)",
      "💬 Cả văn nói và viết (trừ とたんに phổ biến hơn trong văn nói).",
      "📝 ví dụ",
      "・チャイムが鳴るが早いか、生徒たちは教室を飛び出した",
      "・総理大臣が演説を終えるやいなや、会場は大きな拍手に包まれた",
      "・彼は「行くぞ」と言ったなり、車の鍵を手に取った",
      "・夫は出張から帰ってきたとたんに、スーツケースを放り出すと寝室へ向かった",
    ],
    questions: [
      {
        id: "30-1",
        content:
          "夫は出張から帰ってき___、スーツケースを放り出すと寝室へ向かった",
        answers: ["とたんに", "が早いか", "につれて", "ところだ"],
        correctAnswer: 1,
        memo: [
          "とたんに: 'Ngay sau khi', dùng cho hành động B xảy ra tức thì sau A (ít nhấn mạnh hành động bản năng, lặp lại).",
          "が早いか: 'Ngay sau khi'. Hành động vứt vali và đi thẳng vào phòng ngủ là hành động mang tính bản năng, tức thì. Phù hợp nhất cho hành động bất ngờ, nhanh chóng của cá nhân. (Đúng)",
          "につれて: 'Cùng với sự thay đổi của...', không phù hợp.",
          "ところだ: 'Đúng lúc...', không phù hợp.",
        ],
      },
      {
        id: "30-2",
        content: "総理大臣が演説を終える___、会場は大きな拍手に包まれた",
        answers: ["やいなや", "つつ", "なり", "はする"],
        correctAnswer: 0,
        memo: [
          "やいなや: 'Ngay sau khi'. Dùng trong văn viết, trang trọng và chỉ sự việc khách quan, bất ngờ (diễn thuyết kết thúc thì hội trường vỗ tay). Rất phù hợp. (Đúng)",
          "つつ: 'Vừa... vừa...' (đồng thời), không phù hợp.",
          "なり: Thường dùng cho hành động bất ngờ của cá nhân.",
          "はする: 'Có làm nhưng...' (nhượng bộ), không phù hợp.",
        ],
      },
      {
        id: "30-3",
        content: "父が「行くぞ」と言った___、母は車の鍵を手に取った",
        answers: ["が早いか", "なり", "ところだ", "とたんに"],
        correctAnswer: 3,
        memo: [
          "が早いか: 'Ngay sau khi', thường dùng cho hành động bản năng, lặp lại.",
          "なり: 'Ngay sau khi', hành động B thường là bất ngờ, ngoài ý muốn.",
          "ところだ: 'Đúng lúc...', không phù hợp.",
          "とたんに: 'Ngay sau khi'. Hành động B (mẹ lấy chìa khóa) xảy ra ngay sau hành động A (cha nói đi). とたんに phù hợp khi chỉ sự thay đổi tức thì, đột ngột trong giao tiếp/hành động. (Đúng)",
        ],
      },
    ],
  },
];

export default cards;
