import { FlashCardItem } from "@/shared/component/flash-card/flash-card";

export const cards: FlashCardItem[] = [
  {
    front: "～がてら",
    back: [
      "✨ Nhân tiện (làm A nhân tiện làm B)",
      "・Ví dụ: Đi dạo nhân tiện ghé cửa hàng tiện lợi.",
      "📌 Hành động chính kèm hành động phụ, thường có yếu tố di chuyển.",
    ],
    more: [
      "🧩 N / Vます + がてら",
      "⚖️ ～ついでに (không nhấn yếu tố di chuyển), ～ながら (đồng thời)",
      "💬 Thường dùng trong văn nói, mang tính cá nhân.",
      "📝 ví dụ",
      "・散歩がてらコンビニに寄った",
      "・写真を撮りがてら山を登った",
    ],
    questions: [
      {
        id: "1-1",
        content: "ドライブ___、新しい喫茶店に行ってみた",
        answers: ["ながら", "につれて", "がてら", "ついでに"],
        correctAnswer: 2,
        memo: [
          "ながら: Diễn tả hai hành động đồng thời có chủ ý (vừa A vừa B), không nhấn yếu tố 'nhân tiện'.",
          "につれて: Diễn tả sự thay đổi tỷ lệ thuận (A thay đổi thì B thay đổi), không phù hợp.",
          "がてら: Hành động chính (lái xe) kèm hành động phụ (ghé quán cà phê), có yếu tố di chuyển và mục đích 'nhân tiện'. (Đúng)",
          "ついでに: Cũng là 'nhân tiện' nhưng がてら được coi là trang trọng hơn và nhấn mạnh yếu tố di chuyển.",
        ],
      },
      {
        id: "1-2",
        content: "銀行に寄った___、郵便局で手紙を出した",
        answers: ["がてら", "ついでに", "をめぐって", "のところに"],
        correctAnswer: 1,
        memo: [
          "がてら: Cũng là 'nhân tiện' nhưng ついでに tự nhiên hơn khi hai hành động không có sự phụ thuộc chính-phụ rõ ràng.",
          "ついでに: 'Nhân tiện'. Hành động chính là đến ngân hàng, nhân tiện đó ghé bưu điện. Rất tự nhiên. (Đúng)",
          "をめぐって: 'Xoay quanh/Về vấn đề...', không liên kết hành động.",
          "のところに: Không phải ngữ pháp liên kết hành động 'nhân tiện'.",
        ],
      },
      {
        id: "1-3",
        content: "故郷のニュースを聞く___、昔のことを思い出す",
        answers: ["ながら", "つつ", "につけ", "がてら"],
        correctAnswer: 2,
        memo: [
          "ながら: Diễn tả hành động đồng thời có ý thức, không phù hợp với ngữ cảnh 'mỗi khi nghe tin quê hương' kéo theo cảm xúc/trạng thái (nhớ lại).",
          "つつ: Diễn tả hành động đồng thời (trang trọng hơn ながら) hoặc đối lập, không phù hợp.",
          "につけ: Diễn tả 'mỗi khi/hễ cứ' (thường đi kèm với cảm xúc/tâm trạng: nhớ lại kỷ niệm). (Đúng)",
          "がてら: Diễn tả 'nhân tiện làm gì' (có chủ đích, di chuyển), không phù hợp với việc nhớ lại kỷ niệm.",
        ],
      },
    ],
  },
  {
    front: "～なり",
    back: [
      "✨ Ngay sau khi (vừa A thì ngay lập tức B xảy ra)",
      "・Ví dụ: Anh ấy vừa nhận điện thoại xong thì lập tức đứng dậy và ra khỏi phòng.",
      "📌 Hành động B là bất ngờ, ngoài ý muốn và xảy ra ngay sau A. Chỉ dùng cho ngôi thứ ba.",
    ],
    more: [
      "🧩 Vる + なり",
      "⚖️ ～やいなや / ～が早いか (dùng cho hành động mang tính khách quan hơn)",
      "💬 Văn viết hoặc nói trang trọng, mang tính kịch tính.",
      "📝 ví dụ",
      "・彼は電話を受けるなり、席を立って部屋を出ていった",
      "・子供は母親の顔を見るなり、わっと泣き出した",
    ],
    questions: [
      {
        id: "2-1",
        content: "彼は社長の顔を見る___、緊張のあまり言葉を失った",
        answers: ["をものともせず", "なり", "やいなや", "が早いか"],
        correctAnswer: 1,
        memo: [
          "をものともせず: 'Bất chấp...', không phù hợp.",
          "なり: 'Ngay sau khi'. Hành động B (mất lời vì căng thẳng) là phản ứng bất ngờ, ngoài ý muốn ngay sau khi thấy mặt, dùng cho ngôi thứ ba (anh ấy). Rất phù hợp. (Đúng)",
          "やいなや: 'Ngay sau khi', trang trọng, dùng cho hành động bất ngờ, mang tính khách quan.",
          "が早いか: 'Ngay sau khi', nhấn mạnh hành động bản năng, lặp lại.",
        ],
      },
      {
        id: "2-2",
        content: "終業のベルを聞く___、学生たちは教室から飛び出していった",
        answers: ["が早いか", "なり", "わけにはいかない", "において"],
        correctAnswer: 0,
        memo: [
          "が早いか: 'Ngay sau khi'. Nhấn mạnh tính tức thì và hành động mang tính bản năng, tập thể (học sinh ùa ra khỏi lớp) hơn. Phù hợp với ngữ cảnh khách quan này. (Đúng)",
          "なり: Thường nhấn mạnh hành động bất ngờ của cá nhân (ngôi thứ ba) hơn.",
          "わけにはいかない: 'Không thể (vì lý do nghĩa vụ)', không phù hợp.",
          "において: 'Trong/Ở lĩnh vực...', không phù hợp.",
        ],
      },
      {
        id: "2-3",
        content: "窓を開けた___、冷たい風が入ってきた",
        answers: ["をものともせず", "なり", "やいなや", "とたんに"],
        correctAnswer: 3,
        memo: [
          "をものともせず: 'Bất chấp...', không phù hợp.",
          "なり: Thường dùng cho hành động bất ngờ của một người, ít dùng cho hiện tượng tự nhiên.",
          "やいなや: Trang trọng, thường dùng cho sự kiện.",
          "とたんに: 'Ngay sau khi'. Nhấn mạnh sự thay đổi trạng thái đột ngột (gió lạnh ùa vào) ngay sau một hành động (mở cửa sổ). Rất phù hợp. (Đúng)",
        ],
      },
    ],
  },
  {
    front: "～手前（てまえ）",
    back: [
      "✨ Vì đứng trước/vì đã hứa/vì thể diện (nên phải làm gì)",
      "・Ví dụ: Vì đã hứa với con trai, nên dù bận tôi cũng phải đi.",
      "📌 Hành động tiếp theo là bắt buộc phải làm vì giữ thể diện hoặc lời đã hứa.",
    ],
    more: [
      "🧩 Vる / Nの + 手前",
      "⚖️ ～以上は (cũng là 'một khi đã', nhưng 手前 nhấn mạnh yếu tố thể diện)",
      "💬 Văn nói và viết, trang trọng, dùng để biện minh hoặc giải thích.",
      "📝 ví dụ",
      "・息子と遊園地へ行く約束をした手前、忙しくても行かないわけにはいかない",
      "・合格すると宣言した手前、勉強しないわけにはいかない",
    ],
    questions: [
      {
        id: "3-1",
        content:
          "人前で「やります」と断言した___、今さら「できません」とは言えない。",
        answers: ["手前", "からには", "ものの", "だけあって"],
        correctAnswer: 0,
        memo: [
          "手前: 'Vì thể diện/vì đã lỡ nói'. Vì đã tuyên bố trước mặt mọi người nên không thể nói là không làm được (vì giữ thể diện). (Đúng)",
          "からには: 'Một khi đã...', cũng đúng nhưng 手前 nhấn mạnh hơn về việc khó xử, mất thể diện khi làm trái lời đã nói.",
          "ものの: 'Mặc dù... nhưng...', không phù hợp.",
          "だけあって: 'Quả đúng là...', không phù hợp.",
        ],
      },
      {
        id: "3-2",
        content: "日本に来た___、日本の文化を学びたい。",
        answers: ["手前", "からには", "以上", "上で"],
        correctAnswer: 1,
        memo: [
          "手前: 'Vì thể diện...', không phù hợp.",
          "からには: 'Một khi đã...'. Nhấn mạnh một khi đã ở Nhật thì theo lẽ đương nhiên, muốn học văn hóa Nhật. (Đúng)",
          "以上: 'Một khi đã...', trang trọng hơn, thường dùng cho nghĩa vụ.",
          "上で: 'Sau khi...', không phù hợp.",
        ],
      },
      {
        id: "3-3",
        content: "契約書にサインした___、今からキャンセルすることはできない。",
        answers: ["手前", "上は", "ものの", "だけましだ"],
        correctAnswer: 1,
        memo: [
          "手前: 'Vì thể diện...', không phù hợp với ngữ cảnh ký kết hợp đồng.",
          "上は: 'Một khi đã... thì phải...'. Nhấn mạnh một khi đã thực hiện một hành động quan trọng (ký hợp đồng), thì theo logic/nghĩa vụ, phải tuân theo. Rất trang trọng. (Đúng)",
          "ものの: 'Mặc dù... nhưng...', không phù hợp.",
          "だけましだ: '... là còn tốt chán', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～を限りに／限りで",
    back: [
      "✨ Hết/Cho đến hết (dùng để tuyên bố chấm dứt một điều gì đó)",
      "・Ví dụ: Với ngày hôm nay là hết, tôi sẽ nghỉ việc.",
      "📌 Luôn đi kèm với danh từ chỉ thời gian và hành động sau là chấm dứt hoàn toàn.",
    ],
    more: [
      "🧩 N + を限りに / 限りで",
      "⚖️ ～をもって (cũng là 'kết thúc', nhưng をもって trang trọng hơn, dùng cho sự kiện công cộng)",
      "💬 Trang trọng, dùng trong thông báo chính thức.",
      "📝 ví dụ",
      "・今日を限りに、会社を辞めさせていただきます",
      "・この度の講義を限りで、もう参加しません",
    ],
    questions: [
      {
        id: "4-1",
        content: "本日___、このサービスを終了します。",
        answers: ["を限りに", "をもって", "かぎりだ", "限り"],
        correctAnswer: 0,
        memo: [
          "を限りに: 'Hết/Cho đến hết' (tuyên bố chấm dứt). Phù hợp nhất khi một cá nhân/tổ chức tuyên bố kết thúc một điều gì đó vào một mốc thời gian cụ thể. (Đúng)",
          "をもって: Cũng là 'kết thúc' nhưng thường dùng cho các sự kiện công cộng, mang tính hành chính cao hơn.",
          "かぎりだ: 'Vô cùng' (chỉ cảm xúc), không phù hợp.",
          "限り: 'Chừng nào còn...' hoặc 'Hết mức có thể', không phù hợp với ngữ cảnh 'tuyên bố chấm dứt'.",
        ],
      },
      {
        id: "4-2",
        content: "本年度___、この制度を廃止いたします",
        answers: ["に限って", "をもって", "に限らず", "を限りに"],
        correctAnswer: 1,
        memo: [
          "に限って: 'Chỉ riêng...' hoặc 'Thông thường...', không phù hợp.",
          "をもって: 'Kể từ/Cho đến hết' (thông báo kết thúc, thường dùng cho các sự kiện/chính sách công cộng, mang tính hành chính). Phù hợp với việc bãi bỏ chế độ. (Đúng)",
          "に限らず: 'Không chỉ...', không phù hợp.",
          "を限りに: Cũng có thể dùng nhưng をもって trang trọng và phù hợp hơn trong thông báo mang tính hành chính.",
        ],
      },
      {
        id: "4-3",
        content: "このコンサートを___、その歌手は引退するそうだ",
        answers: ["を限りに", "をもって", "限りで", "限りだ"],
        correctAnswer: 1,
        memo: [
          "を限りに: Thường dùng với mốc thời gian (今日、今月).",
          "をもって: 'Kể từ/Với mốc là'. Dùng để tuyên bố một sự kết thúc tại một thời điểm hoặc sự kiện cụ thể. Rất trang trọng và phù hợp với ngữ cảnh này. (Đúng)",
          "限りで: Gần nghĩa nhưng をもって tự nhiên hơn khi nói về một sự kiện lớn làm cột mốc.",
          "限りだ: 'Vô cùng' (chỉ cảm xúc), không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～限りだ",
    back: [
      "✨ Cực kỳ/Vô cùng (thể hiện cảm xúc mạnh mẽ của người nói)",
      "・Ví dụ: Thấy anh ấy thành công, tôi vô cùng vui mừng.",
      "📌 Luôn đi kèm với tính từ chỉ cảm xúc (vui, buồn, hối hận...) và là cách nói trang trọng.",
    ],
    more: [
      "🧩 Vる / Aい / Naである + 限りだ",
      "⚖️ ～というものだ (thật là.../mang tính khách quan hơn)",
      "💬 Văn viết, trang trọng.",
      "📝 ví dụ",
      "・彼の成功を見て、喜ばしい限りだ",
      "・自分の軽率な行動を反省し、悔しい限りだ",
    ],
    questions: [
      {
        id: "5-1",
        content: "彼のような若者が国を担うことは、心強い___",
        answers: ["限りだ", "ばかりだ", "一方だ", "ものだ"],
        correctAnswer: 0,
        memo: [
          "限りだ: 'Vô cùng'. Đi kèm với tính từ chỉ cảm xúc (心強い - an tâm, vững tâm) để nhấn mạnh cảm xúc mạnh mẽ của người nói. (Đúng)",
          "ばかりだ: Diễn tả sự thay đổi theo một chiều hướng (chỉ tăng/chỉ giảm), không phù hợp.",
          "一方だ: Diễn tả sự thay đổi theo một chiều hướng (chỉ tăng/chỉ giảm), không phù hợp.",
          "ものだ: 'Thật là...' (mang tính khách quan) hoặc 'Thường hay...', không nhấn mạnh cảm xúc mạnh mẽ như 限りだ.",
        ],
      },
      {
        id: "5-2",
        content: "長年の努力が実り、このような立派な賞をいただけて、___。",
        answers: ["てたまらない", "限りだ", "てならない", "光栄の至りです"],
        correctAnswer: 3,
        memo: [
          "てたまらない: '...không chịu được'. Diễn tả cảm xúc tự nhiên, khó kìm nén, thường dùng trong văn nói.",
          "限りだ: 'Vô cùng'. Đi kèm với tính từ chỉ cảm xúc (喜ばしい) để nhấn mạnh cảm xúc sâu sắc, trang trọng.",
          "てならない: '...không chịu được'. Trang trọng hơn, thường dùng cho cảm xúc tự nhiên, không kiểm soát được.",
          "光栄の至りです: 'Vô cùng vinh hạnh'. Là cách nói cực kỳ trang trọng và khiêm tốn, phù hợp nhất trong ngữ cảnh nhận giải thưởng. (Đúng)",
        ],
      },
      {
        id: "5-3",
        content: "彼の演奏は素晴らしく、感動___。",
        answers: ["の至り", "限りだ", "の極み", "してやまない"],
        correctAnswer: 2,
        memo: [
          "の至り: Thường đi với các danh từ trang trọng như 光栄, 恐縮.",
          "限りだ: 'Vô cùng', thường đi với tính từ cảm xúc.",
          "の極み: 'Cực kỳ/Tột đỉnh'. Thường đi với danh từ chỉ trạng thái, cảm xúc mạnh (感動の極み - tột đỉnh của sự cảm động). (Đúng)",
          "してやまない: 'Luôn luôn/Không ngừng...'. Dùng cho hành động, cảm xúc kéo dài.",
        ],
      },
    ],
  },
  {
    front: "～あっての",
    back: [
      "✨ Chính vì/Nhờ có (Nhấn mạnh A là điều kiện tiên quyết để có B)",
      "・Ví dụ: Thành công ngày hôm nay chính là nhờ có sự hỗ trợ của mọi người.",
      "📌 A là điều kiện quan trọng nhất, không có A thì không có B. Thường là các danh từ trừu tượng.",
    ],
    more: [
      "🧩 N + あっての + N",
      "⚖️ ～のおかげで (cũng là 'nhờ có', nhưng あっての nhấn mạnh mối quan hệ phụ thuộc mạnh mẽ hơn)",
      "💬 Văn viết trang trọng hoặc văn nói nhấn mạnh.",
      "📝 ví dụ",
      "・今日の成功は、皆さんの協力あってのものです",
      "・健康あっての仕事だ。無理をして体を壊してはいけない",
    ],
    questions: [
      {
        id: "6-1",
        content: "お客様___商売だ。",
        answers: ["あっての", "ならではの", "を抜きにしては", "おかげで"],
        correctAnswer: 0,
        memo: [
          "あっての: 'Chính vì/Nhờ có'. Nhấn mạnh việc kinh doanh (B) tồn tại được là nhờ có khách hàng (A). (Đúng)",
          "ならではの: 'Chỉ có ở/chỉ riêng'. Không phù hợp.",
          "を抜きにしては: 'Nếu không có... thì không thể'. Cũng đúng ngữ pháp nhưng あっての nhấn mạnh mối quan hệ nền tảng tự nhiên hơn.",
          "おかげで: 'Nhờ có'. Không nhấn mạnh sự phụ thuộc tuyệt đối bằng あっての.",
        ],
      },
      {
        id: "6-2",
        content: "努力___合格はあり得ない。",
        answers: ["あっての", "いかんでは", "を抜きにしては", "かぎりでは"],
        correctAnswer: 2,
        memo: [
          "あっての: Gần đúng, nhưng を抜きにしては nhấn mạnh ý 'nếu không có' một cách trực tiếp hơn.",
          "いかんでは: 'Tùy thuộc vào...'.",
          "を抜きにしては: 'Nếu không có/Loại trừ... thì không thể'. Nhấn mạnh nỗ lực là điều kiện không thể thiếu để đỗ. (Đúng)",
          "かぎりでは: 'Trong phạm vi/Theo như...'.",
        ],
      },
      {
        id: "6-3",
        content:
          "先生が丁寧に教えてくださった___、難しい問題が理解できました。",
        answers: ["せいで", "おかげで", "あっての", "かぎりでは"],
        correctAnswer: 1,
        memo: [
          "せいで: 'Tại vì'. Dùng cho kết quả xấu.",
          "おかげで: 'Nhờ có/Nhờ vào'. Diễn tả lòng biết ơn vì một kết quả tốt cụ thể. Phù hợp nhất. (Đúng)",
          "あっての: Quá mạnh, mang ý 'sự tồn tại của việc hiểu bài là nhờ có giáo viên', không tự nhiên bằng おかげで.",
          "かぎりでは: 'Trong phạm vi/Theo như...'.",
        ],
      },
    ],
  },
  {
    front: "～だの～だの",
    back: [
      "✨ Nào là... nào là... (Liệt kê các ví dụ tiêu cực, thể hiện sự chán nản/bất mãn)",
      "・Ví dụ: Anh ấy lúc nào cũng than phiền nào là tiền không đủ, nào là công việc vất vả.",
      "📌 Liệt kê các ví dụ tiêu cực hoặc không quan trọng, bày tỏ sự khó chịu, chán ghét của người nói.",
    ],
    more: [
      "🧩 N / Vる / Aい / Na + だの + ...",
      "⚖️ ～やら～やら (cũng là liệt kê, nhưng không mang ý nghĩa tiêu cực mạnh mẽ như だのだの)",
      "💬 Văn nói suồng sã, mang tính phàn nàn, tiêu cực.",
      "📝 ví dụ",
      "・彼はいつも給料が安いだの、仕事がつらいだのと愚痴ばかり言っている",
      "・彼女の暑いだの寒いだのという文句はもう聞き飽きた",
    ],
    questions: [
      {
        id: "7-1",
        content:
          "このレストランは、料理が遅い___、サービスが悪い___と評判が悪い",
        answers: ["やら/やら", "だの/だの", "につけ/につけ", "なら/なり"],
        correctAnswer: 1,
        memo: [
          "やら/やら: Cũng là liệt kê, nhưng không mang ý phàn nàn/tiêu cực mạnh mẽ như だの/だの.",
          "だの/だの: 'Nào là... nào là...'. Dùng để liệt kê các yếu tố tiêu cực (món ăn chậm, dịch vụ tệ) dẫn đến kết quả tiêu cực (tiếng xấu). Rất phù hợp. (Đúng)",
          "につけ/につけ: 'Mỗi khi A hay B...', không phù hợp.",
          "なら/なり: 'Nếu là A thì phải làm tương xứng...', không phù hợp.",
        ],
      },
      {
        id: "7-2",
        content: "部屋には、本___、雑誌___が散らかっていた。",
        answers: ["といい/といい", "にしろ/にしろ", "やら/やら", "だの/だの"],
        correctAnswer: 2,
        memo: [
          "といい/といい: 'Cả A và B...', mang tính liệt kê ví dụ tốt/xấu.",
          "にしろ/にしろ: 'Dù là A hay là B...', mang tính bao hàm.",
          "やら/やら: 'Nào là... nào là...'. Dùng để liệt kê các thứ một cách lộn xộn, không theo thứ tự, thể hiện sự bừa bộn. (Đúng)",
          "だの/だの: Thường mang ý phàn nàn, tiêu cực mạnh hơn.",
        ],
      },
      {
        id: "7-3",
        content: "電話が壊れる___、財布をなくす___で、大変な一日だった。",
        answers: ["わ/わ", "にかぎり", "だの/だの", "をいいことに"],
        correctAnswer: 0,
        memo: [
          "わ/わ: 'Nào là... nào là...'. Liệt kê các sự việc tiêu cực xảy ra chồng chất, dẫn đến một kết quả tồi tệ. Phù hợp nhất. (Đúng)",
          "にかぎり: 'Chỉ riêng...', không phù hợp.",
          "だの/だの: Thường dùng để liệt kê những lời phàn nàn, chỉ trích hơn là các sự kiện xảy ra.",
          "をいいことに: 'Lợi dụng...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～であれ～であれ",
    back: [
      "✨ Dù là A hay là B (thì kết quả vẫn không thay đổi, mang tính bao hàm)",
      "・Ví dụ: Dù là đàn ông hay phụ nữ thì lao động chân chính đều phải được tôn trọng.",
      "📌 Liệt kê hai trường hợp tương phản hoặc đối lập, kết quả sau đó là luôn luôn đúng với cả hai trường hợp.",
    ],
    more: [
      "🧩 N / Vる / Aい / Na + であれ + ...",
      "⚖️ ～にしろ～にしろ (cũng là 'dù là/hay là', nhưng であれであれ trang trọng và bao quát hơn)",
      "💬 Văn viết trang trọng.",
      "📝 ví dụ",
      "・男であれ女であれ、正当な労働は尊重されるべきだ",
      "・勝つであれ負けるであれ、初めの気持ちを忘れてはいけない",
    ],
    questions: [
      {
        id: "8-1",
        content: "正社員___アルバイト___、仕事に対する責任は同じだ",
        answers: [
          "にしても/にしても",
          "であれ/であれ",
          "といい/といい",
          "ばかりか/も",
        ],
        correctAnswer: 1,
        memo: [
          "にしても/にしても: 'Dù là A hay là B' (ít trang trọng hơn).",
          "であれ/であれ: 'Dù là A hay là B'. Liệt kê hai đối tượng (nhân viên chính thức và bán thời gian) để khẳng định một sự thật chung (trách nhiệm là như nhau). Trang trọng và bao quát. (Đúng)",
          "といい/といい: 'Cả A và B đều...', mang tính liệt kê ví dụ tiêu biểu.",
          "ばかりか/も: 'Không chỉ A mà còn B', không phù hợp.",
        ],
      },
      {
        id: "8-2",
        content: "行く___行かない___、早めに連絡してください。",
        answers: [
          "であれ/であれ",
          "にしろ/にしろ",
          "はする/が",
          "につけ/につけ",
        ],
        correctAnswer: 1,
        memo: [
          "であれ/であれ: Quá trang trọng cho ngữ cảnh này.",
          "にしろ/にしろ: 'Dù là A hay là B'. Dùng để liệt kê các lựa chọn và yêu cầu một hành động chung cho cả hai. Phù hợp với văn nói thông thường. (Đúng)",
          "はする/が: 'Có làm nhưng...', không phù hợp.",
          "につけ/につけ: 'Mỗi khi A hay B...', không phù hợp.",
        ],
      },
      {
        id: "8-3",
        content: "晴天___雨天___、明日の遠足は決行する",
        answers: [
          "にしても/にしても",
          "なり/なり",
          "を問わず",
          "であれ/であれ",
        ],
        correctAnswer: 2,
        memo: [
          "にしても/にしても: 'Dù là A hay là B' (ít trang trọng hơn).",
          "なり/なり: 'Hoặc là A hoặc là B' (chỉ sự lựa chọn), không phù hợp.",
          "を問わず: 'Không kể/Bất kể'. Cách nói ngắn gọn và phổ biến để chỉ việc không phụ thuộc vào điều kiện. (Đúng)",
          "であれ/であれ: 'Dù là A hay là B'. Cũng đúng nhưng を問わず tự nhiên hơn trong thông báo.",
        ],
      },
    ],
  },
  {
    front: "～どうにも…ない",
    back: [
      "✨ Hoàn toàn không thể (dù cố gắng thế nào cũng không thể, thường đi với V thể khả năng)",
      "・Ví dụ: Tôi hoàn toàn không thể tìm thấy chìa khóa đã đánh mất.",
      "📌 Đi kèm với động từ thể khả năng và phủ định để nhấn mạnh sự hoàn toàn bất lực.",
    ],
    more: [
      "🧩 どうにも + V (thể khả năng) ない",
      "⚖️ どうしても...ない (nhấn mạnh sự bất lực mạnh mẽ hơn)",
      "💬 Văn nói suồng sã, diễn tả sự bất lực cá nhân.",
      "📝 ví dụ",
      "・いくら探しても、なくした鍵はどうにも見つからない",
      "・こんなに病気が重くては、どうにも動けない",
    ],
    questions: [
      {
        id: "9-1",
        content: "この問題は難しすぎて、私一人の力では___理解で___",
        answers: [
          "なかなか/きない",
          "まったく/きない",
          "ほとんど/きない",
          "どうにも/きない",
        ],
        correctAnswer: 3,
        memo: [
          "なかなか/きない: 'Khó mà...' - diễn tả sự khó khăn nhưng không nhấn mạnh sự bất lực hoàn toàn.",
          "まったく/きない: 'Hoàn toàn không...' - phủ định mạnh nhưng thiếu sắc thái 'dù cố gắng thế nào'.",
          "ほとんど/きない: 'Hầu như không...' - chỉ mức độ gần như không, không phù hợp ngữ cảnh.",
          "どうにも/きない: 'Hoàn toàn không thể'. Nhấn mạnh sự bất lực hoàn toàn, dù cố gắng thế nào cũng không thể hiểu được. (Đúng)",
        ],
      },
      {
        id: "9-2",
        content: "何度頼んでも、彼は___首を縦に振らなかった。",
        answers: ["なんとか", "どうしても", "どうにも", "どうにか"],
        correctAnswer: 1,
        memo: [
          "なんとか: 'bằng cách nào đó' (khẳng định).",
          "どうしても: 'dù thế nào cũng'. Đi với phủ định để nhấn mạnh sự ngoan cố, kiên quyết không làm. (Đúng)",
          "どうにも: Thường đi với thể khả năng phủ định (どうにも...できない).",
          "どうにか: 'bằng cách nào đó' (khẳng định).",
        ],
      },
      {
        id: "9-3",
        content: "状況が複雑すぎて、___解決でき___",
        answers: [
          "どうしても/ない",
          "簡単には/ない",
          "とても/ない",
          "なかなか/ない",
        ],
        correctAnswer: 0,
        memo: [
          "どうしても/ない: 'Tuyệt đối không thể'. Nhấn mạnh sự bất khả kháng, không có cách nào giải quyết được dù cố gắng thế nào. (Đúng)",
          "簡単には/ない: 'Không thể dễ dàng...' - ngụ ý vẫn có thể nếu cố gắng, không phù hợp ngữ cảnh bế tắc.",
          "とても/ない: 'Không thể nào...' - đúng ngữ pháp nhưng どうしても nhấn mạnh sự bế tắc mạnh hơn.",
          "なかなか/ない: 'Khó mà...' - chỉ mức độ khó khăn, không nhấn mạnh sự bất khả kháng.",
        ],
      },
    ],
  },
  {
    front: "～はする",
    back: [
      "✨ Có làm/Có xảy ra (Nhấn mạnh hành động hoặc sự thật, thường ngụ ý 'nhưng mà', mang tính nhượng bộ)",
      "・Ví dụ: Món ăn này có ngon, nhưng mà giá hơi đắt.",
      "📌 Đặt は giữa Vます và する để nhấn mạnh sự thật của hành động, nhưng luôn đi kèm với vế sau mang tính đối lập/nhượng bộ.",
    ],
    more: [
      "🧩 Vます + は + する",
      "⚖️ VるにはVる (cũng là 'có... thì có...', nhưng はする nhấn mạnh yếu tố đối lập/hối tiếc sau đó hơn)",
      "💬 Văn nói, dùng để nhượng bộ và đối lập (Có A nhưng B).",
      "📝 ví dụ",
      "・この料理は美味しいはするが、値段が少し高い",
      "・来るとは言ったはするが、まだ確実ではないようだ",
    ],
    questions: [
      {
        id: "10-1",
        content: "彼の説明は、一応理解___が、まだ腑に落ちない点がある。",
        answers: ["ではある", "はする", "にしても", "こそする"],
        correctAnswer: 1,
        memo: [
          "ではある: (Dùng với Na/N) 'Tuy là...', mang nghĩa nhượng bộ/đối lập.",
          "はする: (Vます + はする) Nhấn mạnh sự thật rằng 'có hiểu' (理解はする), nhưng đi kèm với vế đối lập (vẫn còn điểm chưa thông suốt). (Đúng)",
          "にしても: 'Dù là...' (nhượng bộ), không phù hợp với cấu trúc này.",
          "こそする: Nhấn mạnh hành động (chính là làm), không mang ý nghĩa nhượng bộ/đối lập.",
        ],
      },
      {
        id: "10-2",
        content: "読む___読んだが、内容はほとんど覚えていない。",
        answers: ["には", "にしても", "といい", "はするが"],
        correctAnswer: 0,
        memo: [
          "には: Cấu trúc VるにはVたが... có nghĩa là 'có làm... thì có làm rồi, nhưng...'. Nhấn mạnh sự việc đã xảy ra nhưng kết quả không như ý. (Đúng)",
          "にしても: 'Dù là...' (nhượng bộ), không phù hợp với cấu trúc này.",
          "といい: 'Cả... và...' (liệt kê), không phù hợp.",
          "はするが: Gần đúng, nhưng VるにはVたが tự nhiên hơn khi lặp lại cùng một động từ.",
        ],
      },
      {
        id: "10-3",
        content: "雨は降った___、すぐにやんだ。",
        answers: ["ものの", "こそすれ", "ではあるが", "ならする"],
        correctAnswer: 0,
        memo: [
          "ものの: 'Mặc dù... nhưng...'. Diễn tả sự thật là 'có mưa', nhưng vế sau là một sự thật trái với dự đoán (tạnh ngay). (Đúng)",
          "こそすれ: 'Chỉ có... chứ không...', không phù hợp.",
          "ではあるが: Dùng với N/Na, không dùng với động từ.",
          "ならする: 'Nếu làm', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～ているばあいではない",
    back: [
      "✨ Không phải lúc để.../Không thể... được (Nhấn mạnh tình huống khẩn cấp, không cho phép làm điều đó)",
      "・Ví dụ: Đây không phải là lúc để nghỉ ngơi.",
      "📌 Nhấn mạnh sự không phù hợp của một hành động trong một tình huống nghiêm trọng, cần phải làm việc khác ngay lập tức.",
    ],
    more: [
      "🧩 Vて いる / N + の + ばあいではない",
      "⚖️ ～どころではない (cũng là 'không phải lúc', nhưng ばあいではない nhấn mạnh sự cần thiết phải hành động)",
      "💬 Văn nói và viết, dùng để nhấn mạnh tình huống khẩn cấp, cần hành động.",
      "📝 ví dụ",
      "・休んでいるばあいではない。すぐに出発しなければならない",
      "・こんなに危険な状況で、心配しているばあいではない、早く行動しろ",
    ],
    questions: [
      {
        id: "11-1",
        content: "火事だ！逃げろ！のんびりテレビを見___",
        answers: [
          "ところではない",
          "わけではない",
          "ているばあいではない",
          "どころではない",
        ],
        correctAnswer: 2,
        memo: [
          "ところではない: Không có cách diễn đạt này.",
          "わけではない: 'Không hẳn là...' (phủ định một phần), không phù hợp.",
          "ているばあいではない: 'Không phải lúc để...'. Nhấn mạnh tình huống khẩn cấp (có hỏa hoạn) nên không phải lúc để xem TV. (Đúng)",
          "どころではない: 'Hoàn toàn không thể (vì bận/tình hình tệ)'. Cũng đúng, nhưng ばあいではない nhấn mạnh sự phi lý của hành động trong hoàn cảnh đó.",
        ],
      },
      {
        id: "11-2",
        content: "風邪をひいて、遊びに行く___。",
        answers: [
          "わけではない",
          "どころではない",
          "ことではない",
          "ばあいではない",
        ],
        correctAnswer: 1,
        memo: [
          "わけではない: 'Không hẳn là...' (phủ định một phần), không phù hợp.",
          "どころではない: 'Hoàn toàn không thể (vì tình hình quá tệ/bận)'. Vì bị cảm nên không có tâm trí/sức lực để đi chơi. (Đúng)",
          "ことではない: 'Không phải là việc...', không phù hợp.",
          "ばあいではない: 'Không phải lúc để...'. Cũng có thể dùng, nhưng どころではない nhấn mạnh sự ảnh hưởng của tình trạng cá nhân (bị ốm) hơn.",
        ],
      },
      {
        id: "11-3",
        content: "災害が発生した。一刻も早く避難しなければ、様子を見___",
        answers: [
          "どころか",
          "というわけだ",
          "ているばあいではない",
          "によって",
        ],
        correctAnswer: 2,
        memo: [
          "どころか: 'Chứ đừng nói là...', không phù hợp.",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
          "ているばあいではない: 'Không phải lúc để...' (nhấn mạnh tình huống khẩn cấp). Thảm họa đã xảy ra, không phải lúc để quan sát, phải sơ tán ngay. (Đúng)",
          "によって: 'Tùy theo/Bằng cách...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～なら…なり",
    back: [
      "✨ Nếu là A thì hãy làm tương ứng với A/Trong phạm vi có thể (thể hiện sự chấp nhận điều kiện hiện tại và hành động trong phạm vi đó)",
      "・Ví dụ: Nếu không có tiền thì hãy làm theo cách không có tiền",
      "📌 Hành động B phải là hành động tương xứng hoặc hợp lý với điều kiện A (dù A có thể là tiêu cực/kém lý tưởng).",
    ],
    more: [
      "🧩 N / Vる / Aい + なら + N / Vる / Aい + なりに/なり",
      "⚖️ VるなりVるなり (là 'hoặc là làm V1 hoặc là làm V2', chỉ sự lựa chọn)",
      "💬 Văn nói, dùng để thể hiện sự chấp nhận điều kiện và hành động tương xứng.",
      "📝 ví dụ",
      "・金がないなら、金がないなりのやり方があるはずだ",
      "・気に入らないなら、気に入らないなりにそう言ってくれ",
    ],
    questions: [
      {
        id: "12-1",
        content: "まだ子供___、子供___にできることをやるべきだ",
        answers: ["ならば/なり", "なら/ならば", "なら/なりに", "なり/なりに"],
        correctAnswer: 2,
        memo: [
          "ならば/なり: Sai cấu trúc.",
          "なら/ならば: Sai cấu trúc.",
          "なら/なりに: 'Nếu là... thì hãy làm tương ứng với...'. Nếu là trẻ con thì hãy làm những việc mà trẻ con có thể làm. (N なら N なりに). (Đúng)",
          "なり/なりに: Sai cấu trúc.",
        ],
      },
      {
        id: "12-2",
        content: "電話___メール___、どちらかで連絡してください。",
        answers: ["なり/なり", "ならば/ならば", "にしろ/にしろ", "なら/なり"],
        correctAnswer: 0,
        memo: [
          "なり/なり: 'Hoặc là... hoặc là...'. Đưa ra các lựa chọn (điện thoại hoặc email) và yêu cầu chọn một. (Đúng)",
          "ならば/ならば: Sai cấu trúc.",
          "にしろ/にしろ: 'Dù là A hay là B', không phù hợp.",
          "なら/なり: Sai cấu trúc.",
        ],
      },
      {
        id: "12-3",
        content: "困ったときは、先生___友達___に相談するといい",
        answers: ["ならば/なりに", "なり/なり", "にしろ/にしろ", "なら/なり"],
        correctAnswer: 1,
        memo: [
          "ならば/なりに: Sai cấu trúc.",
          "なり/なり: 'Hoặc là... hoặc là...'. Khi gặp khó khăn thì 'hoặc là hỏi thầy giáo hoặc là hỏi bạn bè' (chỉ sự lựa chọn). (Đúng)",
          "にしろ/にしろ: 'Dù là A hay là B', không phù hợp.",
          "なら/なり: Sai cấu trúc.",
        ],
      },
    ],
  },
  {
    front: "～わ...わ（で）",
    back: [
      "✨ Nào là... nào là... (Liệt kê nhiều sự việc, thường là tiêu cực, dẫn đến kết quả tệ hại/khó khăn)",
      "・Ví dụ: Nào là bị cảm, nào là bị mất ví, tôi đã có một ngày thật tồi tệ.",
      "📌 Liệt kê tối thiểu hai sự kiện tiêu cực/khó khăn xảy ra liên tiếp, vế sau là kết quả tất yếu.",
    ],
    more: [
      "🧩 Vる / Aい / N / Na + わ + ...",
      "⚖️ ～だの～だの (cũng là tiêu cực, nhưng わ…わ nhấn mạnh sự chồng chất của nhiều vấn đề)",
      "💬 Văn nói và viết, diễn tả sự chồng chất của nhiều vấn đề, mang tính tiêu cực.",
      "📝 ví dụ",
      "・風邪をひくわ、財布をなくすわ（で）、ひどい一日だった",
      "・義母は病気になるわ、子供は学費を要求するわ（で）、私は大変だ",
    ],
    questions: [
      {
        id: "13-1",
        content:
          "仕事は終わらない___、締め切りは迫る___（で）、ストレスがたまった",
        answers: ["わ/わ", "だの/だの", "にしたところで", "にしろ/にしろ"],
        correctAnswer: 0,
        memo: [
          "わ/わ: 'Nào là... nào là...'. Liệt kê các yếu tố tiêu cực chồng chất (công việc không xong, deadline cận kề) dẫn đến kết quả tệ hại (tích tụ stress). (Đúng)",
          "だの/だの: Thường nhấn mạnh sự phàn nàn/bất mãn hơn là sự chồng chất dẫn đến hậu quả.",
          "にしたところで: 'Ngay cả...', không phù hợp.",
          "にしろ/にしろ: 'Dù là A hay là B' (bao hàm), không phù hợp.",
        ],
      },
      {
        id: "13-2",
        content: "彼は給料が安い___、仕事が忙しい___と文句ばかり言っている。",
        answers: ["にしても/にしても", "だの/だの", "わ/わ", "なり/なり"],
        correctAnswer: 1,
        memo: [
          "にしても/にしても: 'Dù là A hay là B' (nhượng bộ/bao hàm), không phù hợp.",
          "だの/だの: 'Nào là... nào là...'. Dùng để liệt kê các lời phàn nàn, chỉ trích. (Đúng)",
          "わ/わ: Thường dùng để liệt kê các sự kiện xảy ra, dẫn đến một kết quả.",
          "なり/なり: 'Hoặc là... hoặc là...', không phù hợp.",
        ],
      },
      {
        id: "13-3",
        content: "部屋には本___雑誌___が散らかっていた。",
        answers: ["やら/やら", "だの/だの", "にしろ/にしろ", "わ/わ"],
        correctAnswer: 0,
        memo: [
          "やら/やら: 'Nào là... nào là...'. Dùng để liệt kê các thứ một cách lộn xộn, không theo thứ tự, thể hiện sự bừa bộn. (Đúng)",
          "だの/だの: Thường mang ý phàn nàn, tiêu cực mạnh hơn.",
          "にしろ/にしろ: 'Dù là A hay là B' (bao hàm), không phù hợp.",
          "わ/わ: Thường dùng để liệt kê các sự kiện xảy ra, dẫn đến một kết quả.",
        ],
      },
    ],
  },
  {
    front: "～をいいことに",
    back: [
      "✨ Lợi dụng... (Lợi dụng một điều kiện/sự vắng mặt để làm điều không tốt)",
      "・Ví dụ: Cô ấy lợi dụng việc thầy giáo không có ở đây để lười biếng",
      "📌 Lợi dụng một trạng thái thuận lợi (thường là tiêu cực hoặc sự vắng mặt) để thực hiện một hành vi tiêu cực/ích kỷ.",
    ],
    more: [
      "🧩 Vる / Vた / Aい / Na / N + の/こと + をいいことに",
      "⚖️ ～につけこんで (ám chỉ việc lợi dụng điểm yếu/sơ hở)",
      "💬 Văn nói, mang tính tiêu cực, dùng để chỉ trích hành vi lợi dụng.",
      "📝 ví dụ",
      "・先生がいないのをいいことに、彼女は怠けている",
      "・皆が親切にしてくれるのをいいことに、彼はわがままなことをする",
    ],
    questions: [
      {
        id: "14-1",
        content: "テストが中止になった___、彼は一切勉強しなくなった",
        answers: ["につれて", "のをいいことに", "をめぐって", "の限り"],
        correctAnswer: 1,
        memo: [
          "につれて: 'Cùng với sự thay đổi của...', không phù hợp.",
          "のをいいことに: 'Lợi dụng...'. Lợi dụng việc thi bị hủy (là điều kiện thuận lợi) để làm điều không tốt (không học nữa). (Đúng)",
          "をめぐって: 'Xoay quanh/Về vấn đề...', không phù hợp.",
          "の限り: 'Hết mức có thể', không phù hợp.",
        ],
      },
      {
        id: "14-2",
        content: "相手の弱み___、彼は交渉を有利に進めた。",
        answers: ["につけ", "にしても", "のをいいことに", "につけこんで"],
        correctAnswer: 3,
        memo: [
          "につけ: 'Mỗi khi/hễ cứ', không phù hợp.",
          "にしても: 'Dù là...', không phù hợp.",
          "のをいいことに: 'Lợi dụng (điều kiện thuận lợi)'.",
          "につけこんで: 'Lợi dụng (điểm yếu/sơ hở)'. Lợi dụng điểm yếu của đối phương để làm điều có lợi cho mình. (Đúng)",
        ],
      },
      {
        id: "14-3",
        content: "相手の無知___、彼は不当な契約を結ばせた。",
        answers: ["のをいいことに", "を限りに", "にしろ", "につけこんで"],
        correctAnswer: 3,
        memo: [
          "のをいいことに: 'Lợi dụng (điều kiện thuận lợi)'.",
          "を限りに: 'Cho đến hết', không phù hợp.",
          "にしろ: 'Dù là...', không phù hợp.",
          "につけこんで: 'Lợi dụng (điểm yếu/sơ hở)'. Lợi dụng sự thiếu hiểu biết của đối phương (là một điểm yếu) để làm điều xấu (ép ký hợp đồng bất công). (Đúng)",
        ],
      },
    ],
  },
  {
    front: "～いざ～となると／～となれば／～となったら",
    back: [
      "✨ Cứ hễ đến lúc/Khi cần thiết (sẽ có sự thay đổi đột ngột về thái độ, hành động, hoặc sự thật được làm rõ)",
      "・Ví dụ: Mặc dù nói là biết, nhưng cứ hễ đến lúc làm thì lại hoàn toàn không thể",
      "📌 Diễn tả sự thay đổi đột ngột hoặc tiết lộ sự thật khi điều kiện đặc biệt/thời điểm quyết định đến.",
    ],
    more: [
      "🧩 いざ + N / Vる + となると/となれば/となったら",
      "⚖️ となると (trang trọng hơn), となれば (nhấn mạnh điều kiện), となったら (thông thường hơn)",
      "💬 Văn nói và viết, dùng để nhấn mạnh sự thay đổi khi đến thời điểm quyết định.",
      "📝 ví dụ",
      "・知っていると言ったが、いざやるとなると、全然できない",
      "・いざお金がとなれば、彼は態度を変えて優しくなる",
    ],
    questions: [
      {
        id: "15-1",
        content: "いつも口では偉そうだが、___ 実行 ___、彼は何もできない",
        answers: [
          "いざ/になったら",
          "まさか/となると",
          "いざ/となると",
          "いざ/にしても",
        ],
        correctAnswer: 2,
        memo: [
          "いざ/になったら: Không phù hợp cấu trúc (いざ đi với Vる).",
          "まさか/となると: 'Không ngờ...', không phù hợp.",
          "いざ/となると: 'Cứ hễ đến lúc/khi cần thiết... thì...'. Luôn nói mạnh miệng nhưng cứ hễ đến lúc thực hành thì lại không làm được. (Đúng)",
          "いざ/にしても: 'Dù là...', không phù hợp.",
        ],
      },
      {
        id: "15-2",
        content: "留学する___、親のありがたみがわかるだろう。",
        answers: [
          "まさか/となると",
          "いざ/になれば",
          "こととなれば",
          "いざ/となれば",
        ],
        correctAnswer: 2,
        memo: [
          "まさか/となると: 'Không ngờ...', không phù hợp.",
          "いざ/になれば: Sai cấu trúc.",
          "こととなれば: 'Nếu nói đến việc...'. Dùng để nhấn mạnh một chủ đề, và vế sau là một thái độ, hành động đặc biệt liên quan đến chủ đề đó. (Đúng)",
          "いざ/となれば: 'Cứ hễ đến lúc...'. Thường dùng cho thời điểm quyết định, hành động cụ thể.",
        ],
      },
      {
        id: "15-3",
        content: "普段はおとなしいが、___トラブル___、彼は頼りになる",
        answers: [
          "いざという時",
          "いざ/となっては",
          "まさか/となったら",
          "いざ/になったら",
        ],
        correctAnswer: 0,
        memo: [
          "いざという時: 'Vào lúc cần thiết/khẩn cấp'. Là một cụm từ cố định chỉ thời điểm quan trọng. (Đúng)",
          "いざ/となっては: Có ý nghĩa tương tự, nhưng いざという時 phổ biến hơn.",
          "まさか/となったら: 'Không ngờ...', không phù hợp.",
          "いざ/になったら: Không phù hợp cấu trúc.",
        ],
      },
    ],
  },
  {
    front: "～との",
    back: [
      "✨ Rằng/Nghe nói là (Chỉ nguồn tin, thông báo; dùng trong văn viết, phát thanh, báo chí)",
      "・Ví dụ: Có thông báo rằng cuộc họp đã bị hoãn lại",
      "📌 Chỉ dùng để trích dẫn hoặc thông báo nguồn tin chính thức/công cộng và mang tính trang trọng.",
    ],
    more: [
      "🧩 V / Aい / Na / N + との + N (danh từ chỉ thông tin: 連絡, ニュース...)",
      "⚖️ ～という (cũng là 'rằng', nhưng との trang trọng hơn và bắt buộc phải đi kèm với một danh từ chỉ thông tin)",
      "💬 Văn viết, trang trọng, dùng trong thông báo chính thức, báo chí.",
      "📝 ví dụ",
      "・会議は中止されたとの連絡があった",
      "・社長が辞任するとのニュースを聞いた",
    ],
    questions: [
      {
        id: "16-1",
        content: "来月新製品が発売される___公式発表があった",
        answers: ["と", "という", "というわけだ", "との"],
        correctAnswer: 3,
        memo: [
          "と: Thường đi với V/N nói/nghĩ, ít dùng trong thông báo chính thức.",
          "という: Cũng là trích dẫn, nhưng との trang trọng hơn trong văn bản chính thức.",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
          "との: 'Rằng/Nghe nói là'. Kết hợp với danh từ chỉ thông báo (公式発表) để trích dẫn nội dung thông báo một cách trang trọng. (Vる + との + N). (Đúng)",
        ],
      },
      {
        id: "16-2",
        content: "彼が結婚した___話は本当ですか。",
        answers: ["としての", "という", "との", "とのこと"],
        correctAnswer: 1,
        memo: [
          "としての: 'Với tư cách là...', không phù hợp.",
          "という: 'rằng'. Dùng để trích dẫn nội dung của danh từ đi sau (話 - câu chuyện). Đây là cách dùng phổ biến nhất. (Đúng)",
          "との: Quá trang trọng cho văn nói thông thường và thường đi với danh từ chỉ thông báo chính thức.",
          "とのこと: 'Nghe nói là...' (kết thúc câu), không đi kèm trực tiếp với danh từ 話.",
        ],
      },
      {
        id: "16-3",
        content: "田中さんから電話があって、会議は明日だ___。",
        answers: ["との", "と", "というわけだ", "とのことだ"],
        correctAnswer: 3,
        memo: [
          "との: Phải đi kèm với danh từ (vd: との連絡).",
          "と: Thường đi với V/N nói/nghĩ.",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
          "とのことだ: 'Nghe nói là...'. Dùng để truyền đạt lại thông tin nghe được từ người khác. (Đúng)",
        ],
      },
    ],
  },
  {
    front: "～てもしかたがない",
    back: [
      "✨ Có làm... cũng vô ích/Không thể tránh khỏi (Thể hiện sự chấp nhận điều không mong muốn)",
      "・Ví dụ: Dù có hối hận về những gì đã xảy ra thì cũng vô ích",
      "📌 Diễn tả sự vô ích của một hành động, thường là hành động mang tính cảm xúc đối với một sự thật không thể thay đổi",
    ],
    more: [
      "🧩 Vて + もしかたがない/しょうがない/どうしようもない",
      "⚖️ ～てもはじまらない (cũng là 'vô ích', trang trọng hơn)",
      "💬 Văn nói suồng sã, dùng để chấp nhận/biện minh cho sự vô ích.",
      "📝 ví dụ",
      "・起きてしまったことを後悔してもしかたがない",
      "・終わったことを泣いてもしかたがない",
    ],
    questions: [
      {
        id: "17-1",
        content: "今さら、あの時の判断を悔やん___",
        answers: [
          "でもいい",
          "でもしかたがない",
          "でも構わない",
          "でもいいはずだ",
        ],
        correctAnswer: 1,
        memo: [
          "でもいい: 'Có thể làm... cũng được', không phù hợp với ngữ cảnh tiếc nuối/vô ích.",
          "でもしかたがない: 'Có làm... cũng vô ích'. Hối hận về quyết định lúc đó bây giờ cũng vô ích vì không thể thay đổi được. (Đúng)",
          "でも構わない: 'Có thể làm... cũng được', không phù hợp với ngữ cảnh tiếc nuối/vô ích.",
          "でもいいはずだ: 'Lẽ ra có thể làm...', không phù hợp.",
        ],
      },
      {
        id: "17-2",
        content: "終わったことを今さら言っ___。",
        answers: [
          "てもいい",
          "てもはじまらない",
          "てもかまわない",
          "てもしかたがない",
        ],
        correctAnswer: 1,
        memo: [
          "てもいい: 'Có thể làm... cũng được', không phù hợp.",
          "てもはじまらない: 'Có nói cũng chẳng giải quyết được gì'. Thường dùng với động từ mang tính ý chí như 言う, 嘆く, 愚痴る. Nhấn mạnh hành động đó hoàn toàn vô nghĩa. (Đúng)",
          "てもかまわない: 'Có thể làm... cũng được', không phù hợp.",
          "てもしかたがない: 'Có nói cũng đành chịu'. Cũng đúng ngữ pháp, nhưng nhấn mạnh sự chấp nhận hơn là sự vô ích của hành động. てもはじまらない phù hợp hơn vì 言う là hành động mang tính ý chí.",
        ],
      },
      {
        id: "17-3",
        content: "電車が遅れて遅刻したのだから、___。",
        answers: [
          "しかたがない",
          "はじまらない",
          "わけがない",
          "ものではない",
        ],
        correctAnswer: 0,
        memo: [
          "しかたがない: 'Đành chịu/Không có cách nào'. Diễn tả sự chấp nhận điều không mong muốn do hoàn cảnh khách quan (tàu trễ). (Đúng)",
          "はじまらない: 'Cũng vô ích' - cần đi với ても, và thường dùng cho hành động mang tính ý chí như 'nói', 'than phiền'.",
          "わけがない: 'Không thể nào...' - diễn tả sự phủ định mạnh, không phù hợp ngữ cảnh chấp nhận.",
          "ものではない: 'Không nên...' - diễn tả lời khuyên/cấm, không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～Vずにはおかない",
    back: [
      "✨ Nhất định sẽ.../Không thể không... (Diễn tả ý chí mạnh mẽ của người nói rằng hành động B nhất định sẽ xảy ra/ảnh hưởng đến người khác)",
      "・Ví dụ: Tác phẩm này nhất định sẽ gây ấn tượng mạnh mẽ cho người xem",
      "📌 Thể hiện sự chắc chắn rằng hành động sẽ gây ra một ảnh hưởng mạnh mẽ lên người/vật khác. Chỉ dùng cho ngôi thứ ba.",
    ],
    more: [
      "🧩 Vない + ずにはおかない (bỏ ない)",
      "⚖️ ～ずにはいられない (là 'không thể không/không kìm được', dùng cho cảm xúc của chính người nói)",
      "💬 Văn viết, trang trọng.",
      "📝 ví dụ",
      "・この作品は見る人に感動を与えずにはおかないだろう",
      "・彼の言葉は、彼女の心を傷つけずにはおかないだろう",
    ],
    questions: [
      {
        id: "18-1",
        content: "彼のカリスマ性は、聴衆の心をつかま___だろう",
        answers: [
          "ずにはおかない",
          "ずにはいられない",
          "ざるをえない",
          "ないわけにはいかない",
        ],
        correctAnswer: 0,
        memo: [
          "ずにはおかない: 'Nhất định sẽ...'. Diễn tả sự chắc chắn rằng Karisma của anh ấy nhất định sẽ gây ảnh hưởng mạnh mẽ đến khán giả (ngôi thứ ba). (Đúng)",
          "ずにはいられない: 'Không thể kìm được' (chỉ cảm xúc của chính người nói), không dùng cho sự ảnh hưởng đến người khác.",
          "ざるをえない: 'Buộc phải làm...', không phù hợp.",
          "ないわけにはいかない: 'Không thể không làm...', không phù hợp.",
        ],
      },
      {
        id: "18-2",
        content: "彼の冗談を聞いて、笑わ___。",
        answers: [
          "ずにはいられない",
          "ざるをえない",
          "ないわけにはいかない",
          "ずにはおかない",
        ],
        correctAnswer: 0,
        memo: [
          "ずにはいられない: 'Không thể kìm được'. Diễn tả cảm xúc tự nhiên, không thể kiềm chế của bản thân (không thể nhịn cười). (Đúng)",
          "ざるをえない: 'Buộc phải làm...', không phù hợp.",
          "ないわけにはいかない: 'Không thể không làm...', không phù hợp.",
          "ずにはおかない: Dùng để chỉ sự ảnh hưởng đến người khác, không phải cảm xúc của bản thân.",
        ],
      },
      {
        id: "18-3",
        content: "上司の命令なので、出張に行か___。",
        answers: [
          "ずにいる",
          "ざるをえない",
          "ずにはおかない",
          "ないわけにはいかない",
        ],
        correctAnswer: 1,
        memo: [
          "ずにいる: 'Không làm V mà vẫn...', không phù hợp.",
          "ざるをえない: 'Buộc phải làm/Đành phải'. Vì là mệnh lệnh của cấp trên nên không muốn cũng phải đi công tác. (Đúng)",
          "ずにはおかない: 'Nhất định sẽ...', không phù hợp.",
          "ないわけにはいかない: 'Không thể không làm... (vì lý do xã hội, đạo đức)'. Cũng có thể dùng, nhưng ざるをえない nhấn mạnh sự bắt buộc, không có lựa chọn hơn.",
        ],
      },
    ],
  },
  {
    front: "～たらどんなに…か",
    back: [
      "✨ Nếu... thì sẽ... biết bao/Ước gì (Thể hiện cảm xúc mạnh mẽ, mong muốn điều gì xảy ra, thường là điều khó xảy ra)",
      "・Ví dụ: Nếu tôi có thể hiểu được cảm xúc của người đó thì tốt biết mấy",
      "📌 Diễn tả cảm xúc tột độ đối với một giả định không có thực hoặc khó xảy ra",
    ],
    more: [
      "🧩 Vたら / Nなら + どんなに + Vる/Aい + か/だろうか",
      "⚖️ ～ばいいのに (chỉ là ước muốn nhẹ nhàng hơn)",
      "💬 Văn nói, dùng để bày tỏ cảm xúc, ước muốn mạnh mẽ.",
      "📝 ví dụ",
      "・あの人の気持ちがわかったらどんなにいいか",
      "・昔の親友に再会できたらどんなにうれしいか",
    ],
    questions: [
      {
        id: "19-1",
        content: "もう一度、学生時代に戻れ___楽しいか",
        answers: ["たとしても", "たらどんなに", "たらいいのに", "たところで"],
        correctAnswer: 1,
        memo: [
          "たとしても: 'Cho dù...', không phù hợp.",
          "たらどんなに: 'Nếu... thì sẽ... biết bao'. Thể hiện ước muốn mạnh mẽ về một điều khó xảy ra (quay lại thời học sinh) và cảm xúc tột độ (vui vẻ biết bao). (Đúng)",
          "たらいいのに: 'Ước gì...' (mong muốn nhẹ nhàng hơn).",
          "たところで: 'Dù có làm... cũng vô ích', không phù hợp.",
        ],
      },
      {
        id: "19-2",
        content: "もっと早くこの方法を知っていれ___。",
        answers: ["ばよかった", "ばどんなに", "ばいいのに", "ばならない"],
        correctAnswer: 0,
        memo: [
          "ばよかった: 'Giá mà... thì đã tốt'. Diễn tả sự hối tiếc về một việc đã không làm trong quá khứ. (Đúng)",
          "ばどんなに: Sai cấu trúc.",
          "ばいいのに: 'Ước gì...' (dùng cho hiện tại hoặc tương lai).",
          "ばならない: 'Phải làm...'.",
        ],
      },
      {
        id: "19-3",
        content: "もっと時間があれ___。",
        answers: ["ばいいのに", "ばよかった", "ばどんなに", "ばならない"],
        correctAnswer: 0,
        memo: [
          "ばいいのに: 'Ước gì/Giá mà...'. Thể hiện sự tiếc nuối hoặc mong muốn một điều trái với hiện thực. (Đúng)",
          "ばよかった: Dùng cho sự hối tiếc trong quá khứ.",
          "ばどんなに: Sai cấu trúc.",
          "ばならない: 'Phải làm...'.",
        ],
      },
    ],
  },
  {
    front: "～ぬまに",
    back: [
      "✨ Trong khi.../Trong lúc... (Trong lúc chưa xảy ra/chưa nhận thấy A thì làm nhanh B)",
      "・Ví dụ: Trong lúc mẹ không để ý, thằng bé đã ăn vụng chiếc bánh ngọt",
      "📌 Thể hiện hành động B được thực hiện ngay lập tức hoặc thầm lặng trong trạng thái không rõ ràng/chưa nhận thấy của A.",
    ],
    more: [
      "🧩 「ない」 → 「ぬ」 + 間に（まに） (chỉ dùng với một số động từ cố định)",
      "⚖️ ～ないうちに (cũng là 'trong khi chưa...', nhưng ぬまに trang trọng hơn và nhấn mạnh yếu tố bí mật/không nhận thấy)",
      "💬 Văn viết, trang trọng.",
      "📝 ví dụ",
      "・母親が目を離すぬまに、子供はお菓子をこっそり食べた",
      "・若く、経験がないぬまに、もっと多くのことにチャレンジするべきだ",
    ],
    questions: [
      {
        id: "20-1",
        content: "知らない___、季節はすっかり春になっていた",
        answers: ["うちに", "ところだ", "あいだに", "ぬまに"],
        correctAnswer: 3,
        memo: [
          "うちに: 'Trong khi...' (khi trạng thái A còn đang tiếp diễn), không nhấn mạnh yếu tố 'bí mật/chưa nhận thấy' mạnh bằng ぬまに.",
          "ところだ: 'Đúng lúc...', không phù hợp.",
          "あいだに: 'Trong suốt khoảng thời gian...', không phù hợp.",
          "ぬまに: 'Trong khi chưa nhận ra'. Thể hiện sự thay đổi trạng thái xảy ra một cách thầm lặng, không rõ ràng (chưa kịp nhận ra thì mùa đã sang xuân). (Đúng)",
        ],
      },
      {
        id: "20-2",
        content: "雨が降らない___、早く帰りましょう。",
        answers: ["うちに", "あいだに", "ぬまに", "まえに"],
        correctAnswer: 0,
        memo: [
          "うちに: 'Trong khi chưa...'. Hành động 'về nhà' nên được thực hiện trước khi trạng thái thay đổi (trước khi trời mưa). (Đúng)",
          "あいだに: 'Trong suốt khoảng thời gian...', không phù hợp.",
          "ぬまに: Quá trang trọng và thường mang ý 'lén lút, không ai biết'.",
          "まえに: 'Trước khi', cũng đúng nhưng うちに nhấn mạnh hơn việc tranh thủ làm khi điều kiện còn cho phép.",
        ],
      },
      {
        id: "20-3",
        content: "忘れない___、メモしておこう。",
        answers: ["うちに", "ところだ", "あいだに", "ぬまに"],
        correctAnswer: 0,
        memo: [
          "うちに: 'Trong khi chưa...'. Hành động 'ghi chú' nên được thực hiện trước khi trạng thái thay đổi (trước khi quên). (Đúng)",
          "ところだ: 'Đúng lúc...', không phù hợp.",
          "あいだに: 'Trong suốt khoảng thời gian...', không phù hợp.",
          "ぬまに: Quá trang trọng và không phù hợp với ngữ cảnh này.",
        ],
      },
    ],
  },
  {
    front: "～からとおもって",
    back: [
      "✨ Vì nghĩ rằng... (Là lý do cho một hành động nào đó, thường là tiêu cực hoặc có kết quả không tốt)",
      "・Ví dụ: Vì nghĩ rằng còn nhiều thời gian, nên tôi đã lơ là việc chuẩn bị",
      "📌 Biểu thị lý do mang tính suy đoán chủ quan của người nói, dẫn đến hành động thiếu cẩn trọng và thường có kết quả không mong muốn/tiêu cực.",
    ],
    more: [
      "🧩 V / Aい / Na / N + だ + からとおもって",
      "⚖️ ～ので (chỉ lý do khách quan, còn からとおもって nhấn mạnh suy nghĩ chủ quan dẫn đến sai lầm)",
      "💬 Văn nói, dùng để biện minh cho hành động thiếu cẩn trọng.",
      "📝 ví dụ",
      "・まだ時間があるからとおもって、準備を怠ってしまった",
      "・ちょっとしたミスだからとおもって報告しなかったら、大きな問題になった",
    ],
    questions: [
      {
        id: "21-1",
        content:
          "少しぐらい遅れても大丈夫だ___、急がなかったら、電車に乗り遅れた",
        answers: ["からこそ", "からとおもって", "のおかげで", "によって"],
        correctAnswer: 1,
        memo: [
          "からこそ: 'Chính vì...', nhấn mạnh lý do tích cực, không phù hợp.",
          "からとおもって: 'Vì nghĩ rằng...'. Vì suy đoán chủ quan mà dẫn đến hành động sai lầm (không vội) và kết quả tiêu cực (trễ tàu). (Đúng)",
          "のおかげで: 'Nhờ có...' (thường là tích cực), không phù hợp.",
          "によって: 'Tùy theo/Bằng cách...', không phù hợp.",
        ],
      },
      {
        id: "21-2",
        content: "病気だ___、学校を休むのは許されない。",
        answers: ["からこそ", "とばかりに", "からといって", "からとおもって"],
        correctAnswer: 2,
        memo: [
          "からこそ: 'Chính vì...', không phù hợp.",
          "とばかりに: 'Cứ như là...', không phù hợp.",
          "からといって: 'Cho dù nói là... cũng không hẳn'. Dùng để phủ định một kết luận quá đơn giản. (Cho dù nói là bị bệnh cũng không được phép nghỉ học). (Đúng)",
          "からとおもって: 'Vì nghĩ rằng...', không phù hợp.",
        ],
      },
      {
        id: "21-3",
        content: "努力した___、必ず成功するとは限らない。",
        answers: ["とあって", "からといって", "によって", "からとおもって"],
        correctAnswer: 1,
        memo: [
          "とあって: 'Vì là... (hoàn cảnh đặc biệt)', không phù hợp.",
          "からといって: 'Cho dù nói là... cũng không hẳn'. Dùng để phủ định một kết luận quá đơn giản. (Cho dù nói là đã nỗ lực cũng chưa chắc thành công). (Đúng)",
          "によって: 'Tùy theo/Bằng cách...', không phù hợp.",
          "からとおもって: 'Vì nghĩ rằng...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～かとおもえば...も",
    back: [
      "✨ Vừa mới... đã lại.../Vừa A xong thì ngay lập tức B (Thể hiện sự thay đổi liên tục, nhanh chóng, thường là sự đối lập)",
      "・Ví dụ: Đứa bé vừa mới khóc xong thì đã lập tức cười",
      "📌 Diễn tả sự thay đổi trạng thái hoặc hành động nhanh chóng, bất ngờ, thường là sự đối lập hoặc luân phiên.",
    ],
    more: [
      "🧩 Vた + かと思えば / かと思ったら",
      "⚖️ ～とたんに (chỉ sự thay đổi tức thì, nhưng かと思えば nhấn mạnh sự đối lập và luân phiên)",
      "💬 Văn nói, diễn tả sự thay đổi nhanh chóng, luân phiên.",
      "📝 ví dụ",
      "・あの赤ちゃんは泣いたかとおもえば、すぐ笑い出す",
      "・さっきまで晴れていたかとおもえば、急に雨が降り出した",
    ],
    questions: [
      {
        id: "22-1",
        content: "部長は怒鳴った___、次の瞬間には穏やかに話していた",
        answers: ["とたんに", "かとおもえば", "が早いか", "やいなや"],
        correctAnswer: 1,
        memo: [
          "とたんに: 'Ngay sau khi', dùng cho hành động B xảy ra tức thì sau A (ít nhấn mạnh sự đối lập).",
          "かとおもえば: 'Vừa mới... đã lại...'. Diễn tả sự thay đổi trạng thái đối lập (từ la hét sang ôn tồn) một cách nhanh chóng, bất ngờ. (Đúng)",
          "が早いか: 'Ngay sau khi', nhấn mạnh hành động bản năng, lặp lại.",
          "やいなや: 'Ngay sau khi', trang trọng, dùng cho hành động bất ngờ, mang tính khách quan.",
        ],
      },
      {
        id: "22-2",
        content: "ドアを開けた___、猫が飛び出してきた。",
        answers: ["やいなや", "とたんに", "なり", "かとおもえば"],
        correctAnswer: 1,
        memo: [
          "やいなや: Trang trọng, thường dùng cho sự kiện.",
          "とたんに: 'Ngay sau khi'. Diễn tả một sự thay đổi, một hành động bất ngờ xảy ra ngay sau hành động trước. (Đúng)",
          "なり: Thường dùng cho hành động bất ngờ của một người.",
          "かとおもえば: Nhấn mạnh sự đối lập, luân phiên.",
        ],
      },
      {
        id: "22-3",
        content: "チャイムが鳴る___、生徒たちは教室を飛び出した。",
        answers: ["やいなや", "とたんに", "が早いか", "かとおもえば"],
        correctAnswer: 2,
        memo: [
          "やいなや: Trang trọng, dùng cho sự kiện.",
          "とたんに: Nhấn mạnh sự thay đổi đột ngột.",
          "が早いか: 'Ngay sau khi'. Nhấn mạnh tính tức thì và hành động mang tính bản năng, tập thể (học sinh ùa ra khỏi lớp). (Đúng)",
          "かとおもえば: Nhấn mạnh sự đối lập, luân phiên.",
        ],
      },
    ],
  },
  {
    front: "～といっても間違いない",
    back: [
      "✨ Nói là... thì không sai (Nhấn mạnh sự thật/mức độ gần như tuyệt đối, mang tính khẳng định)",
      "・Ví dụ: Cô ấy là người thành công nhất trong công ty, nói là 'thiên tài' thì không sai",
      "📌 Khẳng định một sự thật/đặc điểm là hoàn toàn chính xác, không cần phải nghi ngờ. Dùng để phóng đại sự thật",
    ],
    more: [
      "🧩 V / Aい / Na / N + といっても間違いない",
      "⚖️ ～といっても過言ではない (cũng là 'nói là... không quá lời', mạnh tương đương)",
      "💬 Văn nói và viết, dùng để khẳng định mạnh mẽ, phóng đại sự thật.",
      "📝 ví dụ",
      "・彼女は社内で最も成功した人だ。天才といっても間違いない",
      "・この車は最後の限定モデルであり、傑作といっても間違いない",
    ],
    questions: [
      {
        id: "23-1",
        content: "彼はチームの心臓だ。リーダー___",
        answers: [
          "というわけだ",
          "といっても間違いない",
          "にすぎない",
          "であれ",
        ],
        correctAnswer: 1,
        memo: [
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
          "といっても間違いない: 'Nói là... thì không sai'. Khẳng định mạnh mẽ rằng anh ấy chính là người dẫn đầu (Leader), không cần nghi ngờ. (Đúng)",
          "にすぎない: 'Chỉ là...', không phù hợp.",
          "であれ: 'Dù là...', không phù hợp.",
        ],
      },
      {
        id: "23-2",
        content: "この技術は、世界を変える発明___",
        answers: [
          "といっても過言ではない",
          "ということだ",
          "にしては",
          "にかぎりだ",
        ],
        correctAnswer: 0,
        memo: [
          "といっても過言ではない: 'Nói là... thì không quá lời'. Khẳng định mạnh mẽ về mức độ lớn lao của phát minh này. (Đúng)",
          "ということだ: 'Có nghĩa là...', không phù hợp.",
          "にしては: 'Mặc dù...', không phù hợp.",
          "にかぎりだ: 'Vô cùng...', không phù hợp.",
        ],
      },
      {
        id: "23-3",
        content: "彼の努力は想像を絶する。まさに努力の化身___。",
        answers: [
          "にすぎない",
          "といっても過言ではない",
          "といっても間違いない",
          "にほかならない",
        ],
        correctAnswer: 3,
        memo: [
          "にすぎない: 'Chỉ là...', không phù hợp.",
          "といっても過言ではない: 'Nói là... thì không quá lời', cũng đúng.",
          "といっても間違いない: 'Nói là... thì không sai', cũng đúng.",
          "にほかならない: 'Chính là/Không gì khác là...'. Khẳng định một cách chắc chắn và tuyệt đối rằng anh ấy chính là hiện thân của sự nỗ lực. Phù hợp nhất với まさに. (Đúng)",
        ],
      },
    ],
  },
  {
    front: "～にいわせれば",
    back: [
      "✨ Theo ý kiến của.../Nếu để... nói (Trích dẫn quan điểm của một người/nhóm người nào đó)",
      "・Ví dụ: Theo ý kiến của các chuyên gia thì biện pháp này là chưa đủ",
      "📌 Trích dẫn ý kiến mang tính chủ quan hoặc đánh giá của một người/nhóm người. Thường dùng cho các chủ thể có thẩm quyền.",
    ],
    more: [
      "🧩 N + にいわせれば",
      "⚖️ ～によると (chỉ nguồn thông tin khách quan, còn にいわせれば nhấn mạnh ý kiến/quan điểm cá nhân)",
      "💬 Văn nói và viết.",
      "📝 ví dụ",
      "・専門家にいわせれば、この対策はまだ十分ではないそうだ",
      "・彼にいわせれば、できないことは何もないらしい",
    ],
    questions: [
      {
        id: "24-1",
        content: "ベテランの職人___、この作品にはまだ改善の余地があるそうだ",
        answers: ["によれば", "によると", "にいわせれば", "にとっては"],
        correctAnswer: 2,
        memo: [
          "によれば: 'Theo...' (trích dẫn nguồn thông tin khách quan/công cộng), ít nhấn mạnh quan điểm cá nhân/đánh giá chủ quan.",
          "によると: 'Theo...' (trích dẫn nguồn thông tin khách quan/công cộng), ít nhấn mạnh quan điểm cá nhân/đánh giá chủ quan.",
          "にいわせれば: 'Theo ý kiến của...'. Trích dẫn quan điểm/đánh giá chủ quan của người có chuyên môn (ベテランの職人) về chất lượng tác phẩm. (Đúng)",
          "にとっては: 'Đối với...', không phù hợp.",
        ],
      },
      {
        id: "24-2",
        content: "天気予報___、明日は雨が降るそうだ。",
        answers: ["にとって", "にしてみれば", "によると", "にいわせれば"],
        correctAnswer: 2,
        memo: [
          "にとって: 'Đối với...', không phù hợp.",
          "にしてみれば: 'Nếu xét theo quan điểm của...', không phù hợp.",
          "によると: 'Theo...'. Dùng để trích dẫn nguồn thông tin khách quan như dự báo thời tiết. (Đúng)",
          "にいわせれば: Dùng để trích dẫn ý kiến, đánh giá chủ quan.",
        ],
      },
      {
        id: "24-3",
        content: "私___、この問題は非常に重要だ。",
        answers: ["によれば", "にいわせれば", "によると", "にとっては"],
        correctAnswer: 3,
        memo: [
          "によれば: 'Theo...' (nguồn thông tin khách quan), không phù hợp.",
          "にいわせれば: 'Theo ý kiến của tôi...'.",
          "によると: 'Theo...' (nguồn thông tin khách quan), không phù hợp.",
          "にとっては: 'Đối với tôi...'. Diễn tả tầm quan trọng, sự ảnh hưởng của vấn đề đối với người nói. (Đúng)",
        ],
      },
    ],
  },
  {
    front: "～でなくてなんだろう",
    back: [
      "✨ Không phải... thì là gì/Chính là... (Cách nói nhấn mạnh, khẳng định chắc chắn điều gì đó, thường là những danh từ trừu tượng)",
      "・Ví dụ: Sự cống hiến quên mình vì gia đình đó, không phải là tình yêu thì là gì?",
      "📌 Dùng để khẳng định một cách mạnh mẽ rằng sự vật/sự việc là N, không còn cách giải thích nào khác.",
    ],
    more: [
      "🧩 N + でなくてなんだろう",
      "⚖️ ～にほかならない (cũng là 'chính là', nhưng でなくてなんだろう mang tính cảm thán, nhấn mạnh ý kiến cảm xúc của người nói hơn).",
      "💬 Văn viết, trang trọng, mang tính hùng biện, cảm thán mạnh mẽ.",
      "📝 ví dụ",
      "・家族のために尽くすその姿は、愛でなくてなんだろう",
      "・偶然の出来事が重なった。これは運命でなくてなんだろう",
    ],
    questions: [
      {
        id: "25-1",
        content: "命がけで他人を助けたその行為は、勇気___",
        answers: [
          "にほかならない",
          "でなくてなんだろう",
          "にすぎない",
          "というわけだ",
        ],
        correctAnswer: 1,
        memo: [
          "にほかならない: 'Chính là...' (khẳng định mạnh mẽ, ít cảm thán hơn).",
          "でなくてなんだろう: 'Không phải... thì là gì/Chính là...'. Khẳng định mạnh mẽ và cảm thán rằng hành động đó chính là Lòng Dũng Cảm (勇気). (Đúng)",
          "にすぎない: 'Chỉ là...', không phù hợp.",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
        ],
      },
      {
        id: "25-2",
        content: "この成功は、チーム全員の努力の結果___。",
        answers: [
          "にほかならない",
          "でなくてなんだろう",
          "にすぎない",
          "というわけだ",
        ],
        correctAnswer: 0,
        memo: [
          "にほかならない: 'Chính là/Không gì khác là...'. Khẳng định một cách chắc chắn, mang tính kết luận rằng thành công này là kết quả của nỗ lực. (Đúng)",
          "でなくてなんだろう: 'Không phải... thì là gì'. Quá cảm thán cho một câu kết luận khách quan.",
          "にすぎない: 'Chỉ là...', không phù hợp.",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
        ],
      },
      {
        id: "25-3",
        content: "彼が言っていることは、単なる言い訳___。",
        answers: [
          "にほかならない",
          "にすぎない",
          "というわけだ",
          "でなくてなんだろう",
        ],
        correctAnswer: 1,
        memo: [
          "にほかならない: 'Chính là...'. Quá mạnh, mang tính khẳng định tích cực.",
          "にすぎない: 'Chỉ là/Không hơn không kém'. Dùng để đánh giá thấp, cho rằng điều đó không có gì to tát (chỉ là lời bào chữa). (Đúng)",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
          "でなくてなんだろう: 'Không phải... thì là gì'. Không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～にあっては",
    back: [
      "✨ Trong tình huống/hoàn cảnh... (Thường dùng cho hoàn cảnh đặc biệt, khó khăn hoặc đòi hỏi nghiêm ngặt, mang tính trang trọng)",
      "・Ví dụ: Trong hoàn cảnh thiên tai như thế này, sự hợp tác của mọi người là không thể thiếu",
      "📌 Dùng cho hoàn cảnh đặc biệt, khó khăn (thường là N) để rút ra một nhận định/yêu cầu mang tính trang trọng/nghiêm khắc.",
    ],
    more: [
      "🧩 N + にあっては",
      "⚖️ ～においては (chỉ trong phạm vi/lĩnh vực nào đó, còn にあっては nhấn mạnh tính đặc thù/nghiêm trọng của hoàn cảnh)",
      "💬 Văn viết, rất trang trọng.",
      "📝 ví dụ",
      "・このような天災にあっては、皆の協力が不可欠だ",
      "・この緊急事態にあっては、一刻一秒が惜しい",
    ],
    questions: [
      {
        id: "26-1",
        content: "未曾有の危機___、冷静な判断が求められる",
        answers: ["について", "において", "にあたって", "にあっては"],
        correctAnswer: 3,
        memo: [
          "について: 'Về vấn đề...', không phù hợp.",
          "において: 'Trong lĩnh vực/ở nơi...', không nhấn mạnh hoàn cảnh đặc biệt/khó khăn.",
          "にあたって: 'Nhân dịp/Khi bắt đầu...', không phù hợp.",
          "にあっては: 'Trong hoàn cảnh...'. Dùng cho hoàn cảnh đặc biệt, khó khăn (khủng hoảng chưa từng có) để đưa ra yêu cầu nghiêm ngặt (cần phán đoán bình tĩnh). (Đúng)",
        ],
      },
      {
        id: "26-2",
        content:
          "グローバル化が進む現代社会___、国際感覚を身につけることは不可欠だ。",
        answers: ["にあって", "にあたって", "において", "について"],
        correctAnswer: 2,
        memo: [
          "にあって: 'Trong hoàn cảnh...' (nhấn mạnh tính đặc thù, khó khăn).",
          "にあたって: 'Nhân dịp/Khi bắt đầu...', không phù hợp.",
          "において: 'Trong/Ở lĩnh vực/phạm vi...'. Dùng để chỉ bối cảnh, phạm vi rộng (trong xã hội hiện đại). Phù hợp nhất. (Đúng)",
          "について: 'Về vấn đề...', không phù hợp.",
        ],
      },
      {
        id: "26-3",
        content: "開会___、一言ご挨拶申し上げます。",
        answers: ["において", "にあって", "にあたり", "について"],
        correctAnswer: 2,
        memo: [
          "において: 'Trong lĩnh vực/ở nơi...', không phù hợp.",
          "にあって: 'Trong hoàn cảnh...', không phù hợp.",
          "にあたり: 'Nhân dịp/Khi bắt đầu...'. Dùng trong các dịp trang trọng, nghi thức để bắt đầu một hành động. (Đúng)",
          "について: 'Về vấn đề...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～といったところだ",
    back: [
      "✨ Đại khái là/Chừng đó là cùng (Thể hiện mức độ tối đa, nhưng ở mức thấp hoặc trung bình, mang tính khiêm tốn)",
      "・Ví dụ: Tiền lương một tháng đại khái là 20 man là cùng",
      "📌 Đưa ra con số, mức độ hoặc phạm vi tối đa nhưng lại mang ý nghĩa không lớn/không đáng kể/chỉ đến thế mà thôi.",
    ],
    more: [
      "🧩 N / Vる + といったところだ",
      "⚖️ ～ぐらい/ほどだ (chỉ mức độ thông thường, といったところだ nhấn mạnh mức độ tối đa nhưng không cao)",
      "💬 Văn nói và viết, mang tính khiêm tốn hoặc đánh giá mức độ thấp.",
      "📝 ví dụ",
      "・一ヶ月の収入は20万円といったところだ",
      "・講義の内容は6割理解できたといったところだ",
    ],
    questions: [
      {
        id: "27-1",
        content: "今年のボーナスは、去年の半分___",
        answers: [
          "にすぎない",
          "にほかならない",
          "といったところだ",
          "というわけだ",
        ],
        correctAnswer: 2,
        memo: [
          "にすぎない: 'Chỉ là/Không hơn không kém' (thường dùng cho số ít, đơn giản, mang tính phủ định).",
          "にほかならない: 'Chính là...', không phù hợp.",
          "といったところだ: 'Đại khái là/Chừng đó là cùng'. Đưa ra mức độ (một nửa năm ngoái) và ngụ ý mức độ đó là tối đa, không đáng kể. (Đúng)",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
        ],
      },
      {
        id: "27-2",
        content: "このプロジェクトの進捗は、まだ全体の2割___。",
        answers: [
          "にほかならない",
          "にすぎない",
          "といったところだ",
          "というわけだ",
        ],
        correctAnswer: 1,
        memo: [
          "にほかならない: 'Chính là...', không phù hợp.",
          "にすぎない: 'Chỉ là/Không hơn không kém'. Nhấn mạnh mức độ thấp, không đáng kể (chỉ mới 20% toàn bộ dự án). Phù hợp nhất. (Đúng)",
          "といったところだ: 'Chừng đó là cùng'. Cũng có thể dùng, nhưng にすぎない nhấn mạnh sự hạn chế, ít ỏi hơn.",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
        ],
      },
      {
        id: "27-3",
        content: "彼が話せる外国語は、英語とフランス語少々___",
        answers: [
          "にすぎない",
          "というわけだ",
          "といったところだ",
          "にほかならない",
        ],
        correctAnswer: 2,
        memo: [
          "にすぎない: 'Chỉ là...', không phù hợp.",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
          "といったところだ: 'Đại khái là/Chừng đó là cùng'. Liệt kê phạm vi tối đa các ngôn ngữ có thể nói (Tiếng Anh và một chút tiếng Pháp) và ngụ ý là không nhiều. (Đúng)",
          "にほかならない: 'Chính là...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～とあって",
    back: [
      "✨ Vì/Do (Là lý do đặc biệt nên kết quả là một trạng thái đặc biệt)",
      "・Ví dụ: Vì là Giáng sinh nên khắp phố đều tấp nập",
      "📌 Đưa ra một lý do đặc biệt (N, Na) và kết quả là một tình trạng đặc trưng hoặc khác thường.",
    ],
    more: [
      "🧩 N / Na + とあって",
      "⚖️ ～だけあって (cũng là 'vì', nhưng だけあって nhấn mạnh sự xứng đáng, còn とあって nhấn mạnh sự đặc trưng của hoàn cảnh)",
      "💬 Văn viết, trang trọng, thường dùng trong báo chí.",
      "📝 ví dụ",
      "・クリスマスとあって、街はにぎやかだ",
      "・経験者とあって、彼女の仕事ぶりは見事だ",
    ],
    questions: [
      {
        id: "28-1",
        content: "連休の初日___、高速道路は渋滞している",
        answers: ["ならではの", "ならでは", "とあって", "のおかげで"],
        correctAnswer: 2,
        memo: [
          "ならではの: 'Chỉ có ở...' (đi kèm danh từ), không phù hợp.",
          "ならでは: 'Chỉ có ở...' (kết thúc câu), không phù hợp.",
          "とあって: 'Vì là...'. Vì là lý do đặc biệt (Ngày đầu tiên của kỳ nghỉ dài) nên dẫn đến trạng thái đặc trưng (đường cao tốc bị tắc nghẽn). (Đúng)",
          "のおかげで: 'Nhờ có...' (thường là tích cực), không phù hợp.",
        ],
      },
      {
        id: "28-2",
        content: "一流ホテルで働くスタッフ___、接客マナーは完璧だ",
        answers: ["だけあって", "とあって", "ならでは", "というものだ"],
        correctAnswer: 0,
        memo: [
          "だけあって: 'Quả đúng là/Xứng đáng là...'. Nhấn mạnh kết quả (thái độ phục vụ hoàn hảo) là xứng đáng với lý do (làm việc ở khách sạn hạng nhất). (Đúng)",
          "とあって: Chỉ nhấn mạnh sự đặc trưng của hoàn cảnh, không nhấn mạnh tính xứng đáng.",
          "ならでは: 'Chỉ có ở...', không phù hợp.",
          "というものだ: 'Thật là...', không phù hợp.",
        ],
      },
      {
        id: "28-3",
        content: "この景色は、この場所___の美しさだ。",
        answers: ["とあって", "ならでは", "だけあって", "というものだ"],
        correctAnswer: 1,
        memo: [
          "とあって: 'Vì là...', không phù hợp.",
          "ならでは: 'Chỉ có ở/Đặc trưng của...'. Nhấn mạnh vẻ đẹp này là độc đáo, chỉ có ở nơi đây. (Đúng)",
          "だけあって: 'Quả đúng là/Xứng đáng là...', không phù hợp.",
          "というものだ: 'Thật là...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～をものともせずに",
    back: [
      "✨ Bất chấp/Mặc kệ (Làm điều gì đó một cách can đảm, bất chấp trở ngại)",
      "・Ví dụ: Anh ấy bất chấp bệnh tật mà tiếp tục nghiên cứu",
      "📌 Đi kèm với trở ngại, khó khăn (thường là N) và diễn tả hành động can đảm, kiên cường, kết quả thường là tích cực.",
    ],
    more: [
      "🧩 N + をものともせずに",
      "⚖️ ～にもかかわらず (cũng là 'mặc dù', nhưng をものともせずに nhấn mạnh sự kiên cường, bất chấp mạnh mẽ hơn)",
      "💬 Văn viết, trang trọng, mang tính ca ngợi.",
      "📝 ví dụ",
      "・彼は病気をものともせずに研究を続けた",
      "・あらゆる批判をものともせずに、彼女は夢を追い続けた",
    ],
    questions: [
      {
        id: "29-1",
        content: "彼は周囲の冷たい視線___、自分の信念を貫いた",
        answers: ["をものともせずに", "にもかかわらず", "につけ", "にしろ"],
        correctAnswer: 0,
        memo: [
          "をものともせずに: 'Bất chấp...'. Hành động can đảm, kiên cường (giữ vững niềm tin) được thực hiện bất chấp khó khăn (ánh mắt lạnh lùng của người xung quanh). (Đúng)",
          "にもかかわらず: 'Mặc dù...', không nhấn mạnh sự kiên cường, ca ngợi mạnh mẽ như をものともせずに.",
          "につけ: 'Mỗi khi/hễ cứ', không phù hợp.",
          "にしろ: 'Dù là...', không phù hợp.",
        ],
      },
      {
        id: "29-2",
        content: "雨が降っている___、試合は行われた。",
        answers: ["にもかかわらず", "をものともせずに", "にかぎり", "にしろ"],
        correctAnswer: 0,
        memo: [
          "にもかかわらず: 'Mặc dù...'. Diễn tả một sự việc xảy ra trái với điều kiện thông thường (mặc dù trời mưa nhưng trận đấu vẫn diễn ra). (Đúng)",
          "をものともせずに: Quá mạnh, thường dùng cho những trở ngại lớn hơn và hành động mang tính ca ngợi.",
          "にかぎり: 'Chỉ riêng...', không phù hợp.",
          "にしろ: 'Dù là...', không phù hợp.",
        ],
      },
      {
        id: "29-3",
        content: "強い反対___、そのプロジェクトは開始された",
        answers: ["にしろ", "にもかかわらず", "をものともせずに", "にせよ"],
        correctAnswer: 1,
        memo: [
          "にしろ: 'Dù là...', không phù hợp.",
          "にもかかわらず: 'Mặc dù...'. Diễn tả hành động (dự án được bắt đầu) xảy ra bất chấp sự đối lập (sự phản đối mạnh mẽ). (Đúng)",
          "をものともせずに: Thường dùng cho hành động mang tính cá nhân/tập thể cần sự can đảm, kiên cường.",
          "にせよ: 'Dù là...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～が早いか / ～やいなや / ～なり / ～とたんに",
    back: [
      "✨ Ngay sau khi (Diễn tả hành động B xảy ra tức thì sau khi hành động A vừa kết thúc)",
      "・Ví dụ: Vừa nghe chuông kết thúc, học sinh đã chạy ra khỏi lớp.",
      "📌 Nhấn mạnh tính tức thì, không có khoảng cách thời gian.",
    ],
    more: [
      "🧩 Vる / Vた + が早いか / やいなや / なり / とたんに",
      "⚖️",
      " * が早いか: Nhấn mạnh hành động bản năng, lặp lại. (Vる/Vた)",
      " * やいなや: Trang trọng, hành động bất ngờ. (Vる/Vた)",
      " * なり: Hành động bất ngờ, chủ ngữ duy nhất. (Vる)",
      " * とたんに: Thay đổi đột ngột (thường dùng cho hiện tượng tự nhiên). (Vる/Vた)",
      "💬 Cả văn nói và viết (trừ とたんに phổ biến hơn trong văn nói).",
      "📝 ví dụ",
      "・チャイムが鳴るが早いか、生徒たちは教室を飛び出した",
      "・総理大臣が演説を終えるやいなや、会場は大きな拍手に包まれた",
      "・彼は「行くぞ」と言ったなり、車の鍵を手に取った",
      "・夫は出張から帰ってきたとたんに、スーツケースを放り出すと寝室へ向かった",
    ],
    questions: [
      {
        id: "30-1",
        content: "ドアを開け___、猫が飛び出してきた。",
        answers: ["とたんに", "が早いか", "につれて", "ところだ"],
        correctAnswer: 0,
        memo: [
          "とたんに: 'Ngay sau khi'. Diễn tả một sự thay đổi, một hành động bất ngờ xảy ra ngay sau hành động trước. (Đúng)",
          "が早いか: Thường dùng cho hành động có chủ ý, mang tính bản năng của con người.",
          "につれて: 'Cùng với sự thay đổi của...', không phù hợp.",
          "ところだ: 'Đúng lúc...', không phù hợp.",
        ],
      },
      {
        id: "30-2",
        content: "総理大臣が演説を終える___、会場は大きな拍手に包まれた",
        answers: ["やいなや", "つつ", "なり", "はする"],
        correctAnswer: 0,
        memo: [
          "やいなや: 'Ngay sau khi'. Dùng trong văn viết, trang trọng và chỉ sự việc khách quan, bất ngờ (diễn thuyết kết thúc thì hội trường vỗ tay). Rất phù hợp. (Đúng)",
          "つつ: 'Vừa... vừa...' (đồng thời), không phù hợp.",
          "なり: Thường dùng cho hành động bất ngờ của cá nhân.",
          "はする: 'Có làm nhưng...' (nhượng bộ), không phù hợp.",
        ],
      },
      {
        id: "30-3",
        content: "彼は電話を切る___、部屋を飛び出していった。",
        answers: ["が早いか", "なり", "ところだ", "とたんに"],
        correctAnswer: 1,
        memo: [
          "が早いか: Cũng có thể dùng, nhưng なり nhấn mạnh hơn hành động bất ngờ, khó đoán của một cá nhân.",
          "なり: 'Ngay sau khi'. Diễn tả hành động B (lao ra khỏi phòng) xảy ra một cách bất ngờ, ngay sau hành động A (cúp máy), chủ ngữ là một người. (Đúng)",
          "ところだ: 'Đúng lúc...', không phù hợp.",
          "とたんに: Ít dùng cho hành động có chủ ý mạnh mẽ như 'lao ra khỏi phòng'.",
        ],
      },
    ],
  },
];

export default cards;
