import {
  FlashCard,
  FlashCardItem,
} from "@/shared/component/flash-card/flash-card";

const cards: FlashCardItem[] = [
  {
    front: "～がてら",
    back: [
      "- Ý nghĩa: Nhân tiện (làm A nhân tiện làm B)",
      "・Đi dạo nhân tiện ghé cửa hàng",
      "・Leo núi nhân tiện chụp ảnh",
      "- Key point: Hành động chính kèm phụ, thường có di chuyển",
      "- Cấu trúc: N / Vます + がてら",
      "- So sánh: ～ついでに (không nhấn yếu tố di chuyển)",
    ],
    more: [
      "- Ví dụ 1: 散歩がてらコンビニに寄った。",
      "- Ví dụ 2: 写真を撮りがてら山を登った。",
      "💡 Mẹo nhớ:",
      "  ・が (nhấn hành động chính) + てら (cùng lúc)",
      "  ・Hình ảnh: Đi MỘT đường làm HAI việc 🚶‍♂️➕🛒",
      "❌ Sai: 勉強がてら図書館にいる (không có động từ di chuyển)",
      "✅ Đúng: 図書館へ行きがてら本を返す",
    ],
    question: {
      id: "1",
      content: "Điền: 昼ごはんを食べ___郵便局に寄った。",
      correctAnswer: 1,
      answers: ["ながら", "がてら", "ついでに", "うちに"],
    },
  },
  {
    front: "～なり",
    back: [
      "- Ý nghĩa: Vừa mới... thì lập tức...",
      "・Vừa ngồi xuống đã ngủ",
      "・Vừa mở cửa thì trẻ lao ra",
      "- Key point: Hai hành động nối tiếp ngay tức khắc",
      "- Cấu trúc: V辞書形 + なり",
      "- So sánh: ～たとたん(に) (gần nghĩa, phổ biến hơn)",
    ],
    more: [
      "- Ví dụ 1: 席に着くなり寝てしまった。",
      "- Ví dụ 2: ドアを開けるなり子どもが飛び出した。",
      "💡 Mẹo nhớ:",
      "  ・Domino: A đổ xong → B lập tức",
      "  ・Không có khoảng đệm thời gian",
      "❌ Sai: 席に着くなり、しばらく休んでから勉強した (có khoảng nghỉ)",
      "✅ Đúng: 席に着くなり勉強を始めた",
    ],
    question: {
      id: "2",
      content: "Điền: 先生が教室に入る___学生は静かになった。",
      correctAnswer: 2,
      answers: ["末に", "ところで", "なり", "一方で"],
    },
  },
  {
    front: "～手前",
    back: [
      "- Ý nghĩa: Vì đã/đang làm/nói nên phải giữ thể diện",
      "・Đã hứa nên phải đi",
      "・Đã nói trước mọi người nên không rút lui",
      "- Key point: Tự ràng buộc trách nhiệm / sĩ diện",
      "- Cấu trúc: Vた / Vている / Nの + 手前",
      "- So sánh: ～以上(は) trung tính hơn về trách nhiệm",
    ],
    more: [
      "- Ví dụ 1: 約束した手前、行かないわけにいかない。",
      "- Ví dụ 2: 人前で言った手前、後に引けない。",
      "💡 Mẹo nhớ:",
      "  ・'Trước mặt người khác' → phải giữ lời",
      "❌ Sai: 家で一人で決めた手前、やめられない (không có công khai)",
      "✅ Đúng: 人前で宣言した手前、途中でやめられない",
    ],
    question: {
      id: "3",
      content: "Điền: 公の場で宣言した___、途中でやめられない。",
      correctAnswer: 0,
      answers: ["手前", "わけで", "まで", "次第"],
    },
  },
  {
    front: "～を限りに／～限りで",
    back: [
      "- Ý nghĩa: Kể từ / đến hết (thời điểm) thì dừng",
      "・Từ hôm nay bỏ đồ ngọt",
      "・Dịch vụ kết thúc hết tháng này",
      "- Key point: Tuyên bố chấm dứt hành vi/thói quen",
      "- Cấu trúc: 時間語 + を限りに / 限りで",
      "- So sánh: ～までに chỉ hạn chót, không nhấn dứt bỏ",
    ],
    more: [
      "- Ví dụ 1: 今日を限りに甘い物をやめる。",
      "- Ví dụ 2: 今月限りでサービス終了。",
      "💡 Mẹo nhớ:",
      "  ・限り = vạch giới hạn cuối",
      "❌ Sai: 車を限りに使うのをやめる (danh từ không phải mốc thời gian)",
      "✅ Đúng: 今日を限りに間食をやめる",
    ],
    question: {
      id: "4",
      content: "Điền: 今回___この部署を離れます。",
      correctAnswer: 3,
      answers: ["までに", "ばかりで", "ところで", "限りで"],
    },
  },
  {
    front: "～限りだ",
    back: [
      "- Ý nghĩa: Rất / vô cùng (cực độ cảm xúc)",
      "・Vui biết bao",
      "・Tiếc vô cùng",
      "- Key point: Cảm xúc chủ quan cực mạnh",
      "- Cấu trúc: 感情形容詞 + 限りだ",
      "- So sánh: ～てしかたがない dùng rộng hơn",
    ],
    more: [
      "- Ví dụ 1: うれしい限りだ。",
      "- Ví dụ 2: 残念な限りだ。",
      "💡 Mẹo nhớ:",
      "  ・'Chạm trần' cảm xúc",
      "❌ Sai: 行く限りだ (dùng động từ không phải tính từ cảm xúc)",
      "✅ Đúng: 光栄な限りだ",
    ],
    question: {
      id: "5",
      content: "Điền: 皆に助けられてありがたい___。",
      correctAnswer: 1,
      answers: ["わけだ", "限りだ", "ものだ", "ところだ"],
    },
  },
  {
    front: "～あっての",
    back: [
      "- Ý nghĩa: N2 có được là nhờ N1 (nền tảng)",
      "・Hạnh phúc có được nhờ gia đình",
      "・Quan hệ công việc nhờ sự tin cậy",
      "- Key point: N1 không có thì N2 không tồn tại",
      "- Cấu trúc: N1あってのN2",
      "- So sánh: ～なしでは nhấn thiếu; mẫu này nhấn 'nhờ có'",
    ],
    more: [
      "- Ví dụ 1: 家族あっての私だ。",
      "- Ví dụ 2: 信頼あっての仕事関係。",
      "💡 Mẹo nhớ:",
      "  ・N1 = nền móng, N2 = tòa nhà",
      "❌ Sai: 成功あっての努力 (đảo ngược quan hệ nhân quả)",
      "✅ Đúng: 努力あっての成功",
    ],
    question: {
      id: "6",
      content: "Điền: 健康___成功だと思う。",
      correctAnswer: 2,
      answers: ["限りで", "わけで", "あっての", "ばかりに"],
    },
  },
  {
    front: "～だの～だの",
    back: [
      "- Ý nghĩa: Nào là... nào là... (phàn nàn)",
      "・Lúc kêu nóng lúc kêu lạnh",
      "・Toàn than lương thấp với bận rộn",
      "- Key point: Liệt kê tạp, sắc thái chê trách",
      "- Cấu trúc: N/V/A + だの + N/V/A + だの",
      "- So sánh: ～やら～やら trung tính hơn",
    ],
    more: [
      "- Ví dụ 1: 暑いだの寒いだのとうるさい。",
      "- Ví dụ 2: 忙しいだの給料が安いだの文句ばかりだ。",
      "💡 Mẹo nhớ:",
      "  ・Cặp than phiền nối tiếp",
      "❌ Sai: 忙しいだの (thiếu liệt kê thứ hai)",
      "✅ Đúng: 忙しいだの眠いだの文句ばかり言う",
    ],
    question: {
      id: "7",
      content: "Điền: 忙しい___眠い___って文句ばかり言う。",
      correctAnswer: 0,
      answers: ["だの", "やら", "とか", "し"],
    },
  },
  {
    front: "～であれ～であれ",
    back: [
      "- Ý nghĩa: Dù là... hay... đều (không phân biệt)",
      "・Nam hay nữ đều tham gia được",
      "・Dù tán thành hay phản đối vẫn phải phát biểu",
      "- Key point: Hai khả năng ngang nhau về kết luận",
      "- Cấu trúc: N1であれN2であれ",
      "- So sánh: ～ても / ～にせよ mềm hơn",
    ],
    more: [
      "- Ví dụ 1: 男であれ女であれ参加できる。",
      "- Ví dụ 2: 賛成であれ反対であれ意見を述べて。",
      "💡 Mẹo nhớ:",
      "  ・Hai cực → cùng chung kết luận",
      "❌ Sai: 男である女であれ (hình thức lẫn lộn)",
      "✅ Đúng: 男であれ女であれ平等だ",
    ],
    question: {
      id: "8",
      content: "Điền: 成功___失敗___挑戦する価値がある。",
      correctAnswer: 3,
      answers: ["ながら", "かどうか", "にせよ", "であれ"],
    },
  },
  {
    front: "～どうにも…ない",
    back: [
      "- Ý nghĩa: Không cách nào / hết cách",
      "・Việc đó không xử lý nổi",
      "・Máy hỏng không sửa được",
      "- Key point: Bất lực hoàn toàn",
      "- Cấu trúc: どうにも + Vない / Adjくない",
      "- So sánh: なかなか～ない chỉ khó chứ chưa tuyệt đối",
    ],
    more: [
      "- Ví dụ 1: それはどうにもならない。",
      "- Ví dụ 2: 機械が壊れてどうにも直せない。",
      "💡 Mẹo nhớ:",
      "  ・'Cách nào cũng không'",
      "❌ Sai: どうにも直した (khẳng định)",
      "✅ Đúng: どうにも直せない",
    ],
    question: {
      id: "9",
      content: "Điền: この問題は___ならないと思う。",
      correctAnswer: 1,
      answers: ["なかなか", "どうにも", "めったに", "まったく"],
    },
  },
  {
    front: "～はする",
    back: [
      "- Ý nghĩa: Tuy có làm ... nhưng (kết quả không tương xứng)",
      "・Có học mà điểm không tăng",
      "・Có giúp nhưng chẳng hữu ích",
      "- Key point: Nhấn sự 'có làm' nhưng không đủ",
      "- Cấu trúc: Nはする（が／けど）",
      "- So sánh: ～には～が trung tính hơn",
    ],
    more: [
      "- Ví dụ 1: 勉強はするが成績が上がらない。",
      "- Ví dụ 2: 手伝いはしたが役に立たなかった。",
      "💡 Mẹo nhớ:",
      "  ・'Có làm' + kết quả không như kỳ vọng",
      "❌ Sai: 勉強するが成績が上がらない (thiếu は nhấn)",
      "✅ Đúng: 勉強はするが成績が上がらない",
    ],
    question: {
      id: "10",
      content: "Điền: 運動___するが全然痩せない。",
      correctAnswer: 0,
      answers: ["は", "も", "で", "しか"],
    },
  },
  {
    front: "～ているばあいではない",
    back: [
      "- Ý nghĩa: Không phải lúc để...",
      "・Không phải lúc ngủ",
      "・Không phải lúc chơi",
      "- Key point: Cần ưu tiên việc khác cấp bách",
      "- Cấu trúc: Vている場合ではない",
      "- So sánh: ～ている暇はない nhấn thiếu thời gian",
    ],
    more: [
      "- Ví dụ 1: 寝ている場合ではない。",
      "- Ví dụ 2: 遊んでいる場合ではない。",
      "💡 Mẹo nhớ:",
      "  ・'Tình huống khẩn' loại bỏ hành động đang làm",
      "❌ Sai: 寝る場合ではない (mất sắc thái 'đang')",
      "✅ Đúng: 寝ている場合ではない",
    ],
    question: {
      id: "11",
      content: "Điền: こんなことで泣いて___場合ではない。",
      correctAnswer: 2,
      answers: ["みる", "いる", "いる", "しまう"],
    },
  },
  {
    front: "～なら…なり",
    back: [
      "- Ý nghĩa: Nếu chọn kiểu đó thì làm cho tương xứng",
      "・Nghỉ thì phải có kế hoạch nghỉ",
      "・Làm rẻ thì cần cách phù hợp",
      "- Key point: Đòi hỏi nhất quán, không nửa vời",
      "- Cấu trúc: VるならVるなり / NならNなり",
      "- So sánh: ～なら～で biến thể nhẹ hơn",
    ],
    more: [
      "- Ví dụ 1: 休むなら休むなりの計画がいる。",
      "- Ví dụ 2: 安く済ませるなら済ませるなりの工夫。",
      "💡 Mẹo nhớ:",
      "  ・Lựa chọn → theo chuẩn của lựa chọn đó",
      "❌ Sai: 休むなら勉強なり計画する (không song hành cùng cấu trúc)",
      "✅ Đúng: 休むなら休むなりの準備をしろ",
    ],
    question: {
      id: "12",
      content: "Điền: 行くなら行く___の準備をしてくれ。",
      correctAnswer: 3,
      answers: ["べき", "よう", "だけ", "なり"],
    },
  },
  {
    front: "～わ…わ（で）",
    back: [
      "- Ý nghĩa: Nào là... nào là... (chất chồng)",
      "・Nào bận nào buồn ngủ rất mệt",
      "・Nào mưa nào lạnh không muốn ra ngoài",
      "- Key point: Liệt kê ngập nhiều yếu tố (khẩu ngữ)",
      "- Cấu trúc: VるわNだわで / AdjいわAdjいわで",
      "- So sánh: ～し～し trung tính hơn",
    ],
    more: [
      "- Ví dụ 1: 忙しいわ眠いわで大変だ。",
      "- Ví dụ 2: 雨だわ寒いわで出たくない。",
      "💡 Mẹo nhớ:",
      "  ・'Tràn ngập' cảm giác",
      "❌ Sai: 忙しいわで困る (thiếu liệt kê thứ hai)",
      "✅ Đúng: 忙しいわ眠いわで困る",
    ],
    question: {
      id: "13",
      content: "Điền: 今日は仕事___電話___で休む暇がない。",
      correctAnswer: 2,
      answers: ["し", "とか", "わ", "など"],
    },
  },
  {
    front: "～をいいことに",
    back: [
      "- Ý nghĩa: Lợi dụng (điều thuận lợi / sơ hở)",
      "・Lợi dụng thầy vắng gây ồn",
      "・Lợi dụng lòng tốt để nhờ mãi",
      "- Key point: Hành vi mang sắc thái tiêu cực",
      "- Cấu trúc: N / Sのを + いいことに",
      "- So sánh: ～につけこんで nhấn chen vào điểm yếu",
    ],
    more: [
      "- Ví dụ 1: 先生がいないのをいいことに騒いだ。",
      "- Ví dụ 2: 彼の優しさをいいことに頼み続ける。",
      "💡 Mẹo nhớ:",
      "  ・Biến lợi thế thành cớ làm xấu",
      "❌ Sai: 先生がいるのをいいことに静かに勉強した (không mang nghĩa lợi dụng xấu)",
      "✅ Đúng: 親が留守なのをいいことにゲーム三昧だ",
    ],
    question: {
      id: "14",
      content: "Điền: 親がいないの___夜更かしした。",
      correctAnswer: 1,
      answers: ["わけで", "をいいことに", "ばかりで", "からには"],
    },
  },
  {
    front: "～いざ～となると",
    back: [
      "- Ý nghĩa: Đến khi thật sự (xảy ra) thì khác",
      "・Đến lúc thi thì căng thẳng",
      "・Đến lúc xuất phát lại lo lắng",
      "- Key point: Thay đổi phản ứng trong tình huống thật",
      "- Cấu trúc: いざVるとなると / いざNとなれば",
      "- So sánh: いよいよ chỉ cận kề thời điểm",
    ],
    more: [
      "- Ví dụ 1: いざ本番となると緊張する。",
      "- Ví dụ 2: いざ出発となれば不安になる。",
      "💡 Mẹo nhớ:",
      "  ・'Đến lúc thật' phản ứng đổi",
      "❌ Sai: いざ試験を勉強すると緊張する (cấu trúc sai)",
      "✅ Đúng: いざ試験となると緊張する",
    ],
    question: {
      id: "15",
      content: "Điền: 練習は平気でも、___発表となると緊張する。",
      correctAnswer: 0,
      answers: ["いざ", "ただ", "まさに", "もしくは"],
    },
  },
  {
    front: "～との",
    back: [
      "- Ý nghĩa: Rằng... (tường thuật trang trọng)",
      "・Liên lạc nói rằng anh ấy không tới",
      "・Nhận thông báo nói ngày mai nghỉ",
      "- Key point: Văn viết, truyền đạt thông tin nhận được",
      "- Cấu trúc: S + との + N / S + とのことだ",
      "- So sánh: ～という phổ thông hơn",
    ],
    more: [
      "- Ví dụ 1: 彼が来ないとの連絡。",
      "- Ví dụ 2: 明日休業との通知。",
      "💡 Mẹo nhớ:",
      "  ・と + の: nội dung trích dẫn danh hóa",
      "❌ Sai: 彼が来ないとの言った (kết hợp sai)",
      "✅ Đúng: 彼が来ないとの連絡が入った",
    ],
    question: {
      id: "16",
      content: "Điền: 事故で遅れる___連絡があった。",
      correctAnswer: 1,
      answers: ["という", "との", "だの", "わけの"],
    },
  },
  {
    front: "～てもしかたがない",
    back: [
      "- Ý nghĩa: ... cũng đành / không còn cách",
      "・Thất bại cũng đành chịu",
      "・Giận cũng vô ích",
      "- Key point: Chấp nhận vì không đổi được kết quả",
      "- Cấu trúc: Vても / Adjくても + しかたがない",
      "- So sánh: ～てもしょうがない khẩu ngữ hơn",
    ],
    more: [
      "- Ví dụ 1: 失敗してもしかたがない。",
      "- Ví dụ 2: 怒ってもしかたがない。",
      "💡 Mẹo nhớ:",
      "  ・'Không có cách xử lý'",
      "❌ Sai: 怒るしかたがない (thiếu ても)",
      "✅ Đúng: 怒ってもしかたがない",
    ],
    question: {
      id: "17",
      content: "Điền: 遅れたことを今さら謝って___しかたがない。",
      correctAnswer: 2,
      answers: ["も", "に", "も", "では"],
    },
  },
  {
    front: "～ずにはおかない",
    back: [
      "- Ý nghĩa: Thế nào cũng / chắc chắn sẽ (gây tác động)",
      "・Diễn xuất chắc chắn làm người xem cảm động",
      "・Vấn đề chắc chắn gây tranh luận",
      "- Key point: Tính tất yếu tạo ảnh hưởng",
      "- Cấu trúc: Vない語幹 + ずにはおかない",
      "- So sánh: ～に違いない là phỏng đoán thuần",
    ],
    more: [
      "- Ví dụ 1: 彼の演技は人を感動させずにはおかない。",
      "- Ví dụ 2: その問題は議論を呼ばずにはおかない。",
      "💡 Mẹo nhớ:",
      "  ・'Không thể không gây ra'",
      "❌ Sai: 感動させないではおかない (mẫu sai)",
      "✅ Đúng: 人を驚かせずにはおかない出来事",
    ],
    question: {
      id: "18",
      content: "Điền: その事件は社会を驚かせ___おかないだろう。",
      correctAnswer: 3,
      answers: ["に違いない", "わけではない", "ようでは", "ずには"],
    },
  },
  {
    front: "～たらどんなに…か",
    back: [
      "- Ý nghĩa: Nếu ... thì ... biết mấy (ước vọng)",
      "・Nghỉ được thì nhẹ biết bao",
      "・Gặp được thì vui biết bao",
      "- Key point: Giả định không thật / nuối tiếc",
      "- Cấu trúc: もしVたらどんなにAdj/Advか",
      "- So sánh: ～ばよかった nhấn hối tiếc trực tiếp",
    ],
    more: [
      "- Ví dụ 1: 休めたらどんなに楽か。",
      "- Ví dụ 2: 会えたらどんなにうれしいか。",
      "💡 Mẹo nhớ:",
      "  ・Kết thúc bằng か (câu hỏi tu từ)",
      "❌ Sai: 会えたらどんなにうれしい (thiếu か)",
      "✅ Đúng: 会えたらどんなにうれしいか",
    ],
    question: {
      id: "19",
      content: "Điền: もっと早く知っていた___どんなによかったか。",
      correctAnswer: 1,
      answers: ["わけだ", "ら", "まで", "として"],
    },
  },
  {
    front: "～ぬ間に",
    back: [
      "- Ý nghĩa: Trong lúc chưa...",
      "・Tranh thủ về trước khi trời tối",
      "・Hoàn thành trước khi mưa",
      "- Key point: Trang trọng/cổ, tương đương ないうちに",
      "- Cấu trúc: Vない（ぬ）間に",
      "- So sánh: ～ないうちに phổ biến hiện đại",
    ],
    more: [
      "- Ví dụ 1: 日が暮れぬ間に帰る。",
      "- Ví dụ 2: 雨が降りぬ間に終える。",
      "💡 Mẹo nhớ:",
      "  ・ぬ = ない (cổ) → trang trọng",
      "❌ Sai: 日が暮れない間に帰る (dùng sai sắc thái cổ)",
      "✅ Đúng: 日が暮れぬ間に帰る",
    ],
    question: {
      id: "20",
      content: "Điền: 雨が降り___間に作業を終えよう。",
      correctAnswer: 0,
      answers: ["ぬ", "ない", "ず", "まい"],
    },
  },
  {
    front: "～からとおもって",
    back: [
      "- Ý nghĩa: Vì nghĩ rằng... nên...",
      "・Nghĩ rẻ nên mua nhiều",
      "・Nghĩ ổn nên không liên lạc",
      "- Key point: Quyết định dựa suy đoán (có thể sai)",
      "- Cấu trúc: S + からと思って",
      "- So sánh: ～と思い込んで nhấn niềm tin sai rõ rệt",
    ],
    more: [
      "- Ví dụ 1: 安いからと思って大量に買った。",
      "- Ví dụ 2: 大丈夫だと思って連絡しなかった。",
      "💡 Mẹo nhớ:",
      "  ・'Vì cho rằng...' → hành động",
      "❌ Sai: 安いから思って買った (thiếu と)",
      "✅ Đúng: 安いからと思って買いすぎた",
    ],
    question: {
      id: "21",
      content: "Điền: 安い___思って品質を確認しなかった。",
      correctAnswer: 1,
      answers: ["ので", "からと", "わけで", "にして"],
    },
  },
  {
    front: "～かとおもえば...も",
    back: [
      "- Ý nghĩa: Có ... cũng có ... (tương phản)",
      "・Có câu khó cũng có câu dễ",
      "・Tưởng nắng nhưng cũng có lúc mưa",
      "- Key point: Hai trạng thái đối lập xen kẽ",
      "- Cấu trúc: ～かと思えば...も",
      "- So sánh: ～かと思うと nhấn chuyển đổi nhanh (ít liệt kê)",
    ],
    more: [
      "- Ví dụ 1: 難しい問題かと思えば簡単なのもある。",
      "- Ví dụ 2: 晴れかと思えば雨も降る。",
      "💡 Mẹo nhớ:",
      "  ・'Tưởng A thì lại có B'",
      "❌ Sai: 忙しいと思えば暇な日もある (thiếu か)",
      "✅ Đúng: 忙しいかと思えば暇な日もある",
    ],
    question: {
      id: "22",
      content: "Điền: 忙しい___思えば暇な日もある。",
      correctAnswer: 0,
      answers: ["かと", "からと", "わけで", "ようで"],
    },
  },
  {
    front: "～といっても間違いない",
    back: [
      "- Ý nghĩa: Nói ... cũng không sai / gần như chắc chắn",
      "・Gọi anh ấy là thiên tài không sai",
      "・Gọi đây là thành công không sai",
      "- Key point: Khẳng định mạnh độ chính xác",
      "- Cấu trúc: Sと言っても間違いない",
      "- So sánh: ～と言っても (nhượng bộ) khác nghĩa",
    ],
    more: [
      "- Ví dụ 1: 彼は天才と言っても間違いない。",
      "- Ví dụ 2: これは成功と言っても間違いない。",
      "💡 Mẹo nhớ:",
      "  ・'Không sai chút nào' = xác nhận mạnh",
      "❌ Sai: 天才と言って間違いない (thiếu も)",
      "✅ Đúng: 天才と言っても間違いない人物だ",
    ],
    question: {
      id: "23",
      content: "Điền: これは革命___言っても間違いない成果だ。",
      correctAnswer: 2,
      answers: ["かと", "わけで", "と", "までで"],
    },
  },
  {
    front: "～にいわせれば",
    back: [
      "- Ý nghĩa: Theo ý kiến của...",
      "・Theo anh ấy thì dễ",
      "・Theo chuyên gia thì nguy hiểm",
      "- Key point: Gắn quan điểm cho chủ thể được nêu",
      "- Cấu trúc: Nに言わせれば",
      "- So sánh: ～からすると mang tính suy đoán",
    ],
    more: [
      "- Ví dụ 1: 彼に言わせれば簡単だ。",
      "- Ví dụ 2: 専門家に言わせれば危険だ。",
      "💡 Mẹo nhớ:",
      "  ・Trao 'quyền phát biểu' cho N",
      "❌ Sai: 医者を言わせれば危険だ (を sai trợ từ)",
      "✅ Đúng: 医者に言わせれば危険だ",
    ],
    question: {
      id: "24",
      content: "Điền: 医者___言わせれば睡眠不足が原因だ。",
      correctAnswer: 1,
      answers: ["からと", "に", "を", "まで"],
    },
  },
  {
    front: "～でなくてなんだろう",
    back: [
      "- Ý nghĩa: Chính là ... chứ còn gì nữa",
      "・Nếu không phải tình yêu thì là gì",
      "・Hành động đó chính là dũng khí",
      "- Key point: Câu hỏi tu từ khẳng định tuyệt đối",
      "- Cấu trúc: Nでなくてなんだろう",
      "- So sánh: まさに～だ khẳng định nhưng không tu từ",
    ],
    more: [
      "- Ví dụ 1: これが愛でなくてなんだろう。",
      "- Ví dụ 2: 彼の行動は勇気でなくてなんだろう。",
      "💡 Mẹo nhớ:",
      "  ・Phủ định giả → khẳng định mạnh",
      "❌ Sai: 才能でなくて (thiếu なんだろう)",
      "✅ Đúng: これが才能でなくてなんだろう",
    ],
    question: {
      id: "25",
      content: "Điền: これが才能___なんだろう。",
      correctAnswer: 3,
      answers: ["かと", "わけで", "にして", "でなくて"],
    },
  },
  {
    front: "～にあっては",
    back: [
      "- Ý nghĩa: Riêng trong / trong hoàn cảnh...",
      "・Trong khẩn cấp cần bình tĩnh",
      "・Thời kỳ chuyển đổi cần linh hoạt",
      "- Key point: Nhấn tính đặc thù của bối cảnh",
      "- Cấu trúc: Nにあって（は）",
      "- So sánh: ～において trung tính về địa điểm/thời điểm",
    ],
    more: [
      "- Ví dụ 1: 非常時にあっては冷静さが重要だ。",
      "- Ví dụ 2: 変化期にあっては柔軟性が求められる。",
      "💡 Mẹo nhớ:",
      "  ・'Trong hoàn cảnh đặc thù'",
      "❌ Sai: 公園にあっては人が多い (ngữ cảnh thường, dùng không tự nhiên)",
      "✅ Đúng: 緊急時にあっては迅速さが求められる",
    ],
    question: {
      id: "26",
      content: "Điền: 緊急事態___あっては迅速な判断が必要だ。",
      correctAnswer: 2,
      answers: ["にしては", "において", "に", "で"],
    },
  },
  {
    front: "～というわけだ",
    back: [
      "- Ý nghĩa: Có nghĩa là... (kết luận)",
      "・Tức là anh ấy không tới",
      "・Tức là không có thời gian",
      "- Key point: Tóm tắt suy luận từ thông tin trước",
      "- Cấu trúc: Sというわけだ",
      "- So sánh: ～わけではない là phủ định",
    ],
    more: [
      "- Ví dụ 1: 彼は来られないというわけだ。",
      "- Ví dụ 2: 時間がないというわけだ。",
      "💡 Mẹo nhớ:",
      "  ・Kết luận logic cuối",
      "❌ Sai: 行くというわけ (thiếu だ)",
      "✅ Đúng: 行けないというわけだ",
    ],
    question: {
      id: "27",
      content: "Điền: なるほど、だから参加できない___。",
      correctAnswer: 1,
      answers: ["わけではない", "というわけだ", "わけがない", "ところだ"],
    },
  },
  {
    front: "～ようで（は）",
    back: [
      "- Ý nghĩa: Nếu cứ tình trạng như vậy thì (kết quả xấu)",
      "・Thái độ đó sẽ không thành công",
      "・Không luyện tập thì chẳng tiến bộ",
      "- Key point: Phán đoán tiêu cực dựa hiện trạng",
      "- Cấu trúc: Vる / Adj / Nの + ようでは",
      "- So sánh: ～ようではなく phủ định dạng đó",
    ],
    more: [
      "- Ví dụ 1: そんな態度を取るようでは成功しない。",
      "- Ví dụ 2: 練習しないようでは上達しない。",
      "💡 Mẹo nhớ:",
      "  ・'Như thế này thì...' cảnh báo",
      "❌ Sai: 練習しないようで上達しない (thiếu は, mờ sắc thái điều kiện)",
      "✅ Đúng: 練習しないようでは上達しない",
    ],
    question: {
      id: "28",
      content: "Điền: その努力の仕方___成果は出ないだろう。",
      correctAnswer: 2,
      answers: ["わけでは", "ばかりで", "ようでは", "にあっては"],
    },
  },
  {
    front: "～あえて",
    back: [
      "- Ý nghĩa: Dám / mạnh dạn làm điều khó hoặc trái mong đợi",
      "・Dám chọn đường nguy hiểm",
      "・Dám nêu ý kiến phản đối",
      "- Key point: Cố ý chọn rủi ro / đối nghịch chuẩn mực",
      "- Cấu trúc: あえて + Vる / Vない",
      "- So sánh: わざわざ nhấn công sức không nhất thiết trái kỳ vọng",
    ],
    more: [
      "- Ví dụ 1: あえて危険な道を選んだ。",
      "- Ví dụ 2: あえて反対意見を述べる。",
      "💡 Mẹo nhớ:",
      "  ・'Cố tình chọn khó'",
      "❌ Sai: あえて水を飲んだ (hành động bình thường không cần 'dám')",
      "✅ Đúng: あえて誰も言わない欠点を指摘した",
    ],
    question: {
      id: "29",
      content: "Điền: 皆が賛成する中___反対を述べた。",
      correctAnswer: 1,
      answers: ["つい", "あえて", "わざわざ", "どうにも"],
    },
  },
  {
    front: "～が早いか",
    back: [
      "- Ý nghĩa: Vừa mới... thì lập tức...",
      "・Vừa thấy thầy là im",
      "・Chuông reo cái là ra ngay",
      "- Key point: Hành động sau xảy ra ngay tức thì",
      "- Cấu trúc: Vるが早いか",
      "- So sánh: ～かと思うと có sắc thái bất ngờ hơn",
    ],
    more: [
      "- Ví dụ 1: 先生を見るが早いか静かになった。",
      "- Ví dụ 2: ベルが鳴るが早いか生徒が出た。",
      "💡 Mẹo nhớ:",
      "  ・A xong tức thì B bật",
      "❌ Sai: ドアを開けてが早いか (dùng て)",
      "✅ Đúng: ドアを開けるが早いか猫が飛び出した",
    ],
    question: {
      id: "30",
      content: "Điền: ドアを開ける___猫が飛び出した。",
      correctAnswer: 0,
      answers: ["が早いか", "ところで", "末に", "うちに"],
    },
  },
];

export default function Page() {
  return (
    <main>
      <h1 className="text-2xl font-bold text-center mt-8">
        Flash Card Grammar N1 - Page 1
      </h1>
      <FlashCard cards={cards} />
    </main>
  );
}
