import { FlashCardItem } from "@/shared/component/flash-card/flash-card";

export const cards: FlashCardItem[] = [
  {
    front: "～とはいえ",
    back: [
      "✨ Mặc dù, dù, cho dù",
      "・Ví dụ: Mặc dù đã nói là mùa xuân, nhưng vẫn còn lạnh.",
      "📌 Diễn tả sự thật được thừa nhận (A) nhưng kết quả (B) lại trái với dự đoán thông thường.",
    ],
    more: [
      "🧩 N / Vる / Aい / Naである + とはいえ",
      "⚖️ ～からといって (Cho dù nói là...), ～ものの (Mặc dù... nhưng...)",
      "💬 Văn viết, trang trọng, dùng để thừa nhận một sự thật rồi đưa ra một ngoại lệ.",
      "📝 ví dụ",
      "・ベテランとはいえ、初めての仕事なので緊張している",
      "・春とはいえ、まだまだ寒い日が続いている",
    ],
    questions: [
      {
        id: "1-1",
        content: "プロ___、練習しなければすぐに衰える",
        answers: ["ものの", "だけに", "とはいえ", "からには"],
        correctAnswer: 2,
        memo: [
          "ものの: 'Mặc dù... nhưng...', nhấn mạnh sự thật A không đủ để ngăn B.",
          "だけに: 'Chính vì là...', nhấn mạnh lý do tích cực.",
          "とはいえ: 'Mặc dù đã nói là...'. Thừa nhận sự thật (là chuyên nghiệp) nhưng kết quả lại trái ngược (sẽ sa sút). (Đúng)",
          "からには: 'Một khi đã...', nhấn mạnh nghĩa vụ.",
        ],
      },
      {
        id: "1-2",
        content: "いくら忙しい___、食事を抜くのは体に悪い。",
        answers: ["ものの", "とはいえ", "からといって", "だけあって"],
        correctAnswer: 2,
        memo: [
          "ものの: 'Mặc dù... nhưng...', nhấn mạnh sự thật A không đủ để ngăn B.",
          "とはいえ: 'Mặc dù đã nói là...', cũng đúng nhưng からといって phù hợp hơn khi phủ định một hành động cực đoan.",
          "からといって: 'Cho dù nói là... cũng không hẳn'. Phủ định một hành động dựa trên lý do (Bỏ ăn dù bận). (Đúng)",
          "だけあって: 'Quả đúng là...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～きわまる／きわまりない（～極まる／極まりない）",
    back: [
      "✨ Cực kỳ, rất (Diễn tả mức độ cao nhất, thường mang tính tiêu cực)",
      "・Ví dụ: Hành vi đó cực kỳ vô lý.",
      "📌 Luôn đi kèm với danh từ/tính từ chỉ trạng thái hoặc cảm xúc (thường là tiêu cực: vô lý, tệ hại, khó chịu).",
    ],
    more: [
      "🧩 N / Na + きわまる / きわまりない",
      "⚖️ ～の至り (Vô cùng, cực kỳ - thường dùng cho cảm xúc tích cực, trang trọng), ～限りだ (Vô cùng - dùng cho cảm xúc mạnh)",
      "💬 Văn viết, trang trọng, dùng để chỉ trích hoặc đánh giá.",
      "📝 ví dụ",
      "・その態度は失礼極まる (きわまる) ものだ",
      "・彼は非常識極まりない (きわまりない) 行動をした",
    ],
    questions: [
      {
        id: "2-1",
        content: "彼の考え方は、身勝手___",
        answers: ["の至りだ", "きわまりない", "に限る", "だけましだ"],
        correctAnswer: 1,
        memo: [
          "の至りだ: 'Vô cùng' (thường là tích cực: vinh dự).",
          "きわまりない: 'Cực kỳ' (thường là tiêu cực). Phù hợp với tính từ tiêu cực '身勝手' (ích kỷ). (Đúng)",
          "に限る: 'Chỉ có...', không phù hợp.",
          "だけましだ: '... là còn tốt chán', không phù hợp.",
        ],
      },
      {
        id: "2-2",
        content: "このような栄誉をいただき、光栄___",
        answers: ["の至りです", "きわまりない", "ばかりです", "でたまらない"],
        correctAnswer: 0,
        memo: [
          "の至りです: 'Vô cùng...'. Đi kèm với danh từ tích cực (光栄 - vinh dự). (Đúng)",
          "きわまりない: 'Cực kỳ' (thường là tiêu cực).",
          "ばかりです: 'Chỉ...', không phù hợp.",
          "でたまらない: 'Không chịu nổi', dùng cho cảm xúc khó kìm nén.",
        ],
      },
    ],
  },
  {
    front: "～という",
    back: [
      "✨ Toàn bộ / Tất cả / Chính là (Nhấn mạnh sự tổng thể hoặc bản chất)",
      "・Ví dụ: Toàn bộ thành phố đã trở thành đống đổ nát.",
      "📌 Thường đi kèm với danh từ chỉ phạm vi lớn (thành phố, thế giới) để nhấn mạnh sự bao trùm toàn bộ.",
    ],
    more: [
      "🧩 N + という + N (Ví dụ: 町という町 - Toàn bộ các thị trấn)",
      "⚖️ ～の全て (toàn bộ, tất cả), ～あげて (toàn thể)",
      "💬 Văn viết, trang trọng.",
      "📝 ví dụ",
      "・町という町が廃墟と化した",
      "・この企画は、社員という社員の協力があってこそ成功した",
    ],
    questions: [
      {
        id: "3-1",
        content: "家___家が燃えて、あたり一面火の海となった",
        answers: ["という", "といった", "の全て", "のありよう"],
        correctAnswer: 0,
        memo: [
          "という: 'Toàn bộ/Tất cả' (nhấn mạnh sự bao trùm toàn bộ). (Đúng)",
          "といった: 'Chẳng hạn như...', không phù hợp.",
          "の全て: Cũng là 'toàn bộ' nhưng という nhấn mạnh sự bao trùm hơn.",
          "のありよう: 'Trạng thái...', không phù hợp.",
        ],
      },
      {
        id: "3-2",
        content: "山田さんの家は、家具___家具が高級なものばかりだ。",
        answers: ["という", "にしろ", "からにいたるまで", "といい"],
        correctAnswer: 0,
        memo: [
          "という: 'Toàn bộ/Tất cả' (nhấn mạnh tất cả các đồ đạc đều là đồ cao cấp). (Đúng)",
          "にしろ: 'Dù là...', không phù hợp.",
          "からにいたるまで: 'Từ... cho đến...', nhấn mạnh phạm vi.",
          "といい: 'Cả A và B...', liệt kê ví dụ.",
        ],
      },
    ],
  },
  {
    front: "～こともV-ない",
    back: [
      "✨ Đành bỏ không…, những thứ đã định (Không làm một hành động nào đó, dù đã có ý định)",
      "・Ví dụ: Tôi đã định hỏi nhưng đành bỏ không hỏi.",
      "📌 Diễn tả việc dừng lại, không thực hiện hành động đã định vì một lý do bất ngờ hoặc khó khăn.",
    ],
    more: [
      "🧩 Vる + ことも + Vない (V: thường là 言う, する, 聞く, etc.)",
      "⚖️ Vるのをやめる (ngừng làm), Vるのを控える (kiềm chế)",
      "💬 Văn nói, diễn tả sự tiếc nuối, đành lòng.",
      "📝 ví dụ",
      "・彼に本当のことを聞こうと思ったが、何も言わずに出発することにした",
      "・文句を言おうと（は）思ったが、言うことも言わなかった",
    ],
    questions: [
      {
        id: "4-1",
        content: "彼女に謝ろうと(は)思ったが、結局___",
        answers: [
          "謝ることもなかった",
          "謝らないことにした",
          "謝ろうとしない",
          "謝ることではない",
        ],
        correctAnswer: 0,
        memo: [
          "謝ることもなかった: 'Đã định xin lỗi nhưng đành bỏ không xin lỗi'. Phù hợp với ngữ cảnh 'dừng lại việc đã định'. (Đúng)",
          "謝らないことにした: 'Đã quyết định không xin lỗi'.",
          "謝ろうとしない: 'Không có ý định xin lỗi'.",
          "謝ることではない: 'Không phải là việc xin lỗi'.",
        ],
      },
      {
        id: "4-2",
        content: "彼に忠告しようと（は）思ったが、言う___",
        answers: [
          "までもない",
          "ものだ",
          "ことも言わなかった",
          "ざるを得なかった",
        ],
        correctAnswer: 2,
        memo: [
          "までもない: 'Không cần thiết phải...', không phù hợp.",
          "ものだ: 'Nên làm...', không phù hợp.",
          "言うことも言わなかった: Cấu trúc cố định (言うこともVない) 'Đã định nói nhưng đành bỏ không nói'. (Đúng)",
          "ざるを得なかった: 'Buộc phải làm', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～かたがた",
    back: [
      "✨ Nhân tiện / Kèm (Kết hợp mục đích của hai hành động, trang trọng hơn がてら/ついでに)",
      "・Ví dụ: Nhân tiện chào hỏi cấp trên, tôi thăm cấp trên đang bị bệnh.",
      "📌 Hành động chính (A) được kết hợp với một hành động phụ (B) mang mục đích khác. Thường dùng với các danh từ Hán Việt (見舞い、散歩、報告).",
    ],
    more: [
      "🧩 N + かたがた",
      "⚖️ ～がてら (thông dụng hơn, nhấn yếu tố di chuyển), ～ついでに (thông dụng nhất, hành động phụ phát sinh)",
      "💬 Văn viết, trang trọng.",
      "📝 ví dụ",
      "・お見舞いかたがた、ご挨拶に伺いました",
      "・散歩かたがた、駅前の新しい店を見てきた",
    ],
    questions: [
      {
        id: "5-1",
        content: "お見舞い___、ご挨拶に伺いました",
        answers: ["につけ", "がてら", "かたがた", "ついでに"],
        correctAnswer: 2,
        memo: [
          "につけ: 'Mỗi khi...', không phù hợp.",
          "がてら: 'Nhân tiện' (thông thường).",
          "かたがた: 'Nhân tiện/Kèm'. Trang trọng, thường dùng trong chào hỏi, thăm viếng (kết hợp thăm bệnh và chào hỏi). (Đúng)",
          "ついでに: 'Tiện thể' (thông thường).",
        ],
      },
      {
        id: "5-2",
        content: "散歩___、コンビニに寄った。",
        answers: ["かたがた", "をかぎりに", "がてら", "をめぐって"],
        correctAnswer: 2,
        memo: [
          "かたがた: Quá trang trọng cho việc 'ghé cửa hàng tiện lợi'.",
          "をかぎりに: 'Cho đến hết...', không phù hợp.",
          "がてら: 'Nhân tiện đi dạo', ghé cửa hàng tiện lợi. Phù hợp vì có yếu tố di chuyển. (Đúng)",
          "をめぐって: 'Xoay quanh...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～にあって(は)",
    back: [
      "✨ Ở trong (tình huống) / Trong hoàn cảnh (Nhấn mạnh bối cảnh, thường là khó khăn hoặc đặc biệt)",
      "・Ví dụ: Trong tình huống khó khăn này, sự quyết đoán của lãnh đạo là rất cần thiết.",
      "📌 Dùng để chỉ bối cảnh, tình huống, thời đại mà hành động tiếp theo diễn ra. Thường là những bối cảnh đặc biệt (chiến tranh, khó khăn).",
    ],
    more: [
      "🧩 N + にあって(は)",
      "⚖️ ～において (trong lĩnh vực/ở nơi), ～のもとで (dưới sự...)",
      "💬 Văn viết, trang trọng.",
      "📝 ví dụ",
      "・この難局にあっては、リーダーの決断力が求められる",
      "・戦時中という困難な状況にあっても、人々は希望を捨てなかった",
    ],
    questions: [
      {
        id: "6-1",
        content: "この難局___、リーダーの決断力が試される。",
        answers: ["において", "にあって", "を限りに", "にとって"],
        correctAnswer: 1,
        memo: [
          "において: 'Trong lĩnh vực/ở nơi...', không phù hợp.",
          "にあって: 'Trong hoàn cảnh/tình huống'. Nhấn mạnh bối cảnh khó khăn (難局) hiện tại. (Đúng)",
          "を限りに: 'Cho đến hết...', không phù hợp.",
          "にとって: 'Đối với...', không phù hợp.",
        ],
      },
      {
        id: "6-2",
        content: "日本___、彼の研究は高く評価されている",
        answers: ["にあって", "において", "のことで", "にかけては"],
        correctAnswer: 1,
        memo: [
          "にあって: 'Trong hoàn cảnh...', không phù hợp với danh từ chỉ địa điểm/lĩnh vực.",
          "において: 'Trong lĩnh vực/ở nơi'. Phù hợp với danh từ chỉ phạm vi (ở Nhật). (Đúng)",
          "のことで: 'Về việc...', không phù hợp.",
          "にかけては: 'Về mặt...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～ぶん (だけ)",
    back: [
      "✨ Bao nhiêu… thì bấy nhiêu / Tương ứng với (Sự thay đổi A tương ứng với sự thay đổi B)",
      "・Ví dụ: Học hành vất vả bao nhiêu thì niềm vui khi tốt nghiệp lại lớn bấy nhiêu.",
      "📌 Nhấn mạnh mối quan hệ tỷ lệ thuận giữa hai trạng thái/hành động (A và B).",
    ],
    more: [
      "🧩 Vる / N / Aい / Naな + ぶん (だけ)",
      "⚖️ ～につれて (cùng với sự thay đổi...), ～に応じても (tương ứng với sự thay đổi...)",
      "💬 Văn nói, dùng để diễn tả sự thỏa đáng, hợp lý.",
      "📝 ví dụ",
      "・努力した分だけ、結果はついてくる",
      "・給料が上がる分、仕事の責任も重くなる",
    ],
    questions: [
      {
        id: "7-1",
        content: "努力した___、結果はついてくる",
        answers: ["ぶんだけ", "につけて", "に応じて", "にかかわらず"],
        correctAnswer: 0,
        memo: [
          "ぶんだけ: 'Bao nhiêu... thì bấy nhiêu'. Nhấn mạnh kết quả tương xứng với nỗ lực. (Đúng)",
          "につけて: 'Mỗi khi...', không phù hợp.",
          "に応じて: 'Tương ứng với...', dùng cho sự thay đổi khách quan.",
          "にかかわらず: 'Không phân biệt...', không phù hợp.",
        ],
      },
      {
        id: "7-2",
        content: "給料が上がる___、仕事の責任も重くなる",
        answers: ["につれて", "限り", "ぶん", "というものだ"],
        correctAnswer: 2,
        memo: [
          "につれて: 'Cùng với sự thay đổi của...', không phù hợp.",
          "限り: 'Chừng nào còn...', không phù hợp.",
          "ぶん: 'Bao nhiêu... thì bấy nhiêu'. Nhấn mạnh sự thay đổi tương xứng giữa lương và trách nhiệm. (Đúng)",
          "というものだ: 'Thật là...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～ひではない",
    back: [
      "✨ Không thể so sánh được / Không thể sánh bằng (Thường dùng để khiêm tốn hoặc đánh giá)",
      "・Ví dụ: Kinh nghiệm của tôi không thể sánh được với anh ấy.",
      "📌 Dùng để phủ định sự ngang bằng, nhấn mạnh sự chênh lệch lớn về mức độ, kinh nghiệm.",
    ],
    more: [
      "🧩 N + に / と + ひではない",
      "⚖️ ～に及ばない (Không bằng, không đạt được), ～には及ばない (Không cần thiết)",
      "💬 Văn viết, trang trọng.",
      "📝 ví dụ",
      "・彼の経験は私とは比べものにならない (私とは比較のひではない)",
      "・この程度のミスは、謝罪するにひではない (Không cần thiết phải xin lỗi)",
    ],
    questions: [
      {
        id: "8-1",
        content: "彼の経験は、私___",
        answers: [
          "に及ばない",
          "とは比べものにならない",
          "にひではない",
          "に際して",
        ],
        correctAnswer: 1,
        memo: [
          "に及ばない: 'Không bằng'.",
          "とは比べものにならない: 'Không thể so sánh được'. Đồng nghĩa với にひではない. (Đúng)",
          "にひではない: 'Không thể so sánh được'. Thường dùng để chỉ sự chênh lệch lớn.",
          "に際して: 'Nhân dịp...', không phù hợp.",
        ],
      },
      {
        id: "8-2",
        content: "こんな小さなミスで、謝罪する___",
        answers: ["にいたる", "にひではない", "わけにはいかない", "べし"],
        correctAnswer: 1,
        memo: [
          "にいたる: 'Đến mức...', không phù hợp.",
          "にひではない: 'Không cần thiết phải...'. (Không cần thiết phải xin lỗi vì lỗi nhỏ). (Đúng)",
          "わけにはいかない: 'Không thể (vì lý do nghĩa vụ)', không phù hợp.",
          "べし: 'Nên làm', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～ずにおく",
    back: [
      "✨ Để thế mà không…, tạm không… (Giữ nguyên trạng thái của hành động V)",
      "・Ví dụ: Tạm không trả lời thư. / Để đồ vật ở nguyên đó mà không chạm vào.",
      "📌 Hành động được giữ nguyên ở trạng thái phủ định (không làm) và để yên như vậy.",
    ],
    more: [
      "🧩 Vない → Vず + におく",
      "⚖️ Vないままにする (Giữ nguyên trạng thái không V), Vるのを控える (kiềm chế)",
      "💬 Văn viết, trang trọng.",
      "📝 ví dụ",
      "・その手紙は、返事を出さずにおいた",
      "・何も言わずにおくのが最善だと思った",
    ],
    questions: [
      {
        id: "9-1",
        content: "彼女には、何も言わ___が最善だと思った。",
        answers: ["ずにおく", "ないままに", "ないではおかない", "ずにいる"],
        correctAnswer: 0,
        memo: [
          "ずにおく: 'Để thế mà không nói' (không nói và giữ nguyên trạng thái đó). (Đúng)",
          "ないままに: 'Giữ nguyên trạng thái không nói' (không nhấn mạnh ý định 'tạm không').",
          "ないではおかない: 'Nhất định sẽ làm', ngược nghĩa.",
          "ずにいる: 'Đang ở trạng thái không...', không phù hợp.",
        ],
      },
      {
        id: "9-2",
        content: "その問題は、しばらくこの___",
        answers: [
          "状態で置いておく",
          "状態でいよう",
          "ままで置いておく",
          "ままにしよう",
        ],
        correctAnswer: 2,
        memo: [
          "状態で置いておく: 'Để ở trạng thái đó', không phù hợp với ngữ pháp.",
          "状態でいよう: 'Hãy cứ ở trạng thái đó'.",
          "ままで置いておく: 'Để nguyên như vậy mà không thay đổi'. Đồng nghĩa với ずに、Vるのをやめる. (Đúng)",
          "ままにしよう: 'Hãy cứ như vậy đi'.",
        ],
      },
    ],
  },
  {
    front: "～たかだか",
    back: [
      "✨ Giỏi lắm cũng chỉ…, nhiều lắm cũng chỉ… (Nhấn mạnh mức độ tối đa thấp, mang tính xem nhẹ)",
      "・Ví dụ: Giỏi lắm cũng chỉ kiếm được 5000 yên.",
      "📌 Nhấn mạnh một giới hạn về số lượng/mức độ, ngụ ý rằng con số đó không đáng kể.",
    ],
    more: [
      "🧩 たかだか + Số lượng / N / Vる (kèm ても)",
      "⚖️ ～といったところだ (Đại khái là - khiêm tốn hơn), ～にすぎない (Chỉ là)",
      "💬 Văn nói, dùng để xem nhẹ, phủ định.",
      "📝 ví dụ",
      "・バイトで稼げるのは、たかだか5000円だ",
      "・彼の失敗は、たかだか初歩的なミスだ",
    ],
    questions: [
      {
        id: "10-1",
        content: "私の貯金は10万円___",
        answers: ["といったところだ", "にすぎない", "たかだかだ", "くらいだ"],
        correctAnswer: 0,
        memo: [
          "といったところだ: 'Đại khái là/Chừng đó là cùng'. Thể hiện sự khiêm tốn về mức độ. (Đúng)",
          "にすぎない: 'Chỉ là...', mang tính phủ định.",
          "たかだかだ: 'Giỏi lắm cũng chỉ...'. Thường đi kèm với số lượng cụ thể và mang tính xem nhẹ mạnh mẽ hơn.",
          "くらいだ: 'Khoảng...', không nhấn mạnh giới hạn.",
        ],
      },
      {
        id: "10-2",
        content: "このレポートを書くのにかかった時間は、___2時間だ。",
        answers: ["たかだか", "せいぜい", "にすぎない", "極まりない"],
        correctAnswer: 0,
        memo: [
          "たかだか: 'Giỏi lắm cũng chỉ...'. Nhấn mạnh rằng 2 tiếng là mức tối đa, ngụ ý là ít. (Đúng)",
          "せいぜい: 'Tối đa là...'. Đồng nghĩa với たかだか.",
          "にすぎない: 'Chỉ là...', không phù hợp cấu trúc.",
          "極まりない: 'Cực kỳ...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～さほど",
    back: [
      "✨ Không… lắm / Không đến mức đó (Phủ định mức độ mạnh mẽ)",
      "・Ví dụ: Công việc này không khó lắm.",
      "📌 Luôn đi kèm với phủ định (ない, ではない) để phủ nhận một mức độ mạnh mẽ.",
    ],
    more: [
      "🧩 さほど + Vない / Aい-くない / Nではない",
      "⚖️ それほど～ない (Không... đến mức đó), たいして～ない (Không... lắm)",
      "💬 Văn nói và viết.",
      "📝 ví dụ",
      "・この仕事は、さほど難しくない",
      "・彼の話は、さほど面白くなかった",
    ],
    questions: [
      {
        id: "11-1",
        content: "この問題は、___複雑では___",
        answers: [
          "さほど/ない",
          "それほど/ない",
          "ほとんど/ない",
          "とうてい/ない",
        ],
        correctAnswer: 0,
        memo: [
          "さほど/ない: 'Không... lắm'. (Đúng)",
          "それほど/ない: 'Không... đến mức đó'. Đồng nghĩa với さほど, nhưng さほど trang trọng hơn.",
          "ほとんど/ない: 'Hầu như không', không phù hợp.",
          "とうてい/ない: 'Hoàn toàn không thể', không phù hợp.",
        ],
      },
      {
        id: "11-2",
        content: "彼は天才だと言われているが、彼の能力は___",
        answers: ["さほどではない", "にすぎない", "というわけだ", "という"],
        correctAnswer: 0,
        memo: [
          "さほどではない: 'Không đến mức đó'. Phủ định mức độ mạnh (thiên tài). (Đúng)",
          "にすぎない: 'Chỉ là...', không phù hợp.",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
          "という: 'Toàn bộ...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～捲る（まくる）",
    back: [
      "✨ Liên tục… / Làm một cách hết mình (Diễn tả hành động diễn ra liên tục, không ngừng nghỉ hoặc ở mức độ cao)",
      "・Ví dụ: Cô ấy nói liên tục không ngừng.",
      "📌 Nhấn mạnh tần suất cao, sự liên tục của hành động hoặc sự hết mình, quá mức của hành động.",
    ],
    more: [
      "🧩 Vます + まくる",
      "⚖️ ～続ける (Tiếp tục...), Vる一方だ (Cứ... mãi)",
      "💬 Văn nói suồng sã.",
      "📝 ví dụ",
      "・彼女はしゃべりまくって、誰も口を挟めなかった",
      "・ゲームをやりまくって、寝る暇もなかった",
    ],
    questions: [
      {
        id: "12-1",
        content: "ゲームを___、寝る暇もなかった。",
        answers: ["やり続ける", "やりまくる", "やる一方だ", "やるばかりだ"],
        correctAnswer: 1,
        memo: [
          "やり続ける: 'Tiếp tục làm'.",
          "やりまくる: 'Làm liên tục, hết mình' (chơi game một cách điên cuồng). (Đúng)",
          "やる一方だ: 'Cứ làm... mãi', nhấn mạnh xu hướng.",
          "やるばかりだ: 'Chỉ còn cách làm...', không phù hợp.",
        ],
      },
      {
        id: "12-2",
        content: "彼の借金は増える___。",
        answers: ["まくっている", "一方だ", "ばかりだ", "にすぎない"],
        correctAnswer: 1,
        memo: [
          "まくっている: 'Liên tục...'.",
          "一方だ: 'Cứ... mãi'. Nhấn mạnh xu hướng liên tục tăng (món nợ). (Đúng)",
          "ばかりだ: 'Chỉ còn cách làm...', không phù hợp.",
          "にすぎない: 'Chỉ là...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～みこみがたつ（見込みが立つ）",
    back: [
      "✨ Có triển vọng, có hy vọng (Có khả năng thực hiện được hoặc đạt được kết quả)",
      "・Ví dụ: Dự án đã có triển vọng thành công.",
      "📌 Dùng để diễn tả sự đánh giá về khả năng thành công, đạt được mục tiêu trong tương lai.",
    ],
    more: [
      "🧩 Vる / Nの + 見込みが立つ",
      "⚖️ ～可能性が高い (Khả năng cao), ～見通しだ (Có triển vọng)",
      "💬 Văn nói và viết.",
      "📝 ví dụ",
      "・このプロジェクトは成功の見込みが立った",
      "・来月には退院できる見込みが立った",
    ],
    questions: [
      {
        id: "13-1",
        content: "このプロジェクトは成功の___",
        answers: ["可能性が高い", "見通しだ", "見込みが立った", "ばかりだ"],
        correctAnswer: 2,
        memo: [
          "可能性が高い: 'Khả năng cao'.",
          "見通しだ: 'Có triển vọng' (nhấn mạnh sự nhìn thấy trước).",
          "見込みが立った: 'Đã có triển vọng' (nhấn mạnh việc đạt được một đánh giá khả quan). (Đúng)",
          "ばかりだ: 'Chỉ còn cách làm...', không phù hợp.",
        ],
      },
      {
        id: "13-2",
        content: "彼は回復の___",
        answers: ["見込みがある", "見込みが立った", "ところだ", "はずだ"],
        correctAnswer: 0,
        memo: [
          "見込みがある: 'Có triển vọng/có khả năng'. Phù hợp với trạng thái 'có khả năng hồi phục'. (Đúng)",
          "見込みが立った: 'Đã có triển vọng' (thường dùng cho các dự án, kế hoạch).",
          "ところだ: 'Đúng lúc...', không phù hợp.",
          "はずだ: 'Chắc chắn là...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～がかり",
    back: [
      "✨ Dựa vào…, giống như… (Mang tính ước chừng, không chính xác)",
      "・Ví dụ: Đây là bức tranh giống như vẽ bằng tay.",
      "📌 Dùng để chỉ sự ước chừng, không chính xác về tính chất, màu sắc hoặc nguồn gốc.",
    ],
    more: [
      "🧩 N + がかり (Danh từ chỉ màu sắc, tính chất, hành động...)",
      "⚖️ ～のような (Giống như), ～っぽい (Hơi có vẻ)",
      "💬 Văn nói, suồng sã.",
      "📝 ví dụ",
      "・これは手書きがかりの絵だ",
      "・そのシャツは青がかりの色だ",
    ],
    questions: [
      {
        id: "14-1",
        content: "この絵は、遠くから見ると油絵___に見える。",
        answers: ["っぽい", "のような", "がかり", "にほかならない"],
        correctAnswer: 2,
        memo: [
          "っぽい: 'Hơi có vẻ', dùng cho tính chất.",
          "のような: 'Giống như'.",
          "がかり: 'Giống như/Dựa vào'. Mang tính ước chừng, không chính xác về tính chất. (Đúng)",
          "にほかならない: 'Chính là', không phù hợp.",
        ],
      },
      {
        id: "14-2",
        content: "彼女はまだ若いが、考え方は大人___。",
        answers: ["っぽい", "のような", "がかり", "にすぎない"],
        correctAnswer: 0,
        memo: [
          "っぽい: 'Hơi có vẻ'. Chỉ tính chất, khuynh hướng (có vẻ như người lớn). (Đúng)",
          "のような: 'Giống như'.",
          "がかり: Thường dùng cho màu sắc, kỹ thuật.",
          "にすぎない: 'Chỉ là', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～でもあるまい",
    back: [
      "✨ Không còn là lúc… / Đâu phải là… mà… (Nhấn mạnh sự không phù hợp của hành động, thường đi với phủ định)",
      "・Ví dụ: Đâu phải là trẻ con nữa mà làm trò đó.",
      "📌 Dùng để phủ định sự phù hợp của hành động, nhấn mạnh rằng đã qua thời điểm/trạng thái đó.",
    ],
    more: [
      "🧩 N / Vる + でもあるまい",
      "⚖️ ～じゃあるまいし (Đâu phải là... mà - thông tục hơn), ～わけにはいかない (Không thể làm vì nghĩa vụ)",
      "💬 Văn viết, trang trọng, dùng để chỉ trích hoặc phủ định.",
      "📝 ví dụ",
      "・子供___、そんなことで泣くな",
      "・いつまでも悩んでいる___、早く決断すべきだ",
    ],
    questions: [
      {
        id: "15-1",
        content: "いつまでも悩んでいる___、早く決断すべきだ",
        answers: [
          "わけではない",
          "でもあるまい",
          "にすぎない",
          "といったところだ",
        ],
        correctAnswer: 1,
        memo: [
          "わけではない: 'Không hẳn là...', không phù hợp.",
          "でもあるまい: 'Không còn là lúc...'. Nhấn mạnh rằng không phải lúc để cứ mãi đau khổ. (Đúng)",
          "にすぎない: 'Chỉ là...', không phù hợp.",
          "といったところだ: 'Đại khái là...', không phù hợp.",
        ],
      },
      {
        id: "15-2",
        content: "子供___、わがままを言ってはいけない",
        answers: ["じゃあるまいし", "であるならば", "というものだ", "にあって"],
        correctAnswer: 0,
        memo: [
          "じゃあるまいし: 'Đâu phải là... mà'. Phủ định sự phù hợp của hành động (vòi vĩnh) vì đã qua trạng thái đó (trẻ con). (Đúng)",
          "であるならば: 'Nếu là...', không phù hợp.",
          "というものだ: 'Thật là...', không phù hợp.",
          "にあって: 'Trong hoàn cảnh...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～めく",
    back: [
      "✨ Có vẻ như…, mang khuynh hướng… (Mang tính chất của danh từ, trạng thái)",
      "・Ví dụ: Có vẻ như đang mùa xuân.",
      "📌 Dùng để chỉ sự vật, trạng thái có tính chất, khuynh hướng của danh từ đó.",
    ],
    more: [
      "🧩 N + めく",
      "⚖️ ～っぽい (Hơi có vẻ), ～じみる (Có vẻ... cũ kỹ, thô tục)",
      "💬 Văn viết, trang trọng (thường dùng cho các danh từ trừu tượng: bí ẩn, mùa...).",
      "📝 ví dụ",
      "・そこは、いかにも春めいた場所だった",
      "・謎めいた事件の真相を探る",
    ],
    questions: [
      {
        id: "16-1",
        content: "そこは、いかにも春___場所だった",
        answers: ["らしい", "めいた", "っぽい", "のような"],
        correctAnswer: 1,
        memo: [
          "らしい: 'Đúng là/có vẻ là' (mang tính tích cực, rõ ràng).",
          "めいた: 'Có vẻ như/mang khuynh hướng'. Dùng cho danh từ trừu tượng (春 - mùa xuân). (Đúng)",
          "っぽい: 'Hơi có vẻ' (thường dùng cho tính chất, tiêu cực).",
          "のような: 'Giống như'.",
        ],
      },
      {
        id: "16-2",
        content: "子供が作ったとは思えないほど大人___絵だ。",
        answers: ["らしい", "めいた", "びた", "っぽい"],
        correctAnswer: 3,
        memo: [
          "らしい: 'Đúng là...', không phù hợp.",
          "めいた: 'Có vẻ như...', trang trọng.",
          "びた: 'Có vẻ... cũ kỹ/thô tục', không phù hợp.",
          "っぽい: 'Hơi có vẻ'. Dùng cho tính chất (có vẻ như người lớn). (Đúng)",
        ],
      },
    ],
  },
  {
    front: "～ぶんには",
    back: [
      "✨ Nếu chỉ trong phạm vi… thì (Giới hạn phạm vi hành động hoặc điều kiện)",
      "・Ví dụ: Nếu chỉ là nghe thôi thì không có vấn đề gì.",
      "📌 Dùng để giới hạn điều kiện, hành động (A), và khẳng định rằng trong phạm vi đó (B) thì không có vấn đề gì.",
    ],
    more: [
      "🧩 Vる / N + である / N + の + ぶんには",
      "⚖️ ～限りでは (Trong phạm vi...), ～だけなら (Nếu chỉ là... thì)",
      "💬 Văn nói, dùng để đặt điều kiện.",
      "📝 ví dụ",
      "・聞くだけのぶんには、問題はない",
      "・君が反対しないぶんには、私は構わない",
    ],
    questions: [
      {
        id: "17-1",
        content: "聞く___、問題はない",
        answers: ["ぶんには", "限りでは", "だけなら", "といったところだ"],
        correctAnswer: 0,
        memo: [
          "ぶんには: 'Nếu chỉ trong phạm vi... thì'. Giới hạn phạm vi hành động (nghe) và khẳng định kết quả (không vấn đề). (Đúng)",
          "限りでは: 'Trong phạm vi/Theo như...', dùng cho thông tin.",
          "だけなら: 'Nếu chỉ là... thì'. Gần đúng, nhưng ぶんには nhấn mạnh sự giới hạn hơn.",
          "といったところだ: 'Đại khái là...', không phù hợp.",
        ],
      },
      {
        id: "17-2",
        content: "私が知っている___、間違いはありません。",
        answers: ["ぶんには", "限りでは", "だけなら", "といったところだ"],
        correctAnswer: 1,
        memo: [
          "ぶんには: 'Nếu chỉ trong phạm vi... thì'.",
          "限りでは: 'Trong phạm vi/Theo như...'. Thường dùng để giới hạn nguồn thông tin (theo những gì tôi biết). (Đúng)",
          "だけなら: 'Nếu chỉ là... thì'.",
          "といったところだ: 'Đại khái là...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～じゃ(では)あるまいし",
    back: [
      "✨ Đâu phải là… mà… (Phủ định sự phù hợp của hành động, nhấn mạnh sự khác biệt về trạng thái)",
      "・Ví dụ: Đâu phải là trẻ con mà khóc lóc như thế.",
      "📌 Dùng để phủ định mạnh mẽ hành vi (B) vì chủ thể không ở trạng thái (A). Thường mang tính chỉ trích.",
    ],
    more: [
      "🧩 N + じゃ(では)あるまいし",
      "⚖️ ～でもあるまい (Không còn là lúc... - trang trọng hơn)",
      "💬 Văn nói, suồng sã.",
      "📝 ví dụ",
      "・子供じゃあるまいし、そんなことで泣くな",
      "・初めて___、失敗しても仕方がない",
    ],
    questions: [
      {
        id: "18-1",
        content: "子供___、わがままを言ってはいけない",
        answers: ["じゃあるまいし", "のであるから", "にあたって", "ともなると"],
        correctAnswer: 0,
        memo: [
          "じゃあるまいし: 'Đâu phải là... mà'. Phủ định hành vi (vòi vĩnh) vì đã qua trạng thái (trẻ con). (Đúng)",
          "のであるから: 'Vì là...', không phù hợp.",
          "にあたって: 'Nhân dịp...', không phù hợp.",
          "ともなると: 'Cứ hễ là...', không phù hợp.",
        ],
      },
      {
        id: "18-2",
        content: "初めての経験___、失敗しても仕方がない",
        answers: [
          "じゃあるまいし",
          "だからといって",
          "とあっては",
          "のことだから",
        ],
        correctAnswer: 2,
        memo: [
          "じゃあるまいし: 'Đâu phải là...', không phù hợp.",
          "だからといって: 'Cho dù nói là...', không phù hợp.",
          "とあっては: 'Nếu ở trong tình huống... thì'. Nhấn mạnh tính đặc biệt của tình huống (lần đầu tiên) để biện minh (thất bại cũng đành chịu). (Đúng)",
          "のことだから: 'Vì là...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～どうにもならない／できない",
    back: [
      "✨ Không làm gì được, bất lực (Hoàn toàn không thể làm gì, dù cố gắng)",
      "・Ví dụ: Tình hình trở nên tồi tệ đến mức không thể làm gì được nữa.",
      "📌 Nhấn mạnh sự hoàn toàn bất lực, không có cách nào để thay đổi hoặc giải quyết vấn đề.",
    ],
    more: [
      "🧩 どうにも + V (thể khả năng) ない / N + どうにもならない",
      "⚖️ ～お手上げだ (Bó tay), ～はどうすることもできない (Không thể làm gì được)",
      "💬 Văn nói, diễn tả sự bất lực cá nhân.",
      "📝 ví dụ",
      "・状況は悪化して、もうどうにもならない",
      "・この機械は壊れていて、どうにも直せない",
    ],
    questions: [
      {
        id: "19-1",
        content: "状況は悪化して、もう___",
        answers: [
          "どうにもならない",
          "どうしようもない",
          "どうすることもできない",
          "お手上げだ",
        ],
        correctAnswer: 0,
        memo: [
          "どうにもならない: 'Hoàn toàn không làm gì được'. Phù hợp nhất. (Đúng)",
          "どうしようもない: 'Không còn cách nào khác'.",
          "どうすることもできない: 'Không thể làm gì được'.",
          "お手上げだ: 'Bó tay'.",
        ],
      },
      {
        id: "19-2",
        content: "この問題は複雑すぎて、私一人の力では___",
        answers: [
          "解決するわけにはいかない",
          "解決しなくてはならない",
          "どうにも解決できない",
          "なんとか解決できる",
        ],
        correctAnswer: 2,
        memo: [
          "解決するわけにはいかない: 'Không thể giải quyết (vì nghĩa vụ)'.",
          "解決しなくてはならない: 'Phải giải quyết'.",
          "どうにも解決できない: 'Hoàn toàn không thể giải quyết'. (Đúng)",
          "なんとか解決できる: 'Bằng cách nào đó có thể giải quyết'.",
        ],
      },
    ],
  },
  {
    front: "～の至り（いたり）",
    back: [
      "✨ Vô cùng…, cực kỳ… (Mức độ cao nhất, thường dùng cho cảm xúc tích cực, trang trọng)",
      "・Ví dụ: Tôi vô cùng vinh dự.",
      "📌 Luôn đi kèm với danh từ chỉ cảm xúc tích cực (vinh dự, kinh ngạc) để nhấn mạnh mức độ cao nhất.",
    ],
    more: [
      "🧩 N + の至り",
      "⚖️ ～極まる／極まりない (Cực kỳ - thường tiêu cực), ～限りだ (Vô cùng - dùng cho cảm xúc mạnh)",
      "💬 Văn viết, cực kỳ trang trọng.",
      "📝 ví dụ",
      "・このような栄誉をいただき、光栄の至りです",
      "・彼の失敗は、痛恨の至りだ",
    ],
    questions: [
      {
        id: "20-1",
        content: "このような栄誉をいただき、光栄___",
        answers: ["の至りです", "きわまりない", "ばかりです", "でたまらない"],
        correctAnswer: 0,
        memo: [
          "の至りです: 'Vô cùng...'. Đi kèm với danh từ tích cực (光栄 - vinh dự). (Đúng)",
          "きわまりない: 'Cực kỳ' (thường là tiêu cực).",
          "ばかりです: 'Chỉ...', không phù hợp.",
          "でたまらない: 'Không chịu nổi', dùng cho cảm xúc khó kìm nén.",
        ],
      },
      {
        id: "20-2",
        content: "彼の考え方は、身勝手___",
        answers: ["の至りだ", "極まりない", "に限る", "だけましだ"],
        correctAnswer: 1,
        memo: [
          "の至りだ: 'Vô cùng' (thường là tích cực).",
          "極まりない: 'Cực kỳ' (thường là tiêu cực). Phù hợp với tính từ tiêu cực '身勝手' (ích kỷ). (Đúng)",
          "に限る: 'Chỉ có...', không phù hợp.",
          "だけましだ: '... là còn tốt chán', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～いかんだ／いかんで／いかんによって",
    back: [
      "✨ Tùy theo / Dựa vào (Kết quả thay đổi tùy thuộc vào điều kiện A)",
      "・Ví dụ: Kết quả sẽ thay đổi tùy thuộc vào thái độ của bạn.",
      "📌 Nhấn mạnh rằng hành động, kết quả (B) sẽ thay đổi phụ thuộc vào điều kiện (A).",
    ],
    more: [
      "🧩 N + いかんだ／いかんで／いかんによって",
      "⚖️ ～によって (Tùy theo), ～次第で (Tùy thuộc vào)",
      "💬 Văn viết, trang trọng.",
      "📝 ví dụ",
      "・努力のいかんで、成績は変わる",
      "・手続きのいかんにかかわらず、早急に対応します (Không kể/Không tùy thuộc vào thủ tục...)",
    ],
    questions: [
      {
        id: "21-1",
        content: "努力の___、成績は変わる",
        answers: ["いかんだ", "次第で", "に応じて", "にかかわらず"],
        correctAnswer: 0,
        memo: [
          "いかんだ: 'Tùy theo'. Nhấn mạnh kết quả (thành tích) sẽ thay đổi tùy thuộc vào điều kiện (nỗ lực). (Đúng)",
          "次第で: 'Tùy thuộc vào' (thông thường).",
          "に応じて: 'Tương ứng với...', không phù hợp.",
          "にかかわらず: 'Không phân biệt...', ngược nghĩa.",
        ],
      },
      {
        id: "21-2",
        content: "手続きの___、早急に対応します",
        answers: [
          "いかんにかかわらず",
          "いかんだ",
          "いかんによっては",
          "次第で",
        ],
        correctAnswer: 0,
        memo: [
          "いかんにかかわらず: 'Không kể/Không tùy thuộc vào...'. Nhấn mạnh sự không phụ thuộc vào điều kiện. (Đúng)",
          "いかんだ: 'Tùy theo...', không phù hợp.",
          "いかんによっては: 'Tùy theo... thì', không phù hợp.",
          "次第で: 'Tùy thuộc vào' (thông thường).",
        ],
      },
    ],
  },
  {
    front: "～ゆえに（故に）",
    back: [
      "✨ Vì… nên (Chỉ lý do, nguyên nhân, trang trọng)",
      "・Ví dụ: Vì lý do đó nên tôi đã đi đến kết luận này.",
      "📌 Dùng để chỉ nguyên nhân, lý do một cách trang trọng, thường trong văn viết, báo chí.",
    ],
    more: [
      "🧩 N / Vる / Aい / Naである + ゆえに",
      "⚖️ ～ため (Vì - trang trọng), ～からこそ (Chính vì - nhấn mạnh lý do)",
      "💬 Văn viết, cực kỳ trang trọng.",
      "📝 ví dụ",
      "・それゆえに、この結論に至った",
      "・貧しさゆえに、彼は犯罪に手を染めた",
    ],
    questions: [
      {
        id: "22-1",
        content: "貧しさ___、彼は犯罪に手を染めた",
        answers: ["ゆえに", "のために", "からこそ", "によって"],
        correctAnswer: 0,
        memo: [
          "ゆえに: 'Vì... nên'. Chỉ nguyên nhân một cách trang trọng (vì nghèo mà phạm tội). (Đúng)",
          "のために: 'Vì...', trang trọng nhưng ゆえに mạnh hơn.",
          "からこそ: 'Chính vì...', nhấn mạnh lý do tích cực.",
          "によって: 'Tùy theo/Bằng cách...', không phù hợp.",
        ],
      },
      {
        id: "22-2",
        content: "一生懸命努力した___、成功することができた",
        answers: ["ゆえに", "からこそ", "のことで", "にもかかわらず"],
        correctAnswer: 1,
        memo: [
          "ゆえに: 'Vì... nên'.",
          "からこそ: 'Chính vì... nên'. Nhấn mạnh lý do tích cực (chính vì nỗ lực nên mới thành công). (Đúng)",
          "のことで: 'Về việc...', không phù hợp.",
          "にもかかわらず: 'Mặc dù...', ngược nghĩa.",
        ],
      },
    ],
  },
  {
    front: "～わけても",
    back: [
      "✨ Đặc biệt là (Nhấn mạnh một trường hợp nổi bật, đặc biệt nhất trong một phạm vi)",
      "・Ví dụ: Tôi thích tất cả các món ăn Nhật, đặc biệt là sushi.",
      "📌 Dùng để chọn ra một trường hợp đặc biệt, nổi bật nhất trong một nhóm.",
    ],
    more: [
      "🧩 N / Vる + わけても",
      "⚖️ ～特に (Đặc biệt), ～なかんずく (Đặc biệt là - trang trọng nhất)",
      "💬 Văn viết, trang trọng.",
      "📝 ví dụ",
      "・日本料理はどれも好きだが、わけても寿司が好きだ",
      "・今回の会議では、わけても環境問題について深く議論したい",
    ],
    questions: [
      {
        id: "23-1",
        content: "日本料理はどれも好きだが、___寿司が好きだ",
        answers: ["なかんずく", "とりわけ", "わけても", "ことに"],
        correctAnswer: 2,
        memo: [
          "なかんずく: 'Đặc biệt là' (trang trọng nhất).",
          "とりわけ: 'Đặc biệt là' (văn nói/viết).",
          "わけても: 'Đặc biệt là'. Phù hợp. (Đúng)",
          "ことに: 'Đặc biệt là' (thường dùng để nhấn mạnh cảm xúc).",
        ],
      },
      {
        id: "23-2",
        content: "今回の会議では、___環境問題について深く議論したい",
        answers: ["特に", "わけても", "なかんずく", "にわたって"],
        correctAnswer: 0,
        memo: [
          "特に: 'Đặc biệt'. Phù hợp nhất cho ngữ cảnh hội họp, nhấn mạnh điểm cần tập trung. (Đúng)",
          "わけても: 'Đặc biệt là'.",
          "なかんずく: 'Đặc biệt là' (trang trọng nhất).",
          "にわたって: 'Trong suốt...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～仮に…とすれば／としたら／とする",
    back: [
      "✨ Nếu…, giả sử… (Đưa ra một giả định không có thực hoặc khó xảy ra)",
      "・Ví dụ: Giả sử bạn là tôi thì bạn sẽ làm gì?",
      "📌 Dùng để đặt ra một giả định (thường là khó xảy ra) để suy luận hoặc đặt câu hỏi.",
    ],
    more: [
      "🧩 仮に + Vる / Vた + とすれば／としたら／とする",
      "⚖️ ～としても (Ngay cả nếu...), ～たら (Nếu - thông thường)",
      "💬 Văn viết, trang trọng, dùng trong lập luận, suy luận.",
      "📝 ví dụ",
      "・仮にあなたが私だったとすれば、どうしますか",
      "・仮にこの計画が失敗したとして、次の一手はどうするべきか",
    ],
    questions: [
      {
        id: "24-1",
        content: "___あなたが私だったと___、どうしますか",
        answers: [
          "仮に/したら",
          "もし/としたら",
          "万一/ならば",
          "たとえ/としても",
        ],
        correctAnswer: 0,
        memo: [
          "仮に/したら: 'Giả sử... thì'. Đặt giả định (thường là khó xảy ra). (Đúng)",
          "もし/としたら: 'Nếu... thì', không trang trọng bằng 仮に.",
          "万一/ならば: 'Vạn nhất/Nếu lỡ...', không phù hợp.",
          "たとえ/としても: 'Ngay cả nếu...', không phù hợp.",
        ],
      },
      {
        id: "24-2",
        content: "___失敗した___、次の一手はどうするべきか",
        answers: [
          "たとえ/としても",
          "仮に/としても",
          "万一/ならば",
          "もし/ならば",
        ],
        correctAnswer: 1,
        memo: [
          "たとえ/としても: 'Ngay cả nếu... thì', nhấn mạnh sự nhượng bộ.",
          "仮に/としても: 'Giả sử... thì'. Đặt giả định (thất bại) để suy luận. (Đúng)",
          "万一/ならば: 'Vạn nhất/Nếu lỡ...', không phù hợp.",
          "もし/ならば: 'Nếu... thì' (thông thường).",
        ],
      },
    ],
  },
  {
    front: "～なりと",
    back: [
      "✨ Bất cứ… cũng được (Đưa ra lựa chọn không quan trọng, nhấn mạnh sự tùy ý)",
      "・Ví dụ: Bất cứ ai cũng được, hãy nói cho tôi nghe.",
      "📌 Đưa ra lựa chọn bất kỳ, nhấn mạnh sự tùy ý, thường mang ý 'không cần quá quan trọng về đối tượng'.",
    ],
    more: [
      "🧩 N + なりと",
      "⚖️ ～でもいい (Cũng được), ～にかぎらず (Không chỉ... mà còn)",
      "💬 Văn nói suồng sã.",
      "📝 ví dụ",
      "・誰か___、私に話しかけてください",
      "・ご意見___、お聞かせください (Trang trọng)",
    ],
    questions: [
      {
        id: "25-1",
        content: "誰か___、私に話しかけてください",
        answers: ["にかぎり", "なりと", "でさえ", "でも"],
        correctAnswer: 1,
        memo: [
          "にかぎり: 'Chỉ riêng...', không phù hợp.",
          "なりと: 'Bất cứ... cũng được'. (Bất cứ ai cũng được, hãy nói với tôi). (Đúng)",
          "でさえ: 'Ngay cả...', không phù hợp.",
          "でも: 'Hoặc là...', không phù hợp.",
        ],
      },
      {
        id: "25-2",
        content: "ご意見___、お聞かせください",
        answers: ["なりと", "でさえ", "すら", "に限らず"],
        correctAnswer: 0,
        memo: [
          "なりと: 'Bất cứ... cũng được'. Trang trọng, dùng để mời ý kiến. (Đúng)",
          "でさえ: 'Ngay cả...', không phù hợp.",
          "すら: 'Ngay cả...', không phù hợp.",
          "に限らず: 'Không chỉ...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～ぬばかり",
    back: [
      "✨ Như muốn…, như sắp… (Diễn tả trạng thái, hành động dường như sắp xảy ra, nhưng chưa xảy ra)",
      "・Ví dụ: Cô ấy cười lớn như muốn nói 'Tôi đã thắng'.",
      "📌 Diễn tả sự giống nhau, dường như sắp xảy ra hoặc có vẻ như là vậy.",
    ],
    more: [
      "🧩 Vない → Vぬ + ばかりに / の",
      "⚖️ ～ようだ (Dường như), ～そう (Sắp...)",
      "💬 Văn viết, trang trọng.",
      "📝 ví dụ",
      "・彼女は「勝った」とでも言うぬばかりに、大声で笑った",
      "・別れを惜しむ___、いつまでも手を振り続けた",
    ],
    questions: [
      {
        id: "26-1",
        content: "彼は「帰れ」とでも言う___、不機嫌な顔をした",
        answers: ["ぬばかりに", "ように", "そうに", "ばかりに"],
        correctAnswer: 0,
        memo: [
          "ぬばかりに: 'Như muốn/như sắp...'. Dùng Vぬ (帰らぬ) để diễn tả trạng thái 'như muốn nói'. (Đúng)",
          "ように: 'Như là', thông thường.",
          "そうに: 'Có vẻ sắp', không phù hợp.",
          "ばかりに: 'Chính vì...', không phù hợp.",
        ],
      },
      {
        id: "26-2",
        content: "別れを惜しむ___、いつまでも手を振り続けた",
        answers: ["ぬばかりに", "ように", "かのように", "ばかりに"],
        correctAnswer: 2,
        memo: [
          "ぬばかりに: 'Như muốn/như sắp...'.",
          "ように: 'Như là', thông thường.",
          "かのように: 'Cứ như là...'. Phù hợp nhất khi diễn tả hành động có vẻ giống một cảm xúc. (Đúng)",
          "ばかりに: 'Chính vì...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～とおもうまもなく（と思う間もなく）",
    back: [
      "✨ Bất ngờ, ngay lập tức (Hành động B xảy ra ngay sau khi có suy nghĩ/ý định A)",
      "・Ví dụ: Vừa mới nghĩ 'Phải trả lời' thì điện thoại đã reo.",
      "📌 Nhấn mạnh sự tức thì, hành động B xảy ra ngay sau suy nghĩ A, không có thời gian để thực hiện suy nghĩ đó.",
    ],
    more: [
      "🧩 Vる + とおもうまもなく",
      "⚖️ ～が早いか (Ngay sau khi), ～とたんに (Ngay sau khi)",
      "💬 Văn nói, diễn tả sự bất ngờ.",
      "📝 ví dụ",
      "・返事をしようと思うまもなく、電話が鳴った",
      "・「出発だ」と言うと思うまもなく、バスは動き出した",
    ],
    questions: [
      {
        id: "27-1",
        content: "返事をしよう___、電話が鳴った",
        answers: ["とおもうまもなく", "とたんに", "が早いか", "なり"],
        correctAnswer: 0,
        memo: [
          "とおもうまもなく: 'Vừa mới nghĩ... thì ngay lập tức'. Nhấn mạnh hành động B xảy ra ngay sau suy nghĩ A. (Đúng)",
          "とたんに: 'Ngay sau khi' (thường là hành động vật lý).",
          "が早いか: 'Ngay sau khi' (thường là hành động vật lý).",
          "なり: 'Ngay sau khi' (thường là hành động bất ngờ của cá nhân).",
        ],
      },
      {
        id: "27-2",
        content: "ドアを開けた___、猫が飛び出してきた。",
        answers: ["とたんに", "とおもうまもなく", "が早いか", "なり"],
        correctAnswer: 0,
        memo: [
          "とたんに: 'Ngay sau khi'. Diễn tả hành động B xảy ra tức thì sau hành động A. Phù hợp nhất. (Đúng)",
          "とおもうまもなく: Dùng với suy nghĩ, ý định.",
          "が早いか: 'Ngay sau khi' (thường là hành động bản năng).",
          "なり: 'Ngay sau khi' (thường là hành động bất ngờ của cá nhân).",
        ],
      },
    ],
  },
  {
    front: "ってば",
    back: [
      "✨ Tôi nói là…, mà… (Nhấn mạnh lời nói, ý kiến của người nói, thường là để nhắc lại hoặc phàn nàn)",
      "・Ví dụ: Tôi nói là không biết mà.",
      "📌 Dùng để nhấn mạnh, nhắc lại lời nói, ý kiến của mình, thường mang sắc thái bực bội hoặc thúc giục.",
    ],
    more: [
      "🧩 Vる / N / Aい / Na + ってば",
      "⚖️ ～と言っているのに (Mặc dù đã nói...), ～のに (Mặc dù... nhưng)",
      "💬 Văn nói suồng sã, mang tính cá nhân.",
      "📝 ví dụ",
      "・知らないってば！何回言えばわかるの？",
      "・もう行くってば。急かさないでよ",
    ],
    questions: [
      {
        id: "28-1",
        content: "知らない___！何回言えばわかるの？",
        answers: ["といっても", "ってば", "にしても", "にもかかわらず"],
        correctAnswer: 1,
        memo: [
          "といっても: 'Mặc dù nói là...', không phù hợp.",
          "ってば: 'Tôi nói là..., mà...'. Nhấn mạnh lời nói, thường dùng để bực bội, thúc giục. (Đúng)",
          "にしても: 'Dù là...', không phù hợp.",
          "にもかかわらず: 'Mặc dù...', không phù hợp.",
        ],
      },
      {
        id: "28-2",
        content: "何度も言っている___、彼は聞いてくれない。",
        answers: ["ってば", "のに", "からといって", "に際して"],
        correctAnswer: 1,
        memo: [
          "ってば: 'Tôi nói là..., mà...'.",
          "のに: 'Mặc dù... nhưng'. Phù hợp nhất để chỉ sự thất vọng vì hành động không được đáp ứng (Mặc dù đã nói nhiều lần nhưng anh ta không nghe). (Đúng)",
          "からといって: 'Cho dù nói là...', không phù hợp.",
          "に際して: 'Nhân dịp...', không phù hợp.",
        ],
      },
    ],
  },
  {
    front: "～のなんのと",
    back: [
      "✨ Rằng… này nọ, chẳng hạn (Liệt kê các lời phàn nàn, lý do một cách lộn xộn, không quan trọng)",
      "・Ví dụ: Cô ấy lúc nào cũng than vãn rằng đau đầu này nọ.",
      "📌 Liệt kê các lý do, lời phàn nàn một cách lộn xộn, không chính thức, thường thể hiện sự bực mình của người nói.",
    ],
    more: [
      "🧩 Vる / N / Aい / Na + だ + のなんのと",
      "⚖️ ～だの～だの (Nào là... nào là... - tiêu cực hơn), ～やら～やら (Nào là... nào là... - lộn xộn)",
      "💬 Văn nói suồng sã, mang tính phàn nàn.",
      "📝 ví dụ",
      "・彼は頭が痛いのなんのと理由をつけて、仕事を休んだ",
      "・暑いだの寒いだののなんのと、文句ばかり言っている",
    ],
    questions: [
      {
        id: "29-1",
        content: "彼は頭が痛いの___理由をつけて、仕事を休んだ",
        answers: ["なんのという", "なんのと", "やら", "だの"],
        correctAnswer: 1,
        memo: [
          "なんのという: Sai cấu trúc.",
          "なんのと: 'Rằng... này nọ'. Phù hợp nhất để liệt kê lý do/phàn nàn một cách lộn xộn. (Đúng)",
          "やら: 'Nào là... nào là...' (liệt kê lộn xộn).",
          "だの: 'Nào là... nào là...' (phàn nàn, chỉ trích).",
        ],
      },
      {
        id: "29-2",
        content:
          "彼はいつも給料が安い___、仕事がつらい___と愚痴ばかり言っている",
        answers: ["やら/やら", "だの/だの", "わ/わ", "のなんのと"],
        correctAnswer: 1,
        memo: [
          "やら/やら: Liệt kê lộn xộn, không mang ý phàn nàn mạnh.",
          "だの/だの: 'Nào là... nào là...'. Dùng để liệt kê những lời phàn nàn, chỉ trích. (Đúng)",
          "わ/わ: Liệt kê các sự kiện tiêu cực xảy ra liên tiếp.",
          "のなんのと: Thường dùng để kết thúc liệt kê hơn.",
        ],
      },
    ],
  },
  {
    front: "～といっても言い過ぎではない",
    back: [
      "✨ Dẫu có nói… cũng không quá (Khẳng định mạnh mẽ một sự thật, đôi khi có phần phóng đại)",
      "・Ví dụ: Anh ấy là người quan trọng nhất trong đội. Dẫu có nói là trụ cột cũng không quá lời.",
      "📌 Dùng để khẳng định mạnh mẽ một sự thật, thường là một đánh giá cao về đối tượng.",
    ],
    more: [
      "🧩 N / Vる / Aい / Naである + といっても言い過ぎではない",
      "⚖️ ～にほかならない (Chính là, không gì khác là), ～といっても間違いない (Nói là... thì không sai)",
      "💬 Văn viết, trang trọng.",
      "📝 ví dụ",
      "・彼はチームで最も重要な人物だ。大黒柱といっても言い過ぎではない",
      "・この技術は、世界を変える発明といっても言い過ぎではない",
    ],
    questions: [
      {
        id: "30-1",
        content: "この技術は、世界を変える発明___",
        answers: [
          "といっても過言ではない",
          "といっても言い過ぎではない",
          "というわけだ",
          "にすぎない",
        ],
        correctAnswer: 1,
        memo: [
          "といっても過言ではない: 'Nói là... thì không quá lời'. Đồng nghĩa với といっても言い過ぎではない. (Đúng)",
          "といっても言い過ぎではない: 'Dẫu có nói... cũng không quá'. (Đúng)",
          "というわけだ: 'Nói tóm lại là...', không phù hợp.",
          "にすぎない: 'Chỉ là...', không phù hợp.",
        ],
      },
      {
        id: "30-2",
        content: "彼の努力は想像を絶する。まさに努力の化身___。",
        answers: [
          "にほかならない",
          "といっても言い過ぎではない",
          "といっても間違いない",
          "である",
        ],
        correctAnswer: 0,
        memo: [
          "にほかならない: 'Chính là/Không gì khác là...'. Khẳng định một cách tuyệt đối (anh ấy chính là hiện thân của sự nỗ lực). Phù hợp nhất. (Đúng)",
          "といっても言い過ぎではない: 'Dẫu có nói... cũng không quá', cũng đúng nhưng にほかならない nhấn mạnh bản chất hơn.",
          "といっても間違いない: 'Nói là... thì không sai', cũng đúng.",
          "である: 'Là', không nhấn mạnh.",
        ],
      },
    ],
  },
];
