import { Edge } from "reactflow";

export type RoadmapStatus = "todo" | "doing" | "done";

export interface RoadmapNodeMeta {
  id: string;
  label: string;
  description: string;
  status: RoadmapStatus;
  main: boolean;
  x: number;
  y: number;
  href?: string;
}

export interface RoadmapNodeData extends RoadmapNodeMeta {
  status: RoadmapStatus;
}

export const BASE_META: RoadmapNodeMeta[] = [
  {
    id: "main-words",
    label: "Từ vựng",
    description: "Học từ vựng theo 新完全マスター ",
    status: "todo",
    main: true,
    x: 462,
    y: -4,
  },
  {
    id: "word-1",
    label: "Bài 1",
    description: "性格・人柄・個性 (Tính cách)",
    status: "todo",
    main: false,
    x: 900,
    y: -298,
    href: "/words/n1/page1",
  },
  {
    id: "word-2",
    label: "Bài 2",
    description: "人間関係・付き合い・恋愛 (Quan hệ & cảm xúc)",
    status: "todo",
    main: false,
    x: 900,
    y: -208,
    href: "/words/n1/page2",
  },
  {
    id: "word-3",
    label: "Bài 3",
    description: "料理・食べ物・味・匂い (Ẩm thực)",
    status: "todo",
    main: false,
    x: 900,
    y: -118,
    href: "/words/n1/page3",
  },
  {
    id: "word-4",
    label: "Bài 4",
    description: "住居 (Nhà ở)",
    status: "todo",
    main: false,
    x: 900,
    y: -28,
    href: "/words/n1/page4",
  },
  {
    id: "word-5",
    label: "Bài 5",
    description: "病気・治療 (Bệnh tật & điều trị)",
    status: "todo",
    main: false,
    x: 900,
    y: 62,
    href: "/words/n1/page5",
  },
  {
    id: "word-6",
    label: "Bài 6",
    description: "健康・芸術 (Sức khỏe & Nghệ thuật)",
    status: "todo",
    main: false,
    x: 1355,
    y: -298,
    href: "/words/n1/page6",
  },
  {
    id: "word-7",
    label: "Bài 7",
    description: "教育 (Giáo dục)",
    status: "todo",
    main: false,
    x: 1355,
    y: -208,
    href: "/words/n1/page7",
  },
  {
    id: "word-8",
    label: "Bài 8",
    description: "仕事・職業 (Công việc & Nghề nghiệp)",
    status: "todo",
    main: false,
    x: 1355,
    y: -118,
    href: "/words/n1/page8",
  },
  {
    id: "word-9",
    label: "Bài 9",
    description: "発表・マスコミ (Trình bày & Truyền thông)",
    status: "todo",
    main: false,
    x: 1355,
    y: -28,
    href: "/words/n1/page9",
  },
  {
    id: "word-10",
    label: "Bài 10",
    description: "性格・人柄・個性・人間関係 (Tính cách & Quan hệ)",
    status: "todo",
    main: false,
    x: 1355,
    y: 62,
    href: "/words/n1/page10",
  },
  {
    id: "word-11",
    label: "Bài 11",
    description: "料理・食べ物・育児・住居 (Ẩm thực & Nuôi con & Nhà ở)",
    status: "todo",
    main: false,
    x: 1810,
    y: -298,
    href: "/words/n1/page11",
  },
  {
    id: "word-12",
    label: "Bài 12",
    description: "病気・治療・健康・芸術 (Bệnh tật & Sức khỏe & Nghệ thuật)",
    status: "todo",
    main: false,
    x: 1810,
    y: -208,
    href: "/words/n1/page12",
  },
  {
    id: "word-13",
    label: "Bài 13",
    description: "スポーツ (Thể thao)",
    status: "todo",
    main: false,
    x: 1810,
    y: -118,
    href: "/words/n1/page13",
  },
  {
    id: "word-14",
    label: "Bài 14",
    description: "学校・教育 (Trường học & Giáo dục)",
    status: "todo",
    main: false,
    x: 1810,
    y: -28,
    href: "/words/n1/page14",
  },
  {
    id: "word-15",
    label: "Bài 15",
    description: "仕事・職業 (Công việc & Nghề nghiệp)",
    status: "todo",
    main: false,
    x: 1810,
    y: 62,
    href: "/words/n1/page15",
  },
  {
    id: "word-16",
    label: "Bài 16",
    description: "メディア・経済・産業 (Truyền thông & Kinh tế & Sản nghiệp)",
    status: "todo",
    main: false,
    x: 2265,
    y: -298,
    href: "/words/n1/page16",
  },
  {
    id: "word-17",
    label: "Bài 17",
    description: "政治・法律・歴史 (Chính trị & Pháp luật & Lịch sử)",
    status: "todo",
    main: false,
    x: 2265,
    y: -208,
    href: "/words/n1/page17",
  },
  {
    id: "word-18",
    label: "Bài 18",
    description: "格差社会・少子高齢化 (Chênh lệch xã hội & Già hóa dân số)",
    status: "todo",
    main: false,
    x: 2265,
    y: -118,
    href: "/words/n1/page18",
  },
  {
    id: "word-19",
    label: "Bài 19",
    description:
      "気象・地形・天体・機械 (Thời tiết & Địa hình & Thiên thể & Máy móc)",
    status: "todo",
    main: false,
    x: 2265,
    y: -28,
    href: "/words/n1/page19",
  },
  {
    id: "word-20",
    label: "Bài 20",
    description: "時間・空間・関係 (Thời gian & Không gian & Mối quan hệ)",
    status: "todo",
    main: false,
    x: 2265,
    y: 62,
    href: "/words/n1/page20",
  },
  {
    id: "word-21",
    label: "Bài 21",
    description: "変化・関係・由緒 (Biến đổi & Mối quan hệ)",
    status: "todo",
    main: false,
    x: 2720,
    y: -298,
    href: "/words/n1/page21",
  },
  {
    id: "word-22",
    label: "Bài 22",
    description: "意味がたくさんある言葉 23 (Từ nhiều nghĩa - 1)",
    status: "todo",
    main: false,
    x: 2720,
    y: -208,
    href: "/words/n1/page22",
  },
  {
    id: "word-23",
    label: "Bài 23",
    description: "意味がたくさんある言葉 24 (Từ nhiều nghĩa - 2)",
    status: "todo",
    main: false,
    x: 2720,
    y: -118,
    href: "/words/n1/page23",
  },
  {
    id: "word-24",
    label: "Bài 24",
    description: "さらう・しのぐ・断つ・絶つ・弾む・ふるまう",
    status: "todo",
    main: false,
    x: 2720,
    y: -28,
    href: "/words/n1/page24",
  },
  {
    id: "word-25",
    label: "Bài 25",
    description: "副詞・形容詞 (Phó từ & Tính từ đặc biệt)",
    status: "todo",
    main: false,
    x: 2720,
    y: 62,
    href: "/words/n1/page25",
  },
  {
    id: "word-26",
    label: "Bài 26",
    description:
      "形が似ている言葉 - 規・発・補・賛・弁・持続 (Từ hình giống nhau)",
    status: "todo",
    main: false,
    x: 3175,
    y: -298,
    href: "/words/n1/page26",
  },
  {
    id: "word-27",
    label: "Bài 27",
    description: "形容詞・動詞グループ (Nhóm tính từ & động từ)",
    status: "todo",
    main: false,
    x: 3175,
    y: -208,
    href: "/words/n1/page27",
  },
  {
    id: "word-28",
    label: "Bài 28",
    description: "副詞 - 程度・様子 (Phó từ mức độ & trạng thái)",
    status: "todo",
    main: false,
    x: 3175,
    y: -118,
    href: "/words/n1/page28",
  },
  {
    id: "word-29",
    label: "Bài 29",
    description: "副詞 - 時間・推量 (Phó từ thời gian & suy đoán)",
    status: "todo",
    main: false,
    x: 3175,
    y: -28,
    href: "/words/n1/page29",
  },
  {
    id: "word-30",
    label: "Bài 30",
    description: "副詞 - 方法・範囲 (Phó từ phương pháp & phạm vi)",
    status: "todo",
    main: false,
    x: 3175,
    y: 62,
    href: "/words/n1/page30",
  },
  {
    id: "word-31",
    label: "Bài 31",
    description: "副詞 - 態度・意志 (Phó từ thái độ & ý chí)",
    status: "todo",
    main: false,
    x: 3630,
    y: -298,
    href: "/words/n1/page31",
  },
  {
    id: "word-32",
    label: "Bài 32",
    description: "副詞 - 様子・状態 (Phó từ trạng thái - tổng hợp)",
    status: "todo",
    main: false,
    x: 3630,
    y: -208,
    href: "/words/n1/page32",
  },
  {
    id: "main-grammar",
    label: "Ngữ pháp",
    description: "Học ngữ pháp theo 新完全マスター ",
    status: "todo",
    main: true,
    x: 462,
    y: 132,
  },
  {
    id: "grammar-1",
    label: "Bài 1",
    description: "時間関係 (Quan hệ thời gian)",
    status: "todo",
    main: false,
    x: -10,
    y: 314,
    href: "/grammar/n1/page1",
  },
  {
    id: "grammar-2",
    label: "Bài 2",
    description: "範囲の始まり・限度 (Phạm vi & Giới hạn)",
    status: "todo",
    main: false,
    x: -10,
    y: 224,
    href: "/grammar/n1/page2",
  },
  {
    id: "grammar-3",
    label: "Bài 3",
    description: "限定・付加 (Giới hạn & Thêm vào)",
    status: "todo",
    main: false,
    x: -10,
    y: 134,
    href: "/grammar/n1/page3",
  },
  {
    id: "grammar-4",
    label: "Bài 4",
    description: "例示 (Nêu ví dụ)",
    status: "todo",
    main: false,
    x: -10,
    y: 44,
    href: "/grammar/n1/page4",
  },
  {
    id: "grammar-5",
    label: "Bài 5",
    description: "関連・無関係 (Liên quan & Không liên quan)",
    status: "todo",
    main: false,
    x: -10,
    y: -46,
    href: "/grammar/n1/page5",
  },
  {
    id: "grammar-6",
    label: "Bài 6",
    description: "様子 (Trạng thái & Diễn biến)",
    status: "todo",
    main: false,
    x: -10,
    y: -136,
    href: "/grammar/n1/page6",
  },
  {
    id: "grammar-7",
    label: "Bài 7",
    description: "付随行動 (Hành động đi kèm)",
    status: "todo",
    main: false,
    x: -10,
    y: -226,
    href: "/grammar/n1/page7",
  },
  {
    id: "grammar-8",
    label: "Bài 8",
    description: "逆接 (Nghịch tiếp)",
    status: "todo",
    main: false,
    x: -10,
    y: -316,
    href: "/grammar/n1/page8",
  },
  {
    id: "grammar-9",
    label: "Bài 9",
    description: "条件 (Điều kiện)",
    status: "todo",
    main: false,
    x: -10,
    y: -406,
    href: "/grammar/n1/page9",
  },
  {
    id: "grammar-10",
    label: "Bài 10",
    description: "逆接条件 (Điều kiện nghịch tiếp)",
    status: "todo",
    main: false,
    x: -10,
    y: -496,
    href: "/grammar/n1/page10",
  },
  {
    id: "grammar-11",
    label: "Bài 11",
    description: "目的・手段 (Mục đích & Phương tiện)",
    status: "todo",
    main: false,
    x: -10,
    y: -586,
    href: "/grammar/n1/page11",
  },
  {
    id: "grammar-12",
    label: "Bài 12",
    description: "原因・理由 (Nguyên nhân & Lý do)",
    status: "todo",
    main: false,
    x: -10,
    y: -676,
    href: "/grammar/n1/page12",
  },
  {
    id: "grammar-13",
    label: "Bài 13",
    description: "可能・不可能・禁止 (Có thể & Không thể & Cấm)",
    status: "todo",
    main: false,
    x: -10,
    y: -766,
    href: "/grammar/n1/page13",
  },
  {
    id: "grammar-14",
    label: "Bài 14",
    description: "話題・評価の基準 (Chủ đề & Tiêu chuẩn đánh giá)",
    status: "todo",
    main: false,
    x: -10,
    y: -856,
    href: "/grammar/n1/page14",
  },
  {
    id: "grammar-15",
    label: "Bài 15",
    description: "比較対照 (So sánh & Đối chiếu)",
    status: "todo",
    main: false,
    x: -10,
    y: -946,
    href: "/grammar/n1/page15",
  },
  {
    id: "grammar-16",
    label: "Bài 16",
    description: "結末・最終の状態 (Kết quả & Trạng thái cuối cùng)",
    status: "todo",
    main: false,
    x: -10,
    y: -1036,
    href: "/grammar/n1/page16",
  },
  {
    id: "grammar-17",
    label: "Bài 17",
    description: "強調 (Nhấn mạnh)",
    status: "todo",
    main: false,
    x: -10,
    y: -1126,
    href: "/grammar/n1/page17",
  },
  {
    id: "grammar-18",
    label: "Bài 18",
    description: "主張・断定 (Khẳng định & Lập luận)",
    status: "todo",
    main: false,
    x: -10,
    y: -1216,
    href: "/grammar/n1/page18",
  },
  {
    id: "grammar-19",
    label: "Bài 19",
    description: "評価・感想 (Đánh giá & Cảm nhận)",
    status: "todo",
    main: false,
    x: -10,
    y: -1306,
    href: "/grammar/n1/page19",
  },
  {
    id: "grammar-20",
    label: "Bài 20",
    description: "心情・強制的思う (Tình cảm & Ý chí bắt buộc)",
    status: "todo",
    main: false,
    x: -10,
    y: -1396,
    href: "/grammar/n1/page20",
  },
  {
    id: "main-kanji",
    label: "Kanji",
    description: "Học kanji theo 新完全マスター漢字",
    status: "todo",
    main: true,
    x: 460,
    y: 450,
  },
  {
    id: "kanji-1",
    label: "Bài 1",
    description: "動詞Aレベル (1)～(3) (Động từ cấp A - Kun-yomi)",
    status: "todo",
    main: false,
    x: 886,
    y: 310,
    href: "/kanji/n1/page1",
  },
  {
    id: "kanji-2",
    label: "Bài 2",
    description: "動詞Aレベル (4)～(6) (Động từ cấp A - Kun-yomi)",
    status: "todo",
    main: false,
    x: 886,
    y: 410,
    href: "/kanji/n1/page2",
  },
  {
    id: "kanji-3",
    label: "Bài 3",
    description: "動詞Bレベル (1)～(3) (Động từ cấp B - Kun-yomi)",
    status: "todo",
    main: false,
    x: 886,
    y: 510,
    href: "/kanji/n1/page3",
  },
  {
    id: "kanji-4",
    label: "Bài 4",
    description: "動詞Bレベル (4)～(6) (Động từ cấp B - Kun-yomi)",
    status: "todo",
    main: false,
    x: 886,
    y: 610,
    href: "/kanji/n1/page4",
  },
  {
    id: "kanji-5",
    label: "Bài 5",
    description: "動詞Cレベル (1)～(3) (Động từ cấp C - Kun-yomi)",
    status: "todo",
    main: false,
    x: 1322,
    y: 310,
    href: "/kanji/n1/page5",
  },
  {
    id: "kanji-6",
    label: "Bài 6",
    description: "動詞Cレベル (4)～(6) (Động từ cấp C - Kun-yomi)",
    status: "todo",
    main: false,
    x: 1322,
    y: 410,
    href: "/kanji/n1/page6",
  },
  {
    id: "kanji-7",
    label: "Bài 7",
    description: "い形容詞 (1)・(2) (Tính từ đuôi い)",
    status: "todo",
    main: false,
    x: 1322,
    y: 510,
    href: "/kanji/n1/page7",
  },
  {
    id: "kanji-8",
    label: "Bài 8",
    description: "な形容詞・副詞・その他 (Tính từ な, Phó từ)",
    status: "todo",
    main: false,
    x: 1322,
    y: 610,
    href: "/kanji/n1/page8",
  },
  {
    id: "kanji-9",
    label: "Bài 9",
    description: "名詞(1)道具 (2)衣・衣服 (3)身体・感情",
    status: "todo",
    main: false,
    x: 1814,
    y: 310,
    href: "/kanji/n1/page9",
  },
  {
    id: "kanji-10",
    label: "Bài 10",
    description: "名詞(4)自然 (5)植物・食物 (6)建造物・形状",
    status: "todo",
    main: false,
    x: 1814,
    y: 410,
    href: "/kanji/n1/page10",
  },
  {
    id: "kanji-11",
    label: "Bài 11",
    description: "名詞(7)学生・生活 (8)経済・生活 (9)時間・空間",
    status: "todo",
    main: false,
    x: 1814,
    y: 510,
    href: "/kanji/n1/page11",
  },
  {
    id: "kanji-12",
    label: "Bài 12",
    description: "「する」がつく名詞 (1)",
    status: "todo",
    main: false,
    x: 1814,
    y: 610,
    href: "/kanji/n1/page12",
  },
  {
    id: "kanji-13",
    label: "Bài 13",
    description: "多くの言葉を作る漢字",
    status: "todo",
    main: false,
    x: 2260,
    y: 310,
    href: "/kanji/n1/page13",
  },
  {
    id: "kanji-14",
    label: "Bài 14",
    description: "「する」がつく名詞 (2)",
    status: "todo",
    main: false,
    x: 2260,
    y: 410,
    href: "/kanji/n1/page14",
  },
  {
    id: "kanji-15",
    label: "Bài 15",
    description: "「する」がつく名詞 (3)",
    status: "todo",
    main: false,
    x: 2260,
    y: 510,
    href: "/kanji/n1/page15",
  },
  {
    id: "kanji-16",
    label: "Bài 16",
    description: "「する」がつく名詞 (4)",
    status: "todo",
    main: false,
    x: 2260,
    y: 610,
    href: "/kanji/n1/page16",
  },
  {
    id: "kanji-17",
    label: "Bài 17",
    description: "な形容詞 (1)",
    status: "todo",
    main: false,
    x: 2706,
    y: 310,
    href: "/kanji/n1/page17",
  },
  {
    id: "kanji-18",
    label: "Bài 18",
    description: "な形容詞 (2)・副詞",
    status: "todo",
    main: false,
    x: 2706,
    y: 410,
    href: "/kanji/n1/page18",
  },
  {
    id: "kanji-19",
    label: "Bài 19",
    description: "名詞(1)身体・健康",
    status: "todo",
    main: false,
    x: 2706,
    y: 510,
    href: "/kanji/n1/page19",
  },
  {
    id: "kanji-20",
    label: "Bài 20",
    description: "名詞(2)建造物・日用品",
    status: "todo",
    main: false,
    x: 2706,
    y: 610,
    href: "/kanji/n1/page20",
  },
  {
    id: "kanji-21",
    label: "Bài 21",
    description: "名詞(3)人間関係・生涯",
    status: "todo",
    main: false,
    x: 3152,
    y: 310,
    href: "/kanji/n1/page21",
  },
  {
    id: "kanji-22",
    label: "Bài 22",
    description: "名詞(4)数量・範囲",
    status: "todo",
    main: false,
    x: 3152,
    y: 410,
    href: "/kanji/n1/page22",
  },
  {
    id: "kanji-23",
    label: "Bài 23",
    description: "名詞(5)言語・教育",
    status: "todo",
    main: false,
    x: 3152,
    y: 510,
    href: "/kanji/n1/page23",
  },
  {
    id: "kanji-24",
    label: "Bài 24",
    description: "名詞(6)犯罪・災害",
    status: "todo",
    main: false,
    x: 3152,
    y: 610,
    href: "/kanji/n1/page24",
  },
  {
    id: "kanji-25",
    label: "Bài 25",
    description: "名詞(7)政治・行政・国際関係",
    status: "todo",
    main: false,
    x: 3598,
    y: 310,
    href: "/kanji/n1/page25",
  },
  {
    id: "kanji-26",
    label: "Bài 26",
    description: "名詞(8)産業・交通",
    status: "todo",
    main: false,
    x: 3598,
    y: 410,
    href: "/kanji/n1/page26",
  },
  {
    id: "kanji-27",
    label: "Bài 27",
    description: "名詞(9)経済・流通",
    status: "todo",
    main: false,
    x: 3598,
    y: 510,
    href: "/kanji/n1/page27",
  },
  {
    id: "kanji-28",
    label: "Bài 28",
    description: "名詞(10)自然・科学・地理",
    status: "todo",
    main: false,
    x: 3598,
    y: 610,
    href: "/kanji/n1/page28",
  },
  {
    id: "kanji-29",
    label: "Bài 29",
    description: "名詞(11)思想・歴史",
    status: "todo",
    main: false,
    x: 4044,
    y: 310,
    href: "/kanji/n1/page29",
  },
  {
    id: "kanji-30",
    label: "Bài 30",
    description: "名詞(12)IT関連・娯楽",
    status: "todo",
    main: false,
    x: 4044,
    y: 410,
    href: "/kanji/n1/page30",
  },
  {
    id: "kanji-31",
    label: "Bài 31",
    description: "特別な読み方をする漢字の言葉",
    status: "todo",
    main: false,
    x: 4044,
    y: 510,
    href: "/kanji/n1/page31",
  },
  {
    id: "main-listening",
    label: "Nghe hiểu",
    description: "Luyện tập nghe theo chủ đề N1",
    status: "todo",
    main: true,
    x: 462,
    y: 700,
  },
  {
    id: "listening-1",
    label: "Luyện tập",
    description: "Nghe hiểu N1 - Luyện tập liên tục",
    status: "todo",
    main: false,
    x: 886,
    y: 700,
    href: "/listening/n1/newest",
  },
  {
    id: "main-reading",
    label: "Đọc hiểu",
    description: "Luyện tập đọc hiểu N1",
    status: "todo",
    main: true,
    x: 462,
    y: 900,
  },
  {
    id: "reading-1",
    label: "Bài 1",
    description: "Luyện tập 1 - Đọc hiểu",
    status: "todo",
    main: false,
    x: 886,
    y: 850,
    href: "/reading/n1/practice01",
  },
  {
    id: "reading-2",
    label: "Bài 2",
    description: "Luyện tập 2 - Đọc hiểu",
    status: "todo",
    main: false,
    x: 886,
    y: 950,
    href: "/reading/n1/practice02",
  },
  {
    id: "reading-3",
    label: "Bài 3",
    description: "Luyện tập 3 - Đọc hiểu",
    status: "todo",
    main: false,
    x: 886,
    y: 1050,
    href: "/reading/n1/practice03",
  },
];

export const BASE_EDGES: Edge[] = [
  {
    id: "edge-1",
    source: "main-words",
    target: "word-1",
  },
  { id: "e-word-2", source: "word-1", target: "word-2" },
  { id: "e-word-3", source: "word-2", target: "word-3" },
  { id: "e-word-4", source: "word-3", target: "word-4" },
  { id: "e-word-5", source: "word-4", target: "word-5" },
  { id: "e-word-6", source: "word-5", target: "word-6" },
  { id: "e-word-7", source: "word-6", target: "word-7" },
  { id: "e-word-8", source: "word-7", target: "word-8" },
  { id: "e-word-9", source: "word-8", target: "word-9" },
  { id: "e-word-10", source: "word-9", target: "word-10" },
  { id: "e-word-11", source: "word-10", target: "word-11" },
  { id: "e-word-12", source: "word-11", target: "word-12" },
  { id: "e-word-13", source: "word-12", target: "word-13" },
  { id: "e-word-14", source: "word-13", target: "word-14" },
  { id: "e-word-15", source: "word-14", target: "word-15" },
  { id: "e-word-16", source: "word-15", target: "word-16" },
  { id: "e-word-17", source: "word-16", target: "word-17" },
  { id: "e-word-18", source: "word-17", target: "word-18" },
  { id: "e-word-19", source: "word-18", target: "word-19" },
  { id: "e-word-20", source: "word-19", target: "word-20" },
  { id: "e-word-21", source: "word-20", target: "word-21" },
  { id: "e-word-22", source: "word-21", target: "word-22" },
  { id: "e-word-23", source: "word-22", target: "word-23" },
  { id: "e-word-24", source: "word-23", target: "word-24" },
  { id: "e-word-25", source: "word-24", target: "word-25" },
  { id: "e-word-26", source: "word-25", target: "word-26" },
  { id: "e-word-27", source: "word-26", target: "word-27" },
  { id: "e-word-28", source: "word-27", target: "word-28" },
  { id: "e-word-29", source: "word-28", target: "word-29" },
  { id: "e-word-30", source: "word-29", target: "word-30" },
  { id: "e-word-31", source: "word-30", target: "word-31" },
  { id: "e-word-32", source: "word-31", target: "word-32" },
  {
    id: "edge-main-1",
    source: "main-words",
    target: "main-grammar",
  },
  { id: "e-grammar-1", source: "main-grammar", target: "grammar-1" },
  { id: "e-grammar-1-2", source: "grammar-1", target: "grammar-2" },
  { id: "e-grammar-2-3", source: "grammar-2", target: "grammar-3" },
  { id: "e-grammar-3-4", source: "grammar-3", target: "grammar-4" },
  { id: "e-grammar-4-5", source: "grammar-4", target: "grammar-5" },
  { id: "e-grammar-5-6", source: "grammar-5", target: "grammar-6" },
  { id: "e-grammar-6-7", source: "grammar-6", target: "grammar-7" },
  { id: "e-grammar-7-8", source: "grammar-7", target: "grammar-8" },
  { id: "e-grammar-8-9", source: "grammar-8", target: "grammar-9" },
  { id: "e-grammar-9-10", source: "grammar-9", target: "grammar-10" },
  { id: "e-grammar-10-11", source: "grammar-10", target: "grammar-11" },
  { id: "e-grammar-11-12", source: "grammar-11", target: "grammar-12" },
  { id: "e-grammar-12-13", source: "grammar-12", target: "grammar-13" },
  { id: "e-grammar-13-14", source: "grammar-13", target: "grammar-14" },
  { id: "e-grammar-14-15", source: "grammar-14", target: "grammar-15" },
  { id: "e-grammar-15-16", source: "grammar-15", target: "grammar-16" },
  { id: "e-grammar-16-17", source: "grammar-16", target: "grammar-17" },
  { id: "e-grammar-17-18", source: "grammar-17", target: "grammar-18" },
  { id: "e-grammar-18-19", source: "grammar-18", target: "grammar-19" },
  { id: "e-grammar-19-20", source: "grammar-19", target: "grammar-20" },
  {
    id: "edge-main-kanji",
    source: "main-grammar",
    target: "main-kanji",
  },
  { id: "e-kanji-1", source: "main-kanji", target: "kanji-1" },
  { id: "e-kanji-1-2", source: "kanji-1", target: "kanji-2" },
  { id: "e-kanji-2-3", source: "kanji-2", target: "kanji-3" },
  { id: "e-kanji-3-4", source: "kanji-3", target: "kanji-4" },
  { id: "e-kanji-4-5", source: "kanji-4", target: "kanji-5" },
  { id: "e-kanji-5-6", source: "kanji-5", target: "kanji-6" },
  { id: "e-kanji-6-7", source: "kanji-6", target: "kanji-7" },
  { id: "e-kanji-7-8", source: "kanji-7", target: "kanji-8" },
  { id: "e-kanji-8-9", source: "kanji-8", target: "kanji-9" },
  { id: "e-kanji-9-10", source: "kanji-9", target: "kanji-10" },
  { id: "e-kanji-10-11", source: "kanji-10", target: "kanji-11" },
  { id: "e-kanji-11-12", source: "kanji-11", target: "kanji-12" },
  { id: "e-kanji-12-13", source: "kanji-12", target: "kanji-13" },
  { id: "e-kanji-13-14", source: "kanji-13", target: "kanji-14" },
  { id: "e-kanji-14-15", source: "kanji-14", target: "kanji-15" },
  { id: "e-kanji-15-16", source: "kanji-15", target: "kanji-16" },
  { id: "e-kanji-16-17", source: "kanji-16", target: "kanji-17" },
  { id: "e-kanji-17-18", source: "kanji-17", target: "kanji-18" },
  { id: "e-kanji-18-19", source: "kanji-18", target: "kanji-19" },
  { id: "e-kanji-19-20", source: "kanji-19", target: "kanji-20" },
  { id: "e-kanji-20-21", source: "kanji-20", target: "kanji-21" },
  { id: "e-kanji-21-22", source: "kanji-21", target: "kanji-22" },
  { id: "e-kanji-22-23", source: "kanji-22", target: "kanji-23" },
  { id: "e-kanji-23-24", source: "kanji-23", target: "kanji-24" },
  { id: "e-kanji-24-25", source: "kanji-24", target: "kanji-25" },
  { id: "e-kanji-25-26", source: "kanji-25", target: "kanji-26" },
  { id: "e-kanji-26-27", source: "kanji-26", target: "kanji-27" },
  { id: "e-kanji-27-28", source: "kanji-27", target: "kanji-28" },
  { id: "e-kanji-28-29", source: "kanji-28", target: "kanji-29" },
  { id: "e-kanji-29-30", source: "kanji-29", target: "kanji-30" },
  { id: "e-kanji-30-31", source: "kanji-30", target: "kanji-31" },
  {
    id: "edge-main-listening",
    source: "kanji-31",
    target: "main-listening",
  },
  {
    id: "edge-listening-1",
    source: "main-listening",
    target: "listening-1",
  },
  {
    id: "edge-main-reading",
    source: "main-listening",
    target: "main-reading",
  },
  {
    id: "edge-reading-1",
    source: "main-reading",
    target: "reading-1",
  },
  {
    id: "edge-reading-1-2",
    source: "reading-1",
    target: "reading-2",
  },
  {
    id: "edge-reading-2-3",
    source: "reading-2",
    target: "reading-3",
  },
];
