import { Edge } from "reactflow";

export type RoadmapStatus = "todo" | "doing" | "done";

export interface RoadmapNodeMeta {
  id: string;
  label: string;
  description: string;
  status: RoadmapStatus;
  main: boolean;
  x: number;
  y: number;
  href?: string;
}

export interface RoadmapNodeData extends RoadmapNodeMeta {
  status: RoadmapStatus;
}

export const BASE_META: RoadmapNodeMeta[] = [
  {
    id: "main-words",
    label: "Từ vựng",
    description: "Học từ vựng theo 新完全マスター ",
    status: "doing",
    main: true,
    x: 462,
    y: -4,
  },
  {
    id: "word-1",
    label: "Bài 1",
    description: "性格・人柄・個性 (Tính cách)",
    status: "done",
    main: false,
    x: 900,
    y: -298,
    href: "/tu-vung/n1/page1",
  },
  {
    id: "word-2",
    label: "Bài 2",
    description: "人間関係・付き合い・恋愛 (Quan hệ & cảm xúc)",
    status: "done",
    main: false,
    x: 900,
    y: -208,
    href: "/tu-vung/n1/page2",
  },
  {
    id: "word-3",
    label: "Bài 3",
    description: "料理・食べ物・味・匂い (Ẩm thực)",
    status: "done",
    main: false,
    x: 900,
    y: -118,
    href: "/tu-vung/n1/page3",
  },
  {
    id: "word-4",
    label: "Bài 4",
    description: "住居 (Nhà ở)",
    status: "done",
    main: false,
    x: 900,
    y: -28,
    href: "/tu-vung/n1/page4",
  },
  {
    id: "word-5",
    label: "Bài 5",
    description: "病気・治療 (Bệnh tật & điều trị)",
    status: "done",
    main: false,
    x: 900,
    y: 62,
    href: "/tu-vung/n1/page5",
  },
  {
    id: "word-6",
    label: "Bài 6",
    description: "健康・芸術 (Sức khỏe & Nghệ thuật)",
    status: "done",
    main: false,
    x: 1355,
    y: -298,
    href: "/tu-vung/n1/page6",
  },
  {
    id: "word-7",
    label: "Bài 7",
    description: "教育 (Giáo dục)",
    status: "done",
    main: false,
    x: 1355,
    y: -208,
    href: "/tu-vung/n1/page7",
  },
  {
    id: "word-8",
    label: "Bài 8",
    description: "仕事・職業 (Công việc & Nghề nghiệp)",
    status: "done",
    main: false,
    x: 1355,
    y: -118,
    href: "/tu-vung/n1/page8",
  },
  {
    id: "word-9",
    label: "Bài 9",
    description: "発表・マスコミ (Trình bày & Truyền thông)",
    status: "done",
    main: false,
    x: 1355,
    y: -28,
    href: "/tu-vung/n1/page9",
  },
  {
    id: "word-10",
    label: "Bài 10",
    description: "性格・人柄・個性・人間関係 (Tính cách & Quan hệ)",
    status: "done",
    main: false,
    x: 1355,
    y: 62,
    href: "/tu-vung/n1/page10",
  },
  {
    id: "word-11",
    label: "Bài 11",
    description: "料理・食べ物・育児・住居 (Ẩm thực & Nuôi con & Nhà ở)",
    status: "done",
    main: false,
    x: 1810,
    y: -298,
    href: "/tu-vung/n1/page11",
  },
  {
    id: "word-12",
    label: "Bài 12",
    description: "病気・治療・健康・芸術 (Bệnh tật & Sức khỏe & Nghệ thuật)",
    status: "done",
    main: false,
    x: 1810,
    y: -208,
    href: "/tu-vung/n1/page12",
  },
  {
    id: "word-13",
    label: "Bài 13",
    description: "スポーツ (Thể thao)",
    status: "done",
    main: false,
    x: 1810,
    y: -118,
    href: "/tu-vung/n1/page13",
  },
  {
    id: "word-14",
    label: "Bài 14",
    description: "学校・教育 (Trường học & Giáo dục)",
    status: "done",
    main: false,
    x: 1810,
    y: -28,
    href: "/tu-vung/n1/page14",
  },
  {
    id: "word-15",
    label: "Bài 15",
    description: "仕事・職業 (Công việc & Nghề nghiệp)",
    status: "done",
    main: false,
    x: 1810,
    y: 62,
    href: "/tu-vung/n1/page15",
  },
  {
    id: "word-16",
    label: "Bài 16",
    description: "メディア・経済・産業 (Truyền thông & Kinh tế & Sản nghiệp)",
    status: "done",
    main: false,
    x: 2265,
    y: -298,
    href: "/tu-vung/n1/page16",
  },
  {
    id: "word-17",
    label: "Bài 17",
    description: "政治・法律・歴史 (Chính trị & Pháp luật & Lịch sử)",
    status: "done",
    main: false,
    x: 2265,
    y: -208,
    href: "/tu-vung/n1/page17",
  },
  {
    id: "word-18",
    label: "Bài 18",
    description: "格差社会・少子高齢化 (Chênh lệch xã hội & Già hóa dân số)",
    status: "done",
    main: false,
    x: 2265,
    y: -118,
    href: "/tu-vung/n1/page18",
  },
  {
    id: "word-19",
    label: "Bài 19",
    description: "気象・地形・天体・機械 (Thời tiết & Địa hình & Thiên thể & Máy móc)",
    status: "done",
    main: false,
    x: 2265,
    y: -28,
    href: "/tu-vung/n1/page19",
  },
  {
    id: "word-20",
    label: "Bài 20",
    description: "時間・空間・関係 (Thời gian & Không gian & Mối quan hệ)",
    status: "done",
    main: false,
    x: 2265,
    y: 62,
    href: "/tu-vung/n1/page20",
  },
  {
    id: "word-21",
    label: "Bài 21",
    description: "変化・関係・由緒 (Biến đổi & Mối quan hệ)",
    status: "done",
    main: false,
    x: 2720,
    y: -298,
    href: "/tu-vung/n1/page21",
  },
  {
    id: "word-22",
    label: "Bài 22",
    description: "意味がたくさんある言葉 23 (Từ nhiều nghĩa - 1)",
    status: "done",
    main: false,
    x: 2720,
    y: -208,
    href: "/tu-vung/n1/page22",
  },
  {
    id: "word-23",
    label: "Bài 23",
    description: "意味がたくさんある言葉 24 (Từ nhiều nghĩa - 2)",
    status: "done",
    main: false,
    x: 2720,
    y: -118,
    href: "/tu-vung/n1/page23",
  },
  {
    id: "word-24",
    label: "Bài 24",
    description: "さらう・しのぐ・断つ・絶つ・弾む・ふるまう",
    status: "done",
    main: false,
    x: 2720,
    y: -28,
    href: "/tu-vung/n1/page24",
  },
  {
    id: "word-25",
    label: "Bài 25",
    description: "副詞・形容詞 (Phó từ & Tính từ đặc biệt)",
    status: "done",
    main: false,
    x: 2720,
    y: 62,
    href: "/tu-vung/n1/page25",
  },
  {
    id: "word-26",
    label: "Bài 26",
    description: "形が似ている言葉 - 規・発・補・賛・弁・持続 (Từ hình giống nhau)",
    status: "done",
    main: false,
    x: 3175,
    y: -298,
    href: "/tu-vung/n1/page26",
  },
  {
    id: "word-27",
    label: "Bài 27",
    description: "形容詞・動詞グループ (Nhóm tính từ & động từ)",
    status: "done",
    main: false,
    x: 3175,
    y: -208,
    href: "/tu-vung/n1/page27",
  },
  {
    id: "word-28",
    label: "Bài 28",
    description: "副詞 - 程度・様子 (Phó từ mức độ & trạng thái)",
    status: "done",
    main: false,
    x: 3175,
    y: -118,
    href: "/tu-vung/n1/page28",
  },
  {
    id: "word-29",
    label: "Bài 29",
    description: "副詞 - 時間・推量 (Phó từ thời gian & suy đoán)",
    status: "done",
    main: false,
    x: 3175,
    y: -28,
    href: "/tu-vung/n1/page29",
  },
  {
    id: "word-30",
    label: "Bài 30",
    description: "副詞 - 方法・範囲 (Phó từ phương pháp & phạm vi)",
    status: "done",
    main: false,
    x: 3175,
    y: 62,
    href: "/tu-vung/n1/page30",
  },
  {
    id: "word-31",
    label: "Bài 31",
    description: "副詞 - 態度・意志 (Phó từ thái độ & ý chí)",
    status: "done",
    main: false,
    x: 3630,
    y: -298,
    href: "/tu-vung/n1/page31",
  },
  {
    id: "word-32",
    label: "Bài 32",
    description: "副詞 - 様子・状態 (Phó từ trạng thái - tổng hợp)",
    status: "done",
    main: false,
    x: 3630,
    y: -208,
    href: "/tu-vung/n1/page32",
  },
  {
    id: "main-grammar",
    label: "Ngữ pháp",
    description: "Học ngữ pháp theo 新完全マスター ",
    status: "todo",
    main: true,
    x: 462,
    y: 285,
  },
  {
    id: "grammar-1",
    label: "Bài 1",
    description: "Bài 1: Ngữ pháp về chủ để XYZ",
    status: "todo",
    main: false,
    x: 90,
    y: 400,
  },
  {
    id: "grammar-2",
    label: "Bài 2",
    description: "Bài 2: Ngữ pháp về chủ để ABC",
    status: "todo",
    main: false,
    x: 90,
    y: 490,
  },
  {
    id: "grammar-3",
    label: "Bài 3",
    description: "Bài 3: Ngữ pháp về chủ để DEF",
    status: "todo",
    main: false,
    x: 90,
    y: 580,
  },
];

export const BASE_EDGES: Edge[] = [
  {
    id: "edge-1",
    source: "main-words",
    target: "word-1",
  },
  { id: "e-word-2", source: "word-1", target: "word-2" },
  { id: "e-word-3", source: "word-2", target: "word-3" },
  { id: "e-word-4", source: "word-3", target: "word-4" },
  { id: "e-word-5", source: "word-4", target: "word-5" },
  { id: "e-word-6", source: "word-5", target: "word-6" },
  { id: "e-word-7", source: "word-6", target: "word-7" },
  { id: "e-word-8", source: "word-7", target: "word-8" },
  { id: "e-word-9", source: "word-8", target: "word-9" },
  { id: "e-word-10", source: "word-9", target: "word-10" },
  { id: "e-word-11", source: "word-10", target: "word-11" },
  { id: "e-word-12", source: "word-11", target: "word-12" },
  { id: "e-word-13", source: "word-12", target: "word-13" },
  { id: "e-word-14", source: "word-13", target: "word-14" },
  { id: "e-word-15", source: "word-14", target: "word-15" },
  { id: "e-word-16", source: "word-15", target: "word-16" },
  { id: "e-word-17", source: "word-16", target: "word-17" },
  { id: "e-word-18", source: "word-17", target: "word-18" },
  { id: "e-word-19", source: "word-18", target: "word-19" },
  { id: "e-word-20", source: "word-19", target: "word-20" },
  { id: "e-word-21", source: "word-20", target: "word-21" },
  { id: "e-word-22", source: "word-21", target: "word-22" },
  { id: "e-word-23", source: "word-22", target: "word-23" },
  { id: "e-word-24", source: "word-23", target: "word-24" },
  { id: "e-word-25", source: "word-24", target: "word-25" },
  { id: "e-word-26", source: "word-25", target: "word-26" },
  { id: "e-word-27", source: "word-26", target: "word-27" },
  { id: "e-word-28", source: "word-27", target: "word-28" },
  { id: "e-word-29", source: "word-28", target: "word-29" },
  { id: "e-word-30", source: "word-29", target: "word-30" },
  { id: "e-word-31", source: "word-30", target: "word-31" },
  { id: "e-word-32", source: "word-31", target: "word-32" },
  {
    id: "edge-main-1",
    source: "main-words",
    target: "main-grammar",
  },
  { id: "e-grammar-1", source: "main-grammar", target: "grammar-1" },
  { id: "e-grammar-1-2", source: "grammar-1", target: "grammar-2" },
  { id: "e-grammar-2-3", source: "grammar-2", target: "grammar-3" },
];
